### ISSUE TITLE
Possibility to add custom fields & option fields via Dashboard

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#10]
Hey, TypeRocket has very clean & clear interfaces and API. Maybe better than the current ACF Pro in skin side.

In the future, is there any possibility to _add custom fields & option fields_ via Dashboard like ACF do? Think it doesn't have to be as feature-rich as ACF Pro. Since it is "Pro". TypeRocket in future could be "TypeRocket Pro" too. But is it good idea to have those (adding fields via dashboard) ability?

**Comment by kevindees** [comment]
Hey,

Typerocket actually does this already.

## Custom Forms

You can add forms and fields to the dashboard if you like. Depending on what you want to do you will need to customize the form but here is a simple example of submitting a dashboard form to a custom URL without using AJAX as the submission method.

``` php
$box = tr_meta_box('Dashboard Fields');
$box->addScreen('dashboard');
$box->setCallback(function() {

    $form = tr_form();

    /**
     * Open Form Element
     *
     * @param array $attr set the form attributes
     * @param bool $use_rest use the rest api
     */
    echo $form->open(['action' => '/path/to/submit/to'], false);
    echo $form->text('Custom Field');
    echo $form->submit('Submit');
    echo $form->close();

});
```

## Custom REST Form

You can also take advantage of the Typerocket REST API and create a draft post on the dashboard.

``` php
$box = tr_meta_box('Create Draft Post');
$box->addScreen('dashboard');
$box->setCallback(function() {

    $form = tr_form('posts', 'create');

    echo $form->open();

    // set field name to the column name in the wp_posts
    echo $form->text('post_title')->setLabel('Post Title');
    echo $form->textarea('post_content')->setLabel('Content');
    echo $form->submit('Create Draft');
    echo $form->close();

});
```

Or, you can have the post set to published.

``` php
$box = tr_meta_box('Publish Post');
$box->addScreen('dashboard');
$box->setCallback(function() {

    $form = tr_form('posts', 'create');

    echo $form->open();

    // set field name to the column name in the wp_posts
    echo $form->text('post_title')->setLabel('Post Title');
    echo $form->textarea('post_content')->setLabel('Content');
    echo $form->hidden('post_status', ['value' => 'publish']);
    echo $form->submit('Publish');
    echo $form->close();

});
```

**Comment by ghost** [comment]
wow thanks for the responses Kevin!

Although it this is pretty different thing with what i asked. 
_via dashboard_ means adding new custom fields/ option fields using drag & drop/ administrative interface.

Currently, TypeRocket adds everything in coding side. Will it be possible in the future to add custom fields/ option fields using administrative/ post type/ drag n drop interface?

Thanks!

**Comment by kevindees** [comment]
One of the core visions for TypeRocket is to keep everything in the code.
- We believe that data structure should not be bound to the database 
- We believe that structure should be permanent and easily distributed through version control

With this in mind, we have no plans to create a drag and drop feature like Advanced Custom Fields. For those times, when you need it, we highly encourage everyone to use ACF.
