### ISSUE TITLE
How to create post in front-end

### ISSUE THREAD

**Issue by hieuhv** [TypeRocket/typerocket#104]
My route:
tr_route()->get('/post/create', function(){
    return tr_view('posts.create')->setTitle('Create Post');
});

My view: 
/resources/views/posts/create.php
$form = tr_form('post', 'create');
    echo $form->open();
    echo $form->text('Post Title');
    echo $form->textarea('Post Content');
    echo $form->submit('Create Post');
    echo $form->close();

When click submit button an 404 error, can not create new posts.

**Comment by kevindees** [comment]
Hey @hieuhv 

You will also need a post route that take the post request from the form and stores it. You may want to follow this example to get your mind wrapped about hoe MVC works in the system. This example is not for the front-end but the same ideas apply.

https://typerocket.com/docs/v3/custom-resources/

Thanks,
Kevin

**Comment by kevindees** [comment]
Hey @hieuhv 

Here is an issue with a more detailed description:

https://github.com/TypeRocket/typerocket/issues/98
