### ISSUE TITLE
How to add more css and js file for the custom post type.

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#107]
Hello TypRocket Team,
I want to add more CSS and js for the custom post type in the backend. I look at the documentation but I don't get any hook or any function. it is possible to add custom CSS or js ??

**Comment by Biswash-Developer** [comment]
@robojuicie @kevindees

**Comment by kevindees** [comment]
@Biswash-Developer 

WordPress itself provides what you are looking for in this case:

https://davidwalsh.name/add-custom-css-wordpress-admin

Thanks,
Kevin
