### ISSUE TITLE
Setting empty value for color picker field

### ISSUE THREAD

**Issue by maxia** [TypeRocket/typerocket#109]
Hello,

I noticed that it is currently impossible to set a empty default value (e.g. NULL) for a color picker field.
If the current value is falsy, it will set #000000 by default.

Is there any way to fix this?

**Comment by kevindees** [comment]
Hey @maxia 

Right now there is no feature for this. I'm not 100% sure but I think that color picker we use is the one WordPress comes with and it requires a value. You can always use a checkbox to have the user request no color but used and then use the checkbox value to control the condition you want.

I hope this helps.

Thanks,
Kevin

**Comment by kevindees** [comment]
@maxia 

This is now fixed in core. You can do a composer update to get the patch.

Thanks,
Kevin
