### ISSUE TITLE
Builder configuration

### ISSUE THREAD

**Issue by zoephilipps** [TypeRocket/typerocket#111]
Would love to be able to include a builder configuration file that groups blocks into builder fields. Currently, if you want separate builder fields, they must each have their own folder. This becomes redundant when two builder fields have the same blocks. Consider the following configuration:

```php
<?php

return [
  'flex' => [
    '03-billboard',
    '04-simple-content',
    '05a-text-media-split-full',
    '05b-text-media-split-contained',
    '06a-brackets',
    '06b-brackets',
    '07-gallery-grid',
    '08-post-grid',
    '10-quote-carousel',
    '11-profile-grid',
    '12-logos',
    '13-form',
    '14-code'
  ],
  'flex-lp' => [
    '03-billboard',
    '04-simple-content',
    '05a-text-media-split-full',
    '05b-text-media-split-contained',
    '10-quote-carousel',
    '13-form',
    '14-code'
  ],
  'intro-flex' => [
    '01a-big-hero',
    '01b-standard-hero',
    '02-simple-header'
  ]
];

?>
```

This would eliminate the need for folders for each field. However, the "component folder" concept is so ingrained in the current code that I wanted to run this by you rather than slog through it and open up a PR. Since I also know that you have TR v4 in the works.

You could potentially put other stuff in this config like the component name/label and a callback (`'func'` or `['Class', 'func']`).

Just FYI I was also toying around with making my own version of the `tr_components_field` function that directly renders a Twig file instead of including a PHP file that renders a Twig file. Seemed pretty straightforward, but might make sense to incorporate something like that into TR core as well. I feel like most people are turning to cleaner front end template solutions like Twig and Blade.

**Comment by kevindees** [comment]
Hey @zackphilipps 

You can keep all of your components in one folder and set the the options using the `setOptions()` method on the builder field. If you are using the plugin you will need to modify the plugin file or use your own.

Also, you can control what folder the builder field looks for using the `setComponentFolder()` method. https://github.com/TypeRocket/core/blob/master/src/Elements/Fields/Matrix.php#L324

Let me know if this helps.

Thanks,
Kevin

**Comment by zoephilipps** [comment]
@kevindees Nice, thanks for the tip about `setOptions()`! I still had to have a separate folder for `intro-flex` because I needed `intro-flex` and `flex` on the same post type. `setOptions()` allowed me to remove the redundancy though.

Also, FWIW, I'm using [Timber](https://www.upstatement.com/timber/) and here's what I ended up doing for the visuals, which removed the need for visual folders altogether:

```php
function he_components_field(
  $name,
  $item_id = null,
  $modelClass = \TypeRocket\Models\WPPost::class
) {

  // ...

  if ( is_array( $builder_data ) ) {
    foreach ( $builder_data as $data ) {
      $key       = key( $data );
      $component = strtolower( key( $data ) );

      $context = Timber::get_context();
      $context['data'] = $data[$key];
      $context['post'] = Timber::get_post();

      Timber::render( implode( '/', [$component, $component . '.twig'] ), $context );
    }
  }

  return $builder_data;
}
```

Thanks again, TypeRocket is freaking awesome.
