### ISSUE TITLE
Referencing page builder component data in another page builder component?

### ISSUE THREAD

**Issue by egrobler** [TypeRocket/typerocket#112]
I am fairly new to TypeRocket, so please bear with me.
I've created a simple component much like the Content Component that comes bundled for the Page Builder. Now I have another component with a search field, where one can add pages in the component. And I would like to get the $data['content'] from that other component and pull it's value into this one. The only way I could manage to do it was to create a query that queries the post_meta table for the page_id and 'builder' meta_key.
Isn't there supposed to be a more elegant way to do this?

**Comment by kevindees** [comment]
Hey @egrobler 

There is a better way. Can you post your code for your component and visual files?

Thanks,
Kevin

**Comment by egrobler** [comment]
So I have 2 components, a Page Intro component and Page Cards component. The Page Cards one, needs to get the 'intro_text' value from the Page Intro component for a specific page (result from the search box in the Page Cards component).

I don't have the visual for the Page Intro component yet, since I'm still working on the Page Cards one.

I created a gist for the code as the code doesn't display really well for me in thie markdown editor. Apologies. 
Gist: https://gist.github.com/egrobler/e9a0ba28c408f8e6b382d6dd3ccef1db

Thanks again!

**Comment by kevindees** [comment]
Hey @egrobler 

I see what you are asking now. If you are looking to have shared data between components you will need to make your own builder field function to call from your theme instead of calling `tr_components_field ()`.

Below I created a new function that passes all the components to the visual. See `use ($builder_data)`. You can then access all the builder fields using the `$builder_data` from any visual file.

However, having one builder component dependant on another component might not be the best architecture. I would recommend having shared data live within a metabox that is always present. I'm not sure what your project constraints are but it may be best to look into another approach.  

```php
function your_components_field($name, $item_id = null, $modelClass = \TypeRocket\Models\WPPost::class )
{
    global $post;
    if (isset($post->ID) && is_null($item_id)) {
        $item_id = $post->ID;
    }
    /** @var \TypeRocket\Models\Model $model */
    $model = new $modelClass;
    $model->findById($item_id);
    $builder_data = $model->getFieldValue($name);
    if (is_array($builder_data)) {
        foreach ($builder_data as $data) {
            $key       = key($data);
            $component = strtolower(key($data));
            $paths = \TypeRocket\Core\Config::getPaths();
            $file  = $paths['visuals'] . '/' . $name . '/' . $component . '.php';
            if( file_exists($file) ) {
                $fn = function( $file, $data, $name, $item_id, $model) use ($builder_data) {
                    /** @noinspection PhpIncludeInspection */
                    include( $file );
                };
                $fn($file, $data[$key], $name, $item_id, $model);
            } else {
                echo "<div class=\"tr-dev-alert-helper\"><i class=\"icon tr-icon-bug\"></i> Add builder visual here by creating: <code>{$file}</code></div>";
            }
        }
    }
    return $builder_data;
}
```

**Comment by egrobler** [comment]
Thanks @kevindees , got it.

What I tried to do was just a nice to have for the client, but I guess I'll just remove it for now. And thanks for the code snippet to, I'll keep it in my back pocket. :)
