### ISSUE TITLE
The controller does not work for guests

### ISSUE THREAD

**Issue by KarimQaderi** [TypeRocket/typerocket#114]
Hello,

The controller does not work for guests

This message shows
`Sorry, you don't have enough rights.`

My codes

route.php
```
tr_route()->get('/lists', 'index@Lists');
```

ListsController.php
```
namespace App\Controllers;

use \TypeRocket\Controllers\Controller;

class ListsController extends Controller
{
    public function index()
    {
        return "index";
    }
}
```

**Comment by kevindees** [comment]
@KarimQaderi

In your Kernel file, you need to disable the `AuthRead::class` requirement for the `resourceGlobal` group by removing it from the code. That specific class blocks anyone who is not logged in from accessing a custom route. We have by default the most secure settings for custom routes. If this does not fix your problem then try some of the other middleware registered to the Kernel.

 https://typerocket.com/docs/v3/kernel/

Thanks,
Kevin

**Comment by KarimQaderi** [comment]
tnx

**Comment by twosg** [comment]
Hi,

I have the same problem, but I needed to modify this to get it working:

```
'noResource' => [
        	//AuthAdmin::class
        ],
```

Should I define a resource name for a public controller? If yes how and where? :)
