### ISSUE TITLE
tr_route() not working ?

### ISSUE THREAD

**Issue by thaihiep098** [TypeRocket/typerocket#116]
tr_route()->get('/foo', function( $path, \TypeRocket\Http\Request $request, $wilds ) {
    echo $path;
});

However, I'm getting a 404 page not found in the TwentySeventeen theme. Am I missing something?

**Comment by kevindees** [comment]
Hey @thaihiep098 

In your Kernel file, you need to disable the `AuthRead::class` requirement for the `resourceGlobal` group by removing it from the code. That specific class blocks anyone who is not logged in from accessing a custom route. We have by default the most secure settings for custom routes. If this does not fix your problem then try some of the other middleware registered to the Kernel.

 https://typerocket.com/docs/v3/kernel/

Thanks,
Kevin

**Comment by thaihiep098** [comment]
Thank you, greetings. It working
