### ISSUE TITLE
How to use meta_key and meta_value in WPPost ?

### ISSUE THREAD

**Issue by thaihiep098** [TypeRocket/typerocket#117]
Hi @kevindees
I am encountering an issue : 
$docs = (new Post())->where('meta_key', 'is_featured')->where('meta_value', 1)->get();

It not working , please support

Thanks,
thaihiep

**Comment by kevindees** [comment]
Hey @thaihiep098 

There is no shortcut option to do what you are asking. It might be best to use the `WP_Query` to do what you want.

https://codex.wordpress.org/Class_Reference/WP_Query#Custom_Field_Parameters

```php
$args = array(
	'meta_key'   => 'color',
	'meta_value' => 'blue'
);
$query = new WP_Query( $args );
```

If you are a more advanced user you might want to look at using Laravel's Eloquent package.

https://www.slimframework.com/2013/03/21/slim-and-laravel-eloquent-orm.html

Thanks,
Kevin
