### ISSUE TITLE
How to set default value in tr_form()->gallery() or tr_form()->image() ?

### ISSUE THREAD

**Issue by thaihiep098** [TypeRocket/typerocket#120]
hi @kevindees ,

My code :
echo $form->image()->setSettings('value', 4);

but it not working ..

**Comment by kevindees** [comment]
Hey @thaihiep098 

The image field does not have a set default option. The best way to do this is to set the default in the theme template files. It is almost always better to have a blank value stored and have the default set independent of the field. The exceptions to this rules are for radio and select inputs.

Thanks,
Kevin
