### ISSUE TITLE
Tables with Redactor

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/typerocket#121]
Hi

I see in the documentation that TypeRocket is using "Redactor 10".
On Redactor's website, it seems that the latest version is "Redactor 3", and there is no documentation for "Redactor 10". Does "10" means "1.0" ?

I'm looking for a way to add a "table" button in the toolbar.

**Comment by kevindees** [comment]
Hey @clemorphy 

Yes, version 10 is an older version. They just changed how they were versioning the system. They have the docs for the older version in a PDF file. https://imperavi.com/assets/pdf/redactor-documentation-10.pdf

There is also a link to their docs in the TypeRocket docs: https://typerocket.com/docs/v3/field-types/#section-editor

However, you would need their old table plugin but it is not available.

Thanks,
Kevin

**Comment by clemorphy** [comment]
Do you mean we can't use tables with the version of Redactor used by TypeRocket ?

**Comment by kevindees** [comment]
Hey @clemorphy 

I was able to locate the old plugins. You can download the table one here: 

https://typerocket.com/wp-content/uploads/redactor-plugins/table.zip

Thanks,
Kevin

**Comment by clemorphy** [comment]
Thank you so much :+1: 
I managed to have it working.

> I was able to locate the old plugins.

Do you mean there are more plugins available for Redactor 10 ?
Could you please indicate me where you found those old plugins ?

**Comment by kevindees** [comment]
https://github.com/TypeRocket/core/tree/v4.0/assets/js/lib/redactor

**Comment by clemorphy** [comment]
Great :smiley: 
Thank you.
