### ISSUE TITLE
Get a list of page builder components that's currently being used?

### ISSUE THREAD

**Issue by egrobler** [TypeRocket/typerocket#123]
Hi there,

I've created a bunch of page builder components, and now some time later, I realise that there are some that I've built initially but aren't using them anymore. Is there a way to query the database to get a list of all the components currently in use, so I can remove the unused ones?

I'm sorry for creating an issue for this question, just wasn't sure where to ask it.

**Comment by kevindees** [comment]
Hey @egrobler 

There is no way to be 100% sure but running a SQL query looking for the components name might do the trick. For example:

```sql
select * from wp_postmeta where meta_value like '%"banner";%' and meta_key = 'builder'
```

Then replace `banner` with your components name.

Thanks,
Kevin
