### ISSUE TITLE
Page builder buttons translations

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/typerocket#124]
Hi

Is there a clean way to modify and / or translate the buttons in the admin interface of the builder.
Ex : the "Add new" button, and in the repeater fields, the "Add new", "Flip", "Contract", "Expand", "Clear all" buttons.

Thanx

**Comment by kevindees** [comment]
Yes,

You do this using the fields method `setControls()` and pass in an array with the corresponding data. In v4 beta there are more options than with v3. I recommend using v4 beta.

https://github.com/TypeRocket/typerocket/releases/tag/v4.0.0-beta1

In v4 beta you have these options:

```php
$form->repeater('Name')->setControls([
	    'contract' => 'Contract',
	    'expand' => 'Expand',
	    'flip' => 'Flip',
	    'clear' => 'Clear All',
	    'add' => 'Add',
]);
```

Thanks,
Kevin

**Comment by clemorphy** [comment]
Thank you.

I found that the builder's button also can be set with `setSettings` :

`$form->builder('builder-name')->setSettings(['add_button'=>'Add an element']);`

So from now you recommend using v4 beta.

What is the recomended way to upgrade to v4 beta, without losing stuff like Builder components ?
I installed v3 through the "theme installation" with composer

**Comment by kevindees** [comment]
There is no real documentation to migrate at this point. The best way to move is to install v4 beta in a new theme and migrate any custom code like components to the new theme.

This has all the notes:

https://github.com/TypeRocket/typerocket/releases/tag/v4.0.0-beta1

This is a beta release so things might change but I do not expect so many changes that it will affect many users. However, v4 does require PHP 7.0+.

Thanks,
Kevin

**Comment by clemorphy** [comment]
Ok thank you.

I'll try and let you know if I encounter difficulties or bugs with v4 beta.

Keep up the good work :+1:

**Comment by vianapatricio** [comment]
Hi, how can i change label for "Add New" for my CPT using Typerocket? im speak portuguese and need change to "Adicionar Novo". In wp is 'add_new'               => __( 'Add New', 'text_domain' ),

**Comment by kevindees** [comment]
Hey @vianapatricio 

If you need to update how WP translates its buttons you can override the TypeRocket auto-generated tables and add your own arguments using the `setArgument` method https://typerocket.com/docs/v3/post-types/#section-arguments

You can see the WP listed items here https://codex.wordpress.org/Function_Reference/register_post_type#Arguments

For example, you might try this:

```php
$args = $your_pt->getArguments();
$args = array_merge( $args, [ 'add_new' => __( 'Add New', 'text_domain' ) ] );
$your_pt->setArguments( $args );
```

Thanks,
Kevin
