### ISSUE TITLE
Code example request

### ISSUE THREAD

**Issue by zoephilipps** [TypeRocket/typerocket#125]
Hey @kevindees 

Would you mind sending along a quick code example for how to search by fields on relationships in admin tables? Let me know if you need any further explanation.

Thanks!

**Comment by kevindees** [comment]
There are two hooks that will likely help you.

1. Modify the model; In your case maybe using a join. https://github.com/TypeRocket/core/blob/master/src/Elements/Tables.php#L231
2. Add any custom output. https://github.com/TypeRocket/core/blob/master/src/Elements/Tables.php#L453
3. Also the same here for custom output for things like form filters. https://github.com/TypeRocket/core/blob/master/src/Elements/Tables.php#L215

**Comment by zoephilipps** [comment]
I was able to accomplish this with the following (this example is enabling the filtering of floorplans by the product they belong to):

```php
add_action('tr_table_search_model_floorplans', function($model, $table) {
  if(empty($_GET['on'])) return;
  $on = $_GET['on'];

  if(empty($_GET['s'])) return;
  $s = $_GET['s'];

  if($on != 'product_id') return;

  $product = (new \App\Models\Product)->where('name', wp_unslash($s))->first();
  $model = (new \App\Models\Floorplan)->where('product_id', $product->id);
  if( !empty( $_GET['order'] ) && !empty( $_GET['orderby'] ) ) {
      $model->orderBy($_GET['orderby'], $_GET['order']);
  }
  $table->model = $model;

}, 99, 2);
```

then in the view `floorplan/index.php` at the very end: `$table->render('floorplans');`
