### ISSUE TITLE
setSlug() doesn't do anything

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/typerocket#127]
Hi

I tried to use `setSlug()` with Post Types and Taxonomies, and it doesn't do anything.

`$cpt = tr_post_type('MyPostType')->setSlug('mypt');`

The slug is still `myposttype`.
I did flush the permalinks.

Any idea ?

**Comment by kevindees** [comment]
Hey @clemorphy 

This might be a bug. I'll need to look into it. You can always override using `setArguments` to do what you are asking as well.

https://typerocket.com/docs/v3/post-types/#section-arguments

Tha

**Comment by clemorphy** [comment]
I can't get it to work.
Even using `setArguments` :
`$cpt = tr_post_type('MyPostType')->setArgument( 'rewrite', ['slug' => 'mycpt'] );`

The slug is still `myposttype` :disappointed:

**Comment by clemorphy** [comment]
Ok my bad, it's working perfectly, using both methods ...
I thought the slug was used in the admin URLs too, as the `post_type` parameter, and that's what I was checking.

What I was actually looking for is the `setId()` method
