### ISSUE TITLE
TypeRocket and Yoast

### ISSUE THREAD

**Issue by GPurdue** [TypeRocket/typerocket#128]
Is there a way to get the Yoast plugin to pickup fields that have been used in a page builder?

Cheers
Gary

**Comment by kevindees** [comment]
Hey @GPurdue 

I'm sure how this might be done but the builder does use post meta so if there is a way to point Yoast to custom fields you might be able to pull it off. But at the moment TypeRocket does not have that level of integration with Yoast.

Thanks,
Kevin
