### ISSUE TITLE
Search Field Selection Doesn't Allow Deselection

### ISSUE THREAD

**Issue by richardblondet** [TypeRocket/typerocket#129]
Hello @kevindees,

Thank you for this amazing work you are doing with this project. I find it really compelling in terms of Wordpress development, really great work.

After adding the search field:

**Expected Behavior**
Allow to deselect the selected option by either clicking an [X] button or removing the value from an input.

**Actual Behavior**
Selected option is preserved after the first selection and saved. No means to go back to the no selection state.

**Steps to reproduce**
1. Add search field
```echo $form->search( 'Select post' )->setPostType( 'post' );```
2. Save the post
3. Try deselecting selected post

**Specifications**
1. Wordpress Version 4.9.8
2. Typerocket 3.0
3. PHP 7.1
4. Chrome Version 68.0.3440.84

If there's anymore information needed, please let me know. 

Thanks again!
Bests, Rich

**Comment by kevindees** [comment]
Hey @richardblondet 

We will get this updated in a version of 4.0. thanks for your suggestion.

Kevin

**Comment by kevindees** [comment]
Hey @richardblondet 

This has now been added to version 4.0 beta.

Thanks,
Kevin
