### ISSUE TITLE
tr_components_field tries to echo an array after the components

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/typerocket#131]
Hi

When I use `tr_components_field` to display the content of a custom Builder, I always have a `Array to string conversion` error at the end, after all the components have been displayed.
It's like if it was adding an array at the end of my component list, and it tries to echo it.

I'm using Twig with Timber and I'm struggling at finding what is inside this array.

Here is my twig template where I use the builder :
``` twig
{{ data[1].post_title }}
<br />
{{ fn('tr_components_field','desc_prod_builder', data[1].ID) }}
```

And here is the result :
``` html
My post title
<br />
<h1>Content of my component</h1><br />
<b>Notice</b>:  Array to string conversion in <b>/var/www/html/wp-content/themes/understrap/vendor/twig/twig/lib/Twig/Environment.php(378) : eval()'d code</b> on line <b>30</b><br />
Array
```

As soon an there is at least one component in my builder's content, it adds this array at the end.

Any idea of what this array could be ?

**Comment by clemorphy** [comment]
I thought I tried all I could, but once again, with some more digging, I found that it comes from the `tr_components_field` function itself, which renders directly the output by including the component files, but ALSO returns all the components data at the end.

Twig is trying to echo the returned data, but as it's an array, and not a string, it doesn"t work.

So in my Twig template, I just need to execute the `tr_components_field` function and ignore the returned data : 
`{% do fn('tr_components_field','desc_prod_builder', data[1].ID) %}`
instead of
`{{ fn('tr_components_field','desc_prod_builder', data[1].ID) }}`

By the way, why does `tr_components_field` return all the data in addition of  printing them ?

**Comment by kevindees** [comment]
Hey @clemorphy 

It returns the data just in case you want to do something with that data. There is really no other reason for it to be that way. Internally it is not used. It is just a function to help display components.

Thanks,
Kevin
