### ISSUE TITLE
Adding fields to nav menu items

### ISSUE THREAD

**Issue by cdayjr** [TypeRocket/typerocket#132]
Unless I'm missing something, it doesn't look like it's currently possible to add fields to navigation menu items. As it can be pretty useful to let the menu area have extra fields (for example, I've been using them to set fontawesome icons next to navigation items in my theme), I'd like to make a feature request for this.

**Comment by kevindees** [comment]
Hey @cdayjr Noted.

**Comment by kevindees** [comment]
Hey @cdayjr 

I am going to table this request for now but you can do what you are asking by following this tutorial.

https://www.wpexplorer.com/adding-custom-attributes-to-wordpress-menus/
