### ISSUE TITLE
What about pagination?

### ISSUE THREAD

**Issue by richardblondet** [TypeRocket/typerocket#134]
So what about pagination for the model, is it included? I ask because couldn't find it in the docs, maybe I missed it. 

Anyways, awesome work! 
Thanks!

**Comment by kevindees** [comment]
Hey @richardblondet 

We do not currently have a pagination method for models but I can see one being added soon. Were you needing it for the WP admin or for the front-end?

Thanks,
Kevin

**Comment by richardblondet** [comment]
Hi @kevindees 

We were wondering for the front-end. 

👍

**Comment by kevindees** [comment]
Hey @richardblondet 

I have no current plans to add pagination to models yet. I have some ideas for a future version though.
