### ISSUE TITLE
No theming when accesing a public controller

### ISSUE THREAD

**Issue by rdeeb** [TypeRocket/typerocket#135]
## Scenario
I created a new item in the woocommerce account menu, and tied that item to a new route (`tr_route`) to a controller.

## Expected result
When returning a view (`tr_view`) the page returns my content with the theme output (this is how admin pages works). 

## What I got
An empty page with just the view output (no theming).

**So my question is:** I'm I doing something wrong, or do I need to call `get_header()` and `get_footer` and whatever else is needed for my theme on each view?

**Comment by kevindees** [comment]
Hey @rdeeb 

Thanks for the detailed question.

You are correct. The WP admin does not require any framing code but your front-end views files will require `get_header()` and `get_footer()` if you use them. The view files for the front-end will work very similar to how most WP templates do.

The need for `get_header()` and `get_footer()` is not written about in the [docs for view files](https://typerocket.com/docs/v3/views/#section-front-end-views) on the front-end. So, if you were wondering if there was a bug there is not a bug.

Thanks,
Kevin
