### ISSUE TITLE
Custom Controller : "Invalid CSRF Token" with POST method

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/typerocket#136]
Hi

I created a custom controller (a "thin" one) and I am trying to handle a POST request through a method in this controller.

All I get when the method is triggered is a HTTP 500 error with the message "Invalid CSRF Token".

When I handle the POST request in an anonymous function directly in the routes.php file, I don't get this error.

Do I have to add a nonce field filled with a token, or something similar, in addition to my posted data ?
Or is there a way to bypass this CSRF token check ?

Thanx

**Comment by kevindees** [comment]
Hey @clemorphy 

Anonymous functions in routes bypass the middleware system (the CSRF check is done through middleware). The check is managed here: https://github.com/TypeRocket/typerocket/blob/master/app/Http/Middleware/VerifyNonce.php

You can disable it for a path like so.

```php
<?php
namespace App\Http\Middleware;
use \TypeRocket\Http\Middleware\BaseVerify;
/**
 * Class ValidateNonce
 *
 * Validate WP Nonce
 */
class VerifyNonce extends BaseVerify  {
    public $except = [
        '/my/path/here',
        '/another-path-with-wild/*'
    ];
}
```

**Comment by clemorphy** [comment]
Ok, thank you, I am now able to bypass the CSRF check.

But what if I want to keep this check ?
Is there a way to use this check to secure my custom forms ? Like adding a nonce field in my forms ?
I tried to add a builtin WP nonce field in my form (with `wp_nonce_field`), but I guess TypeRocket is not waiting for this.

**Comment by kevindees** [comment]
Hey @clemorphy 

You can add a nonce field in two ways:

```php
// For a hidden input field
tr_nonce_field()
```
https://github.com/TypeRocket/core/blob/master/functions/helpers.php#L537-L545

Or, manually yourself.

```php
// Yourself
$action = 'form_' . \TypeRocket\Core\Config::locate('app.seed');
$name = '_tr_nonce_form';
wp_nonce_field($action, $name, false, false);
```

Other ways:

https://codex.wordpress.org/Function_Reference/wp_create_nonce
https://codex.wordpress.org/Function_Reference/wp_nonce_url

**Comment by clemorphy** [comment]
Thanx @kevindees 
I have disabled the check for now but I'll try to add the nonce when I have some time.
