### ISSUE TITLE
MetaBox methods don't work

### ISSUE THREAD

**Issue by zoephilipps** [TypeRocket/typerocket#137]
Hey @kevindees,

I'm noticing that `setContext()` and `setPriority()` don't seem to do anything. Also, it seems strange to have the default priority of all metaboxes set to "high."

Just FYI!

**Comment by kevindees** [comment]
Hey @zackphilipps 

Have you moved the boxes after setting the context? WP overrides the defaults as soon as you move one.

Thanks,
Kevin

**Comment by zoephilipps** [comment]
@kevindees Nope. This is happening because `tr_meta_box` calls `addToRegistry()` at the end thus making it impossible to use any of the `MetaBox` methods to set settings when using `tr_meta_box`.

You can use the 3rd argument (`$settings` array) and it works fine. You could also call the `MetaBox` constructor directly. However, at the very least, the docs regarding all of this are a bit disingenuous.

**Comment by kevindees** [comment]
@zackphilipps 

This is working as expected for me. I'll change the default priority to what WP defaults. If you are still seeing this let me know and reopen the issue.

<img width="1056" alt="Screen Shot 2019-04-16 at 5 03 35 PM" src="https://user-images.githubusercontent.com/348368/56243978-d00f3180-6069-11e9-9c6a-f9cd0c50235c.png">
