### ISSUE TITLE
edit_url for custom table

### ISSUE THREAD

**Issue by jamesmarquez** [TypeRocket/typerocket#139]
When working with custom table that has primary field other than "id" (ex. teamID), the route_id returns 0.

I think changing this line in `/vendor/typerocket/core/src/Elements/Tables.php`
`$edit_url = $page->getUrl(['route_id' => (int)$result->id]);`

into this works.
`$edit_url = $page->getUrl(['route_id' => (int)$result->{$columnId}]);`

I think this goes the same with `$show_url` and `$delete_url`

**Comment by kevindees** [comment]
@jamesmarquez 

Thanks for letting me know. This has been fixed in the latest version of TypeRocket 4.0 Beta.

Thanks,
Kevin
