### ISSUE TITLE
How can I get extra fields from a taxonomie created using typerocket

### ISSUE THREAD

**Issue by elfedali** [TypeRocket/typerocket#140]
Hello, 
I've create a taxonomie  using type rocket 'gamme' with an image 'illustration' & file 'catalogue', and I've create the controller and the model ,
I want to get the data ,from this taxonomie,  How to , 
sorry for my english

**Comment by kevindees** [comment]
Hey @elfedali 

Have you done this: 

https://typerocket.com/docs/v3/taxonomies/#section-forms-and-fields

Thanks,
Kevin
