### ISSUE TITLE
Use TypeRocket on a theme and a plugin at the same time?

### ISSUE THREAD

**Issue by futuredesigngroup** [TypeRocket/typerocket#141]
I created a plugin using TypeRocket then I also created a theme for another site. I wanted to test it out with both installed and it basically says I cannot redeclare functions. I understand why this is happening, but for future purposes, how can I avoid this? Is there a way to rename classes / functions to something more custom so that I can create and use multiple plugins and themes on the same site utilizing Type Rocket?

**Comment by futuredesigngroup** [comment]
Has anyone ever ran into this issue?

**Comment by kevindees** [comment]
Hey @futuredesigngroup 

I have not tried running multiple versions of TypeRocket on a single site in this way. What version of TypeRocket are you using? Also, what specific errors are you getting. Even if you have multiple install of TypeRocket on a single site it should not through errors for functions.

Thanks,
Kevin

**Comment by futuredesigngroup** [comment]
@kevindees 
I have 3.0.* in my composer file, I don't know the exact version.

Error Messages: 

Notice: Constant TR_PATH already defined in /typerocket/init.php on line 18
Notice: Constant TR_APP_NAMESPACE already defined in /typerocket/init.php on line 19
Notice: Constant TR_START already defined in /typerocket/init.php on line 37
Fatal error: Cannot declare class ThemeOptionsPlugin, because the name is already in use in /typerocket/plugins/theme-options/init.php

Basically, I use TypeRocket for all of my custom meta boxes and post types. This issue seems to be presented when I use TypeRocket on a custom plugin (it's own installation) and then I try to add a custom theme that is also using TypeRocket (it's own installation). I am worried about this happening if someone installs my plugin and they are using a theme or plugin created by someone else that uses TypeRocket.

I think the issue could be fixed if I could rename or create a custom class that is only referenced in the plugin and/or theme that would not conflict with other TypeRocket installations or any kind. I tried to modify the classes and constants, but it just creates more issues.

**Comment by futuredesigngroup** [comment]
Also, BTW, it is the same version for TypeRocket, it just seems like it does not want me to use TypeRocket for a theme and a plugin on the same site as it seems to look for the other installation and errors out. I hope this makes sense.

**Comment by kevindees** [comment]
Hey @futuredesigngroup 

I tend to use the `typerocket_loaded` hook for this kind of thing. https://typerocket.com/docs/v3/wordpress-hooks/#section-core-loaded

You will want to have TypeRocket install on one or the other; or, have a plugin just for loading TypeRocket. When you load TypeRocket wrap it in a conditional.

```php
<?php
if( !defined('TR_START') ) {
   // Load Typerocket
}

add_action( 'typerocket_loaded', function() {
    // do TypeRocket stuff
});

```

**Comment by futuredesigngroup** [comment]
@kevindees What if it is something I cannot prevent? For example, someone uses my plugin on their server that is also running a theme built using TypeRocket that I did not create.  In that instance, I cannot look for it in a theme because it may not be there but if it is, it will cause my plugin to break the site.

Is it possible to only use the code in my plugin outside of other potential plugins and themes that may be using it? I had this issue previously with CMB2 and I was hoping to avoid it with TypeRocket. Is it possible to just rename the classes to something unique so it does not look at other code?

**Comment by futuredesigngroup** [comment]
@kevindees  Following up on this. I have tried to no avail to get it to work. Do you have any other suggestions to prevent another plugin or theme that uses Typerocket from using the same constants? I am at my wit's end trying to figure it out. I have tried to set it up so it uses a different plugin for typerocket, but my issue still stands if a plugin I did not develop uses typerocket, it prevents the plugin from installing since it is calling the same classes and constants.

Any help?
