### ISSUE TITLE
Does routes work only when i root install typerocket?

### ISSUE THREAD

**Issue by developerpaddy** [TypeRocket/typerocket#142]
I was working on typerocket since last couple of months, I loved this framwork. But I am stuck in using typeroket's routes feature. My query is,

Does typerocket route feature works only when I root install it?
if not, why does it not work when i install it in plugin or theme?

I have went through all procedure like,
1. adding roots in route.php file.
2. adding source in kernel, and changes required for public urls.
3. creating controllers and modules using galaxy CLI.

Please resolve my problem,
Thanks in advance.

**Comment by kevindees** [comment]
Hey @developerpaddy 

Can you post your code here? I'll need that to help debug your problem.

Thanks,
Kevin

**Comment by developerpaddy** [comment]
`tr_route()->get('/paddy/', function() {
    return 'Hi Member 1!';
});`

Inserting this code, and visiting localhost/projectfolder/paddy/ doesn't give me Hi Member1! output in displayed page.

**Comment by kevindees** [comment]
Hey @developerpaddy 

Are you using [v4-beta of TypeRocket](https://github.com/TypeRocket/typerocket/releases/tag/v4.0.0-beta1)? If so the api for routes has changed to:

```php
// your code
tr_route()->get()->match('paddy')->do(function() {
    return 'Hi Member 1!';
});

// with vars
tr_route()->get()->match('post/(.*)/edit', ['id'])->do(function($id) {
    return $id;
});

// also new features
tr_route()->middleware([App\Http\Middleware\VerifyNonce::class])
        ->get()
        ->match('post/(.*)/edit', ['id'])
        ->do('index@Post');
```

Thanks,
Kevin

**Comment by mithuTS** [comment]
Hi I am using v3 , and having problem with route.

I have added this way in routes.php

tr_route()->get('/qqq/', function () {
        return 'hello world';
    });

and visited both {site}/qqq and {site}/wp-admin/qqq and the 404 page appears. I am using typerocket inside plugin and included init.php.

**Comment by kevindees** [comment]
@mithuTS 

Are you using friendly URLs and have you flushed the permalinks?
