### ISSUE TITLE
how to output code errors?

### ISSUE THREAD

**Issue by kutoman** [TypeRocket/typerocket#145]
sorry, I'm relativley new in php programming.
I try to figure out how to print out the errors I make in my typerocket based code.
I've already configured php.ini (thus errors are printed out when I run error containing php code on my apache server in general but not in typerocket scope)

**Comment by kevindees** [comment]
@kutoman 

This is actually a WordPress issue. In your wp-config.php file be sure WP_DEBUG is set to true.

https://codex.wordpress.org/WP_DEBUG

Thanks,
Kevin
