### ISSUE TITLE
How to display tabs inside a post type edit screen?

### ISSUE THREAD

**Issue by fabioneves** [TypeRocket/typerocket#146]
Hello,
Great framework! I want to add tabs to organize a custom post type edit screen, is this possible? I couldn't figure it out from the documentation.
Thanks!

**Comment by kevindees** [comment]
Hey @fabioneves 

See these two sections:

https://typerocket.com/docs/v3/post-types/#section-forms-and-fields
https://typerocket.com/docs/v3/tabs/#section-tab-callback-v3-0-24

```php
$book = tr_post_type('Book');
$book->setTitleForm(function() {

$about = function() use ($form) {
    echo $form->text('Company Name');
    echo $form->text('Company Email');
    echo $form->text('Company Phone');
    echo $form->search('Terms Page')->setPostType('page');
    echo $form->checkbox('Company Open')->setText('Company open for business')->setLabel(false);
};

tr_tabs()->addTab( 'About', $about )->render();

});
```
