### ISSUE TITLE
understanding rooting

### ISSUE THREAD

**Issue by kutoman** [TypeRocket/typerocket#147]
I'm using typerocket as the root of the project. There are a couple things I'm trying to accomplish but couldn't figure out how to do.

~~1- How can I still use my active WP theme instead of the typerocket template?~~
2- How can I block predifined routes llike` /wp-admin/`? This was the main reason why I've decided to use rooting (I guess rooting is required for theses cases).

**Comment by kutoman** [comment]
Edit: 
solution for **1**: `'templates' => false` in app.php

**Comment by kevindees** [comment]
Hey @kutoman 

Unfortunately rooting does not block access to /wp-admin. However, WordPress core is secure and there is not much to worry about there. The main point of rooting is to keep all of your custom PHP outside of public view.

If you want to block wp-admin you will need to do so using nginx or apache access rules.

Thanks,
Kevin

**Comment by kutoman** [comment]
ok thanks. Just one question remaining, I'm aware of the way it's done in wordpress itself but how can you disable the wordpress backend (dashboard) and also hide the admin bar for subscribers in typerocket?

**Comment by kevindees** [comment]
hey @kutoman 

TypeRocket does not have an API for this and I'm not sure where to point you in the WordPress docs to help you make that happen. Let me know if you find anything on the topic.

Thanks,
Kevin

**Comment by kutoman** [comment]
here is a tutorial concerning this: [link](https://www.stewright.me/2016/03/disable-wordpress-dashboard-subscribers/). I'm going to try this approach
