### ISSUE TITLE
Question About $validator->flashErrors

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#149]
Forgive me if I'm missing something really basic - I'm working my way through a project as a novice.

I'm using your built-in form validation options to validate form input on a custom resource view. It works great, but I'm not sure if it's possible to get a friendly field name in the flashErrors function. Right now it just gives the form field name (like "rngstart" instead of "Range Start") which makes sense, because that's all it's being fed. Is there a way to inject a more user-friendly field title into those error messages?

Example image attached.

![image](https://user-images.githubusercontent.com/45110062/48649582-1419df80-e9c1-11e8-8f73-303ee8ab3888.png)

Thanks!

**Comment by kevindees** [comment]
Hey @eric-michel 

There is no feature for this right now but I'll see about adding it in.

Thanks,
Kevin

**Comment by eric-michel** [comment]
@kevindees thanks!

**Comment by kevindees** [comment]
Done

https://github.com/TypeRocket/core/releases/tag/v4.0.1

**Comment by eric-michel** [comment]
@kevindees this is excellent!
