### ISSUE TITLE
Polylang  plugin

### ISSUE THREAD

**Issue by elfedali** [TypeRocket/typerocket#150]
Hello, thank you for this amazing framework that enhances the development experience in WordPress,
I am using a plolylang plugin for multilingual site, 
I have a block in the page builder that accept [select, text, image] the select field is select option of pages that already exist on the site (when I switch lang to provide data for FR I lost En data ) so It's like I have two related pages (EN/FR) when I set Fr data I lost En data, and when i set En data I lost FR data

**Comment by elfedali** [comment]
Any body help, No multilingual support, I mean Polylang, thank you

**Comment by kevindees** [comment]
Hey @elfedali 

I know I posted an answer to you here as well. https://github.com/TypeRocket/typerocket/issues/152

I know a few people have used translation systems with TypeRocket before but I do not know which ones they have used or how they used them. You may need to prefix your field names based on the language being used so they are not replaced.

For example:

```php
$lang = 'FR'; // value of language
echo $form->text($lang . ' Name');
```

I'm not sure how you would get the language variable to be dynamic. I'm guessing that would be based on how the plugin works.

Thanks,
Kevin
