### ISSUE TITLE
The Page builder does not supper qTranslate X 

### ISSUE THREAD

**Issue by elfedali** [TypeRocket/typerocket#152]
Hello, I am trying to use this framework for a multilingual website, qTranslate not working,
the same data in the page in fr/eng

**Comment by kevindees** [comment]
Hey @elfedali 

TypeRocket stores custom field data for post types by default in the wp_postmeta table following WP best practices. This is likely a qTranslate issue and its compatibility with post meta fields.

Thanks,
Kevin
