### ISSUE TITLE
Working with custom tables in custom post types

### ISSUE THREAD

**Issue by nebulousGirl** [TypeRocket/typerocket#154]
I have a project that have pretty advanced search options. I was building using Carbon Fields and the meta table, but when I starting reflecting on how to do the search and the sorting I hit a wall. I would need to join the meta table multiple times just to setup the correct order. In looking for another solution, I found TypeRocket which seems awesome. I have already converted my post types and taxonomies and will be doing the same for the meta boxes.

I only have one problem. I need to save custom fields in a custom table which is related to the post. Is there a way to do this currently with TypeRocket, or do I have to tap into Wordpress filters to get this done?

**Comment by nebulousGirl** [comment]
With what I have seen from the documentation, I would need to define a model for the post type with restricted fillables to prevent data from being saved as post meta. Then, creating another model which would be populated on the `save_post` hook.

**Comment by kevindees** [comment]
Hey @nebulousGirl 

You can do this with TypeRocket. You just need to [override or extend the default methods](https://github.com/TypeRocket/core/blob/master/src/Controllers/WPPostController.php) (create and update) for your specific post type controller. Maybe try unsetting the field you do not want saved as meta data as desired restricting fillable is a way to do this.

https://typerocket.com/docs/v3/controllers/#section-post-controller

Then use Models to work with you custom tables and save data to them.

https://typerocket.com/docs/v3/models/

Finally you just need to add a new `Form` object that is connected to the custom tables model. You can use some of this documentation as guidance.

https://typerocket.com/docs/v3/custom-resources/

Thanks,
Kevin

**Comment by nebulousGirl** [comment]
Thanks for the quick reply. 

I don't understand how I could use a `Form` object for a custom table model in a custom post type page.

**Comment by kevindees** [comment]
This is not comprehensive but I hope it can spark the idea I'm trying to communicate. Note, that I have added a method update in TypeRocket v4 with core v4-beta13 to make this easier as seen in the example below. If you are using v3 you might need to go about this in another way but the same idea applies.

https://github.com/TypeRocket/core/releases/tag/v4.0.0-beta13

```sql
CREATE TABLE `wp_custom` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `post_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

```
php galaxy make:model -c base Custom
```

```php
global $post_id; // not sure this is right just working off memory
$pt_form = tr_form();
echo $pt_form->text('My Meta Field');

// This allows you to inject the custom model so your custom fields populate 
// when you edit the page. No checks have been added to see if the model
// exists. It might even be a good idea to create the table when the post
// is created by coding that logic into the post type controller.

$custom = (new \App\Models\Custom)->where('post_id', $post_id)->first();
$custom_form = tr_form('custom')->setModel($custom);
echo $custom_form->text('Name');
```
