### ISSUE TITLE
Returning repeater fields from custom resource as array or object instead of raw string

### ISSUE THREAD

**Issue by galingong** [TypeRocket/typerocket#156]
Hi! I have a custom resource that my users create and delete from the frontend, which I also access from the admin. It has a repeater field, displays correctly as a form in the admin (`$form->repeater('Repeater')->setFields([...]);` etc.), while if I want to display it on the frontend then `$queryResult->repeater` returns the unformatted raw string. Of course I could go regex, but is there a simpler way to return it in a usable format?

**Comment by galingong** [comment]
Ok, I've got it - it's `tr_resource_field()` or in my case calling `getFieldValue()` on the result also did it since the database was already queried. These are not documented at all though, I've managed to find them in `helpers.php`. Dev can close the issue, I leave it open to make sure it's read :)

**Comment by zoephilipps** [comment]
@galingong Another solve for this is to cast your repeater as an array. https://typerocket.com/docs/v3/models/#section-cast

**Comment by galingong** [comment]
Thank you for the input, I had no idea that existed. By the way is this format (in which repeater, matrix and builder fields are saved to the database) standard? I've seen ACF also uses this method, but haven't heard of it elsewhere.

**Comment by zoephilipps** [comment]
Yea it's a serialized array and I think is fairly standard in WordPress world. It requires unserializing to manipulate so it's not as portable as other ways of storing data, but it does reduce rows in your tables.
