### ISSUE TITLE
Queries fail silently

### ISSUE THREAD

**Issue by nebulousGirl** [TypeRocket/typerocket#158]
I think displaying query errors should be enabled in debug mode by default by TypeRocket: `$wpdb->show_errors(); `

**Comment by nebulousGirl** [comment]
Nevermind the previous comment. Wordpress enables this if `WP_DEBUG` is `true`. 
The problem is that the error is not shown (because of the redirection on saving) and there is no indication that a query failed except if you look into the log file. 

Wordpress only has a constant to die on queries for multisites. It would be awesome to have a feature like this in TypeRocket.

**Comment by kevindees** [comment]
Hey @nebulousGirl 

I'm going to table this request for now. I'd need to take a closer look into errors for TypeRocket, in general, to create a common interface. Maybe in v4.1 or v5 ;)
