### ISSUE TITLE
TypeRocket causes error when using wp_insert_user function in a non-logged in state

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#16]
Hi Kevin!

Very happy to use the newest version 👍 . I found something weird. When using `wp_insert_user` on a not-logged in state, i get one of these:
1. _500 Internal Server Error_ with message **No Message Set**
2. _401 Unathorized_ with message same as above

I was confused about what causes the error. Trying to switch theme to default, de-activate plugin/ components. Then i know, it's caused by TypeRocket. Please don't get me wrong, i love this plugin.

I installed TypeRocket on _mu-plugins_ directory. Then move it into _theme_ directory, and error is still happened. I'm still confused about this. What script should be adjusted in TypeRocket?

Thank you very much & regards,
Bagus

**Comment by ghost** [comment]
Update:
A friend told us to check the use of `user_register` action hook. Then  we look into **typerocket\vendor\typerocket\core\src\Core\Launcher.php** and commenting line **154** : `add_action( 'user_register', 'TypeRocket\Http\Responders\Hook::users' );` and finally `wp_insert_user` works!

Currently, we just commenting this line for the temporary solution. I think it would be very nice if this can be handled better.

Thank you @kevindees ;)
Great plugin!

**Comment by kevindees** [comment]
Hey bersujamu,

This error is due to how TypeRocket middleware works and how it is very aggressive with security. I'll see about adding a patch today to address your scenario.

If you find any more bugs please feel free to connect with me. I'd love the feedback.

Thanks,
Kevin

**Comment by kevindees** [comment]
Hey @bersujamu,

There is a core patch now that should fix your issue. Once you update the core, with `composer update`, then change your Kernel under `app/Http/Kernel.php` and remove the auth read middleware under the hook global group.

``` php
...
    protected $middleware = [
        'hookGlobal' =>
            [ AuthRead::class ], // remove this setting
...
```

Should end up as,

``` php
...
    protected $middleware = [
        'hookGlobal' => [],
...
```

Let me know if that does the trick.

Thanks,
Kevin

**Comment by ghost** [comment]
Hi Kevin,
Thanks for the fix! Yes, it does the trick ^^

Thank you again,
Bagus
