### ISSUE TITLE
save_post hook executed twice

### ISSUE THREAD

**Issue by clemorphy** [TypeRocket/typerocket#160]
Hi 

I added a function on the `save_post` hook, and for a particular CPT (created with TypeRocket) the function is called twice.
On the first call, it seems that some fields are saved, and in the second call, other fields are saved.

Is there any reason why TypeRocket would go twice through this hook when a CPT is saved ?

**Comment by clemorphy** [comment]
It actually happens when a CPT has custom fields.
The `save_post` hook is called one time to save native fields, and then a second time to save custom fields.
Maybe TypeRocket should have its own `save_post` hook (e.g. `tr_save_post`), that would be called once.

For now I have to check the wpnonce in order to execute my function only once, and I have to use `$_POST` data in order to get my submitted data. If I use the `$post` parameter to get the data, on the first call custom fields have old data, and on the second call native fields have old data.

**Comment by kevindees** [comment]
Hey @clemorphy 

This is happening because the `update` method calls the WP function `wp_update_post` and `wp_update_post` triggers the `save_post` hook again. I'm not sure there is much that can be done to prevent this from happening. This should only occur by built-in fields are used.
