### ISSUE TITLE
Wrong format for date field

### ISSUE THREAD

**Issue by nebulousGirl** [TypeRocket/typerocket#163]
I see an issue that found a workaround: https://github.com/TypeRocket/typerocket/issues/83

But, I think that the default should be the conventional database format "Y-m-d".

**Comment by zoephilipps** [comment]
@nebulousGirl Yet another workaround for now is to use `echo $form->text( 'Date' )->setType( 'date' )` rather than the jQuery Datepicker field. The HTML5 date input formats the value correctly.

**Comment by kevindees** [comment]
I have added a new feature for this. It will be coming in a new beta release:

```php
echo $form->date('Date')->setFormat('yy-mm-dd');
```

**Comment by eric-michel** [comment]
~~I just tested this out for the first time and it works great! I used `setFormat( 'yy-mm-dd' );`.~~

Scratch that; I was mistakenly testing on a post type, not a custom resource. I'm actually getting all of my fields using this method saved as 0000-00-00 in the database. Will switch back to Zack's method for now.

**Comment by manuman94** [comment]
Is this working already?

echo $form->date('Date')->setFormat('yy-mm-dd');

Greetings.

**Comment by eric-michel** [comment]
hey @manuman94, I believe this has been implemented, but these days I'm still just using Zack's workaround as I like using the HTML5 input fields when I can. So I am not actually using the new functionality if it has been implemented.
