### ISSUE TITLE
WHERE ... NOT IN query

### ISSUE THREAD

**Issue by matteo-greco** [TypeRocket/typerocket#164]
Hi! I'm trying to pull all Users that don't have a certain ID, using a Model like this:

```php
$users = ( new \App\Models\User() )
    ->where( 'ID', 'NOT IN', '(1,4,6)' )
    ->get();
```

But the resulting query has quotes around (1,4,6), causing a syntax error.

```sql
SELECT * FROM wp_users WHERE ID NOT IN '(1,4,6)'
```

I know this is not a documented feature, but is there any chance this can be supported? Or, is there a workaround to it?

Thanks

**Comment by kevindees** [comment]
Hey @matteo-greco 

Have you tried this:

```php
$users = ( new \App\Models\User() )
    ->where( 'ID', 'NOT IN', [1,4,6] )
    ->get();
```

**Comment by kevindees** [comment]
Updated docs for you

https://typerocket.com/docs/v3/query-builder/#section-where
