### ISSUE TITLE
post_content is required to create a post

### ISSUE THREAD

**Issue by nebulousGirl** [TypeRocket/typerocket#166]
In Wordpress, it is possible to create post types without an editor which means no post_content when creating a new post. 

TypeRocket triggers an error because it requires both post_title and post_content. I can understand for post_title, but post_content is a bit of a reach.

I have avoided the problem by feeding a space into the post_content for now.

**Comment by kevindees** [comment]
The requirement for post_content has been removed in the latest beta

https://github.com/TypeRocket/core/releases/tag/v4.0.0-beta16
