### ISSUE TITLE
Admin Table + tr_table_search_model action = wrong count

### ISSUE THREAD

**Issue by matteo-greco** [TypeRocket/typerocket#167]
Hello! Hello!
I am displaying an admin Table and I added a `<select>` to display an additional filter:

```php
$table->appendSearchFormFilters(
    function() {
        $html  = '<select name="sgruppo">';
        $html .= '<option value="">Pick a filter</option>';
        $html .= '<option value="option1">Option 1</option>';
        $html .= '<option value="option2">Option 2</option>';
        $html .= '</select>';
        echo $html;
    }
);
```

I added an action to the 'tr_table_search_model' hook that adds a where() condition to the Table's Model:
```php
public static function setSearchModel( \App\Models\Anagrafica $model ) {
    $gruppo = $_GET['sgruppo']; // validation and sanitizing omitted
    if ( '' !== $gruppo ) {
        $model->where( 'gruppo', $gruppo );
    }
}
```

It works, but the Table will display the wrong count, as the count is set when the model is, which happens before the 'tr_table_search_model' hook. I patched it by modifying Tables.php:231 

```php
public function render($action_key = '')
{
    // ...
    do_action('tr_table_search_model'.$action_key, $this->model);
    $this->count = $this->model->findAll()->count(); // <-- I ADDED THIS
    $results = $this->model->findAll()->take($this->limit, $this->offset)->get();
    // ...
```

Is there a better way? One that doesn't involve hacking the TypeRocket's core?
If not, would the developers consider adding this?

Cheers,
  MG

**Comment by nebulousGirl** [comment]
Personally, I would extend the Tables class.

**Comment by nebulousGirl** [comment]
You could possibly also use the hook inside the model's constructor: `do_action( 'tr_model', $this );`

**Comment by kevindees** [comment]
Hey @matteo-greco @nebulousGirl 

https://github.com/TypeRocket/core/releases/tag/v4.0.0-beta14
