### ISSUE TITLE
Can't use flash messages on users page

### ISSUE THREAD

**Issue by xiqui** [TypeRocket/typerocket#169]
I cant't display error messages in the edit user wordpress backend page.

I have custom fields in the edit user page that i need to validate, everything works fine, but when i try to display errors messages, the message 'User updated.' always show, even when i don't use the update method.

I need to show the errors messages but without 'User updated' message. how can i achieve that?

The image below show the problem.

![user error messages](https://user-images.githubusercontent.com/46166420/50452790-2aa64580-0934-11e9-904e-4e5cbc925d2a.png)

best regards.

**Comment by kevindees** [comment]
Hey @xiqui 

The user updated massage seems to be a core WordPress feature. You will likely need to locate a hook WP offers if there is one to ignore that message.

Thanks,
Kevin

**Comment by xiqui** [comment]
Hi Kevin,

Yes, the updated message is a WordPress feature. 

I already find the solution. The only way is to hide the message, the hook exist but the documentation is very poor.

I have to hide the message with CSS.

Another thing that I have been with trouble is the response class.

I can't use the response that came by user update hook, because Block Flash is true and I can't send flash messages to admin. I have to create another response object or add a method that change the Block flash to false.

Response Class only have a method to set BlockFlash to true, in the responder user hook the block flash is always set to true.

I add a new method to set it to false.

Can you add a new method to the framework or tell me how I can send flash messages on the User page.

Thank you for all the attention...

best regards,

**Comment by xiqui** [comment]
Hi Kevin,

Yes, the updated message is a WordPress feature.

I already find the solution. The only way is to hide the message, the hook exist but the documentation is very poor.

I have to hide the message with CSS.

Another thing that I have been with trouble is the response class.

I can't use the response that came by user update hook, because Block Flash is true and I can't send flash messages to admin. I have to create another response object or add a method that change the Block flash to false.

Response Class only have a method to set BlockFlash to true, in the responder user hook the block flash is always set to true.

I add a new method to set it to false.

Can you add a new method to the framework or tell me how I can send flash messages on the User page.

Thank you for all the attention...

best regards,

**Comment by kevindees** [comment]
@xiqui 

Have you tried `flashNext()`? Can you send a code example? If so I can reopen this one.

https://typerocket.com/docs/v4/responses/#section-flash-next
