### ISSUE TITLE
Typo in Docs -> HTML Generator

### ISSUE THREAD

**Issue by JulienMelissas** [TypeRocket/typerocket#17]
Shouldn't `a` output `href=""` instead of `src=""`? On this page: https://typerocket.com/docs/v3/html-generator/

<img width="653" alt="screenshot 2016-11-23 15 54 10" src="https://cloud.githubusercontent.com/assets/2278221/20578437/4e9c72b4-b195-11e6-816e-93bfbc762701.png">

**Comment by kevindees** [comment]
Hey Julien!

Good to hear from you again. We are all fixed now. Thanks for the correction.

Kevin
