### ISSUE TITLE
create user from front end

### ISSUE THREAD

**Issue by mannermax** [TypeRocket/typerocket#170]
I'm trying to create a new user from frontend using
$form_user = tr_form('user', 'create')->useJson();
echo $form_user->open();
echo $form_user->text('user_login');
echo $form_user->text('user_email');
echo $form_user->text('user_pass');
echo $form_user->text('role');
echo $form_user->text('mall_shop'); //user meta
echo $form_user->submit('Create');
echo $form_user->close();

everything works well, even user meta, except for the role
I get always the default role subscriber

do you have any advice
thanks in advance Max

**Comment by kevindees** [comment]
Hey @mannermax 

Setting roles for users is a bit complicated because of how WordPress does things. This might help: 

https://usersinsights.com/wordpress-custom-role/

Something like this might be needed:

```php
$user = new WP_User(123);
$user->set_role('editor');
```

Thanks,
Kevin
