### ISSUE TITLE
Adding Routes Outside of routes.php

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#172]
I'm working on developing a series of theme and plugin assets for re-use among different customers in the same industry. TypeRocket will be installed in the theme backbone, and we'll create a child theme for each customer for design customization.

Not every customer will use every plugin, so I'm trying to compartmentalize all TypeRocket resources that are only needed for a given plugin, to that plugin's directory. I've made great progress, but am stuck at routes.

Right now, custom routes are loaded in vendor/typerocket/core/src/Core/Launcher.php starting on line 48. It loads those routes exclusively from the routes.php file within the theme. Because that happens during initCore, there isn't really any way to extend that so I can register routes from my plugin rather than routes.php in the theme.

For right now, what I'm doing is just adding a WordPress hook that I can grab right before it loads the router so I can add routes from anywhere. But that means I'm modifying a core file of TypeRocket, which isn't my preference. This is probably also not the best or most secure way to do what I'm trying to accomplish.

Here's the new code:

        /*
        |--------------------------------------------------------------------------
        | Router
        |--------------------------------------------------------------------------
        |
        | Load TypeRocket Router
        |
        */
        /* BEGIN EXTENSION */
	        do_action( 'additional_routes' );
        /* END EXTENSION */
        $paths = Config::getPaths();
        $routeFile = $paths['base'] . '/routes.php';
        if( file_exists($routeFile) ) {
            /** @noinspection PhpIncludeInspection */
            require( $routeFile );
        }
	    (new Routes())->detectRoute()->initHooks();

        $this->initEndpoints();

Only the "do_action('additional_routes');" is new. With that, I can add routes from my plugins.

For anyone else wanting to separate functionality like I'm doing, you can easily separate your Models and Controllers into a separate plugin by using the Composer autoloader to add to the TypeRocket App namespace.

All you have to do is, in your main plugin file in the root plugin directory, add the following code within the 'typerocket_loaded' action:

	$autoloader = require TR_PATH.'/vendor/autoload.php';
	$autoloader->addPsr4('App\\', __DIR__.'/app');

Then add an "app" directory in your root plugin directory and use the same structure as exists in typerocket/app (e.g. app/Controllers, app/Models, etc.). These will immediately work if you mark them with the same namespace at the top of each class file (App\Controllers, App\Models, etc). Essentially, you're telling PHP that it can find classes from the App namespace in both the original location (typerocket/app) _and_ your new location.

For views, you simply have to abandon the handy dot format that you can normally use in the first argument of the tr_view helper function and instead point it directly to the file path of your view file. Fortunately the View constructor will detect that it's a full path pointing to a valid file and use it gracefully.

**Comment by nebulousGirl** [comment]
@eric-michel I'm actually doing something similar to you. I also added a hook in the launcher, but found it also necessary to move this code into a "plugins_loaded" action, probably because I'm using it as an mu-plugin instead of inside a theme.

I am detailing my edit to the core in this issue: https://github.com/TypeRocket/core/issues/21

**Comment by kevindees** [comment]
@eric-michel @nebulousGirl 

https://typerocket.com/docs/v4/routes/#section-route-hooks
