### ISSUE TITLE
Routes using an anonymous function for the route handler return 404 to AJAX calls

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#174]
This one's got me stumped.

When I use tr_route to create a custom URL and define the handler via an anonymous function, AJAX get requests to that URL return 404, but the page resolves just fine in a browser. I've quintuple checked that I'm always at the correct URL in both cases, and I've tried multiple different scenarios.

If, instead, I point the handler to a controller using the method@Controller syntax and put the exact same return in that method, the URL resolves to the AJAX get request.

You can try it with the most simple example:

    tr_route()->get( '/test/', function(){
	    return 'test';
    });

If you visit /test/ in your browser, it will resolve. But if you try to perform an AJAX get request to the exact same URL, you'll get a 404. I've tried using relative reference, hard coding the full URL, etc. This happens in both Chrome and Firefox.

If you refactor it to look like this, though, it'll work just fine:

    tr_route()->get( '/test/', 'testMethod@SomeController' );

and then in the SomeController class:

    class SomeController extends Controller {
        public function testMethod() {
            return 'test';
        }
    }

This resolves for both AJAX and browser requests.

Ultimately I just used a controller for what I'm working on (which is probably the better way to do it anyway) but figured I'd point this out in case this could cause other problems.

**Comment by brettvan** [comment]
I think you might have something else going on with your installation.  I tested this and it appeared to function properly.

```
tr_route()->get('/hammertime/', function() {
    return 'Funky Cold Medina.';
});
```

and

```
<button id="buttonthing">this is a thing</button>
<div id="divthing">This is div thang</div>
<script>
$(document).ready(function(){
  $("#buttonthing").click(function(){
      $.ajax({url: "http://my.site.com/hammertime/", success: function(result){
        $("#divthing").html(result);
    }});
  });
});
</script>
```

![image](https://user-images.githubusercontent.com/30217286/50936668-9e6d4580-143e-11e9-88f2-bf1f42f421a4.jpeg)

**Comment by eric-michel** [comment]
@brettvan hm... I'm sure you're right. I'm afraid it's time to blow up my dev environment and start from scratch.

Thanks for checking it for me!
