### ISSUE TITLE
Typerocket + Sage

### ISSUE THREAD

**Issue by jerrebm** [TypeRocket/typerocket#175]
Hi! 

I'm using Trellis + Bedrock + Sage theme from roots.io, but I love the idea of TypeRocket's pagebuilder and Laravel-like Models, Forms, etc.

I'd like to have that functionality in Sage, but it already has a similar directory structure and asset handling.

Is there an efficient way to combine the two?

**Comment by jerrebm** [comment]
Nevermind, just went with rooted typerocket instead.

**Comment by besrabasant** [comment]
hey, @egyptik are you using rooted **Typerocket** with Bedrock setup or the conventional **WP** setup?
