### ISSUE TITLE
Need WPPostController to spoof a destroy method on delete_post

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#177]
TR does a great job spoofing a create and update method in WPPostController that we can use/override when the save_post action is called. It would be great to also have a destroy method that runs when the delete_post action is called so we can, for instance, delete related records in another table.

Right now I'm using CASCADE DELETE in my database (thanks @nebulousGirl!) to do this, but would prefer to have the option to do so in the framework, especially because dbDelta doesn't handle foreign keys when setting up your tables on plugin install.

**Comment by kevindees** [comment]
Hey @eric-michel 

I feel like this kind of functionality should be at the model level. If you do this through the controller you can not be sure it will work. However, I can see this being helpful for other tasks that need to be run on delete. I'll need to think about this request more. Also, thanks for the PR on this one so I can see what you are thinking.
