### ISSUE TITLE
Slack Channel

### ISSUE THREAD

**Issue by kevindees** [TypeRocket/typerocket#178]
Hey @zackphilipps @eric-michel @nebulousGirl

I have started a slack channel for TypeRocket if you are interested. I can not say if I will keep the Slack or be able to manage it effectively but I thought it might be worth adding to try and help better collaboration on all things TypeRocket.

https://join.slack.com/t/typerocketchat/shared_invite/enQtNTMwOTg1OTQwNTc5LWMzMmExZTE2ZGExYWM2ZDAwZDEwYjcyYTliNjM5MGFhZDMzZDQyMzAzNTUwOGFkOTQ4NTA3M2ZmZDA5Y2NiZGU

Thanks,
Kevin

**Comment by brettvan** [comment]
Mind if I join this channel?

**Comment by jerrebm** [comment]
Can't use the link.. `This invite link is no longer active.`

**Comment by kevindees** [comment]
@brettvan @egyptik 

https://join.slack.com/t/typerocketchat/shared_invite/enQtNTMwOTg1OTQwNTc5LWMzMmExZTE2ZGExYWM2ZDAwZDEwYjcyYTliNjM5MGFhZDMzZDQyMzAzNTUwOGFkOTQ4NTA3M2ZmZDA5Y2NiZGU
