### ISSUE TITLE
Error when adding comment on a post

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#18]
Hi Kevin,

When i added comment on a post, the page became blank because of fatal error (although the comment was succesfuly inserted to db). This also happened on fresh WordPress installation with TypeRocket installed inside theme:
`Fatal error: Cannot access empty property in /nas/content/live/questarcadis/wp-content/mu-plugins/internal/libraries/typerocket/vendor/typerocket/core/src/Controllers/WPCommentController.php on line 21`

But, because my TypeRocket installation is on mu-plugins, it also produces additional notice
`Notice: Undefined variable: modelClass in /nas/content/live/questarcadis/wp-content/mu-plugins/internal/libraries/typerocket/vendor/typerocket/core/src/Controllers/WPCommentController.php on line 21
`

Hmm I have no idea to fix this now. I think we need a patch.

Thank you Kevin,
Bagus

**Comment by kevindees** [comment]
Hi Bagus,

This bug should be fixed now in core version v3.0.9. Let me know if it is working for you. `composer update`.

Thanks,
Kevin

**Comment by ghost** [comment]
Yes, it fixes the bug!

Thanks Kevin,
Bagus
