### ISSUE TITLE
Replacing Post Title as Primary Column in Index

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#180]
I've created a custom post type called "Purchase Orders". I don't plan on actually using the post title for anything, as the ID of the post itself will serve as the purchase order number (easy to grab, always unique). Then I'll have various custom meta fields to fill out some additional data.

I've used `remove_post_type_support` and `removeColumn` to remove the title form field (in the post edit page) and the title column (on the index page) respectively.

However, once I remove the title column on the index page, I can't assign a new column to act as the "primary" column that has all the links to do stuff ("Edit | Quick Edit | Trash | View").

For custom resources, this is made super easy with the excellent and flexible `setColumns` method under the `Tables` class, which allows you to both select any column to act as the main control column (or even multiple columns, if you wanted), *and* select which controls appear.

Is there an equivalent function that I'm missing to do the same for custom post types? Right now my workaround will probably be to simply save the post ID into the title field every time the post is saved.

**Comment by kevindees** [comment]
Hey @eric-michel 

This is a good question. TypeRocket does not have a feature for this and I'm not sure if WordPress does either. I have not tried doing this before.

Maybe @zackphilipps has done this before.

Thanks,
Kevin

**Comment by zoephilipps** [comment]
I have not done that before, but looks like this answer has some stuff that may work? https://wordpress.stackexchange.com/a/152978

**Comment by eric-michel** [comment]
Thanks! I'm going to spend some time on this and decide if I want to see if I can create an elegant solution that might turn into a PR, or take the path of least resistance and just save the post ID into the post_title on save.

**Comment by eric-michel** [comment]
I got it! It's list_table_primary_column. I'll add a property and method to the PostType class and add the hook to the registery in `setPostTypeColumns` and put through a PR
