### ISSUE TITLE
Get "null" from custom taxonomy's fields with taxonomies in URL

### ISSUE THREAD

**Issue by klocus** [TypeRocket/typerocket#183]
Hi,

I'm using taxonomies in URL to get specific posts.

```
http://wordpress.test/?post_type=custom&taxonomy1=foo&taxonomy2=bar
```

In posts I use `tr_components_field` to get Matrix fields of my custom taxonomies. 

```php
tr_components_field('matrix_fields', $id, \App\Models\Term::class);
```

It works only when I don't use any other taxonomies in URL then `$id's` taxonomy. Otherwise, it is returned `null`. I found that there is problem with ID on `getFieldValue` method:

```
        if ($this->getID() == null && ! $this->old && empty($this->dataOverride) ) {
            return null;
        }
```

https://github.com/TypeRocket/core/blob/83d5a28da580c124dcf298f4315492f1a9b06ad7/src/Models/Model.php#L536

I really do not know what the problem is and how to solve it. Could it have anything to do with using the same controller and model for all taxonomies? (https://github.com/TypeRocket/typerocket/issues/176)

**Comment by kevindees** [comment]
@klocus 

I've made a number of updates to the WPTerm class. Some of those upgrades might help you.

https://github.com/TypeRocket/core/releases/tag/v4.0.4
