### ISSUE TITLE
Query Builder - can you concatenate two fields for the where method?

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#184]
I'm pretty sure the answer to this is "no", but I'm wondering if you can do something equivalent to this using the query builder:

`SELECT * FROM People WHERE CONCAT(firstname, ' ', lastname) like '%john doe%';`

**Comment by kevindees** [comment]
@eric-michel 

In version 4.0 there is an `appendRawWhere()` method that might work.
