### ISSUE TITLE
Year range in Date Fields

### ISSUE THREAD

**Issue by developerpaddy** [TypeRocket/typerocket#185]
Hello Folks,

I want to add date field with year range like starts with 18 years before until 50 years back like as on current 2019 year the range will be 2001:1969

How can do it with typerocket date field

**Comment by kevindees** [comment]
Hey @developerpaddy 

I'm not sure what you are asking for here. Can you be a bit more descriptive? TypeRocket does not provide a date-range field in the core at the moment.
