### ISSUE TITLE
Model::count() returns incorrect result due to limit in Tables::render()

### ISSUE THREAD

**Issue by bucur-marian** [TypeRocket/typerocket#186]
The `Model::count()` call returns an incorrect result in `Tables::render()`, because of the previously set limit by `Model::take()`, on pages greater than 1.

See:
```PHP
$results = $this->results = $this->model->findAll()->useResultsClass()->take($this->limit, $this->offset)->get();
$count = $this->count = $this->model->count();
```

Tested with Typerocket `v4.0.0-beta26`.

**Comment by kevindees** [comment]
@mbucurcf 

This is now fixed along with a few other fixes.

https://github.com/TypeRocket/core/releases/tag/v4.0.2
