### ISSUE TITLE
Custom fields for custom taxonomy not working

### ISSUE THREAD

**Issue by twosg** [TypeRocket/typerocket#188]
Hi,

the same problem as here: https://github.com/TypeRocket/typerocket/issues/78

I just found out that this is not only for image fields. It is for all fields. I debugged  `WPTerm::update()` and found out that the ID is not set, so it can't update the record. The passed $fields array does NOT include the core/builtin fields, but DOES include the custom fields. However without ID...

It seems to always use TypeRocket\Models\WPTerm which has `$taxonomy = 'category';`, but my taxonomy is called `manufacturer`.

Related question 1: How can I pass a custom model to `tr_taxonomy()` ? My custom model would extend `TypeRocket\Models\WPTerm`

Related question 2: `$this->errors = ['No item to update'];` I guess that should be flashed after updating/saving when the ID cant be found, but it is not visible anywhere.

_Originally posted by @twosg in https://github.com/TypeRocket/typerocket/issues/78#issuecomment-470088267_

Edit: updated class names and details

**Comment by twosg** [comment]
The taxonomy is created by:

```
tr_taxonomy(__('Manufacturer'), __('Manufacturers'))
				->addPostType('my_post_type')
				->setId('my_taxonomy')
				->setArgument('rewrite', [
					'slug' => 'my-post-type/manufacturer',
					'with_front' => false
				])
				->setArgument('show_admin_column', true)
				->setMainForm( function() {
					$form = tr_form();
					echo $form->image('logo')
					          ->setLabel('Logo');
					echo $form->text('test');
				});
```

The Post Type and Taxonomy is visible in admin, as well as the custom fields.

**Comment by Slayvin** [comment]
Same issue here. Custom fields are visible, but creation/edition not saving meta

**Comment by kevindees** [comment]
@twosg @Slayvin 

Did you make a Taxonomy controller?

https://typerocket.com/docs/v4/taxonomies/#section-forms-and-fields

```
php galaxy make:model -c term Manufacturer
```
