### ISSUE TITLE
No support for multilingual website

### ISSUE THREAD

**Issue by elfedali** [TypeRocket/typerocket#189]
This is not working will workin with any multilingue plugin,
https://wordpress.org/plugins/polylang/
When I create a page with the builder in (fr) & (eng), I find the some text in the page (fr) & (eng)
is there any hook or a way to do this, Thanks

**Comment by galingong** [comment]
In my opinion this is not related to TypeRocket, but the way you query your database/pass data to the view. 
The way I do it is like this - there is a Polylang function `pll_get_post()` which returns an ID for translated post. It takes two arguments, the first is a post ID (no matter what language), the second is a language slug, so you can do `$translatedId = pll_get_post($id, pll_current_language())`.
I use Timber, so from this point for me it's just passing the ID to the .twig file e.g. `$post = new TimberPost($translatedId)`, then in the .twig `post.builder` will always parse the correct translations.
I highly recommend using a templating language (like Twig or it's WP plugin Timber), but you can also query your translated post with TypeRocket models or even the default WP query.
