### ISSUE TITLE
Typo in TypeRocket\Elements\Fields\Matrix.php

### ISSUE THREAD

**Issue by galingong** [TypeRocket/typerocket#190]
PHP throws an undefined index (['contact']) error when using matrix fields. The problem is a typo on **line 303** in **TypeRocket\Elements\Fields\Matrix.php**, it's `<?php if(!$this->hide['contact']) : ?>`, when it should be `<?php if(!$this->hide['contract']) : ?>`.

**Comment by kevindees** [comment]
@galingong 

Thanks for this. I have updated the code base and it will go live in v4 on the next release.
