### ISSUE TITLE
composer static autoloader not working in child theme

### ISSUE THREAD

**Issue by Slayvin** [TypeRocket/typerocket#191]
Hello!
I've been using typerocket for a few weeks now, and I really enjoy it!
I started with a root project and had no issue.
But then I used typerocket in an existing child theme, and I got an error message:

> **Fatal error**: Uncaught Error: Class 'TypeRocket\Core\Config' not found in _{{my project path}}_\www\wp-content\themes\my-child-theme\typerocket\init.php:38

I discovered that the static loader is not working as expected. If I disable it, then its working fine, classes are loaded correctly.
I know you are not responsible of the files composer auto-generate, but maybe you could help me on this.
Is there something I have to add in composer.json to make it work?
I see there is an 'autoload' part in there.  

Thanks

**Comment by kevindees** [comment]
Hey @Slayvin 

Who are you hosting with? I know WP Engine has some issues with composer.

Thanks,
Kevin

**Comment by Slayvin** [comment]
I'm using Apache/php7 on a local server running on my desktop pc. As I said, I have no issue with a 'rooted' typerocket install. I only saw this problem when installing typerocket in a child theme.

**Comment by kevindees** [comment]
@Slayvin 

Did you ever find a solution to this? Did you run composer install?

Thanks,
Kevin
