### ISSUE TITLE
Typerocket Licensing

### ISSUE THREAD

**Issue by armgeek007** [TypeRocket/typerocket#192]
I found Typerocket really useful. I was planning to create a few commercial open-source plugins based on Typerocket and sell them as premium offerings, when I saw GPL3 Licensing on Typerocket. I wanted to know if Typerocket offers a commercial licensing option or if I am permitted to create commercial open-source plugins using Typerocket GPL3 license. Any insights on the matter would be very helpful. 

Pardon my ignorance of Open Source Licenses.

**Comment by kevindees** [comment]
@armgeek007 

Yes. GPL allows you to do what you are asking. You just need to know more about the GPL lic.

https://www.gnu.org/licenses/gpl-3.0.en.html
