### ISSUE TITLE
Another prefix for database and  display errors front-end

### ISSUE THREAD

**Issue by DreamiLy817** [TypeRocket/typerocket#194]
Hello!

It's possible to use another prefix than Wordpress $ wpdb-> prefix = wp_ ?
For example, have a prefixed tables with "mf_" and orignal prefixed tables of wordpress with "wp_".

And how can we display the errors of the fomulaires of the front-end side ?

Thanks!

**Comment by kevindees** [comment]
Hey @LeslieBlt 

TypeRocket only uses the WP standard way of working with tables so you are stuck with the `wp_` prefix.

If you need to work with unprefixed tables considering adding a more robust ORM to your project via composer. The TypeRocket ORM is designed to work well with WP; for example, the TR ORM will trigger many of the WP hooks the WP_Query system would. We do all this to help with third-party plugin compatibility.

Thanks,
Kevin
