### ISSUE TITLE
Model findById method for a non existing ID (since Beta 6)

### ISSUE THREAD

**Issue by xanatoses** [TypeRocket/typerocket#195]
Hi! An example, 5 is a missed register:
`$chart= new \App\Models\Chart;`
`$chart->findById(5);`
`if(!$chart):`
    `echo "the chart no longer exists"; //it works perfectly in Beta 5`
`endif;`
With TypeRocket 4 Beta 6 release, this condition is not respected.

Thanks and good job with TypeRocket, is just amazing!

**Comment by kevindees** [comment]
@xanatoses 

Do you have any js console errors you can send over?

**Comment by xanatoses** [comment]
I'm sorry but the only report i have is the consequence of continue the execution with an empty model:

PHP Fatal error:  Uncaught InvalidArgumentException: stats does not exist in Models properties array in my-plugin/typerocket/vendor/typerocket/core/src/Models/Model.php:1536

I solved it using `if($chart->count()==0)` method, but that's not the question here.

Thanks again!

**Comment by kevindees** [comment]
@xanatoses 

This will be working again in a new release of v4. I just created the patch. 

```
$chart= new \App\Models\Chart;
$result = $chart->findById(5);
if(!$result):
 echo "the chart no longer exists"; //it works perfectly in Beta 5
endif;
```
