### ISSUE TITLE
Letter case on post type menu

### ISSUE THREAD

**Issue by contactjavas** [TypeRocket/typerocket#196]
Im sure it's quite common to use an abbreviation as post type's admin menu name. For example:
```
// The result will be "Cms" instead of "CMS".
tr_post_type( 'CMS', 'CMS' );

// The result will be "Data Tps" instead of "Data TPS".
tr_post_type( 'Data TPS', 'Data TPS' )->setId( 'tps' );
```

Is it possible to use uppercase in post type's admin menu name using TypeRocket? Thank you for providing this great & elegant WordPress framework. I love this.

**Comment by kevindees** [comment]
Hey @contactjavas 

I have fixed this in a patch I'm about to release for v4.0

**Comment by kevindees** [comment]
Hey @contactjavas 

There is also a fix for this in v3 now. Just run `composer update`.
