### ISSUE TITLE
Wrong url on search filed

### ISSUE THREAD

**Issue by klocus** [TypeRocket/typerocket#197]
Hello,

When you will use "Search field", you will get an error 404 because TypeRocket is using wrong URL if you have WordPress installed in subdirectory.

**Example:**
I have a WordPress copy on `domain.com/wordpress/`
TypeRocket is using `domain.com/wp-json/typerocket/v1/search?post_type=any` (missing `wordpress`)

TypeRocket should get an address from WP Settings (siteurl).

**Comment by kevindees** [comment]
@klocus 

This is fixed in v4 of TypeRocket. Version 4 will be out of beta very soon.

**Comment by klocus** [comment]
@kevindees How users of v3 can fix that? Or is upgrade safe & easy?

**Comment by kevindees** [comment]
@klocus 

The upgrade is not easy but 100% worth it if you can. I'll be adding a few patching to v3 in the coming days before EOL that version. 

https://typerocket.com/docs/v4/upgrade-guide/

**Comment by ascaroit** [comment]
Hello, @kevindees first of all thank you for doing typerocket, amazing project!
I think I have a similar issue, I m developing a multisite woocommerce installation with two sites.
I use TR  "search field" in the subdirectory installation to search the products cpt, but the list is populated with the products of the other wp installation.
Any suggestions?

Thanks in advance

**Comment by kevindees** [comment]
@klocus @ascaroit 

This is now fixed in v3

https://typerocket.com/docs/v3/updating/

**Comment by klocus** [comment]
@kevindees I have an error after update:

`Uncaught ReferenceError: trHelpers is not defined`

**Comment by kevindees** [comment]
You will need to run `npm update` for this once and update the TR core asset for this update.

**Comment by klocus** [comment]
@kevindees I've already do that. 

1. `npm update`
2. Uncomment 2 lines from `gulpfile.js`
3. Run `npm run prod`.
4. Replace `core.js` (otherwise this file will not change)

**Comment by ascaroit** [comment]
@kevindees same here, when I start to type in the search field

Uncaught ReferenceError: trHelpers is not defined
 
Same steps to update

npm update
Uncomment 2 lines from gulpfile.js
Run npm run prod

**Comment by kevindees** [comment]
@klocus @ascaroit 

Try running `composer update`. I just created a patch release for the core.

**Comment by ascaroit** [comment]
@kevindees 

Hi 
the patch solve the problem for my local installation, but doesn't works if I upload online because the request is on http and i need an https request.

Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.

**Comment by kevindees** [comment]
@ascaroit 

Is your site URL set to https in your WP settings? I run into this issue from time to time and that tends to be it.

**Comment by ascaroit** [comment]
@kevindees 
yes https is set to wordpress URL.

**Comment by kevindees** [comment]
Hey @ascaroit 

It is working on SSL for me. I have the following set to force WP to use SSL in its URLs in the wp-config.php file.

```php
// use your domain
define( 'WP_HOME', 'https://tr3.tr' );
define( 'WP_SITEURL', 'https://tr3.tr' );
```

Here is how my requests are going through.

<img width="795" alt="Screen Shot 2019-04-16 at 1 59 12 PM" src="https://user-images.githubusercontent.com/348368/56233005-19528780-6050-11e9-9006-ba4ca78b20dc.png">

**Comment by kevindees** [comment]
@ascaroit 

If that does not work it could be your server config. If that is the case you may need to add a filter to update the scheme.

These would work:

```php
add_filter( 'home_url', function($url, $path, $orig_scheme, $blog_id) {
    return $url;
}, 10, 4);
```

**Comment by kevindees** [comment]
@klocus 

Is this working for you?

**Comment by klocus** [comment]
@kevindees Yes, thank you :)

**Comment by ascaroit** [comment]
@kevindees Yes, now it's ok. Thanks

**Comment by klocus** [comment]
@kevindees I have to reopen this issue. The same error shows when you try to add Matrix Field.

Current state:
```
domain.com/tr_matrix_api/v1/taxonomy_relations/relation/taxonomy_relations
```

Should be:
```
domain.com/wordpress/tr_matrix_api/v1/taxonomy_relations/relation/taxonomy_relations
```

**Comment by kevindees** [comment]
@klocus 

I have added a patch to the npm package. Let me know if that works for you.

Thanks,
Kevin

**Comment by klocus** [comment]
@kevindees Yes, it works! Thanks! :)
