### ISSUE TITLE
Route is  not working (both v3 and v4)

### ISSUE THREAD

**Issue by mithublue** [TypeRocket/typerocket#198]
I am using both version 3 and 4 in different plugins by including this framework in the plugin folder.
In version 4, in route.php , for testing purpose I have registered this route

    tr_route()->get()->match('/qqq/')->do(function (){
        echo 'hello world !'; die();
    });

I then, visited both domain_name/qqq and domain_name/wp-admin/qqq, both of them are showing me  404,

I then registered the above code in the 'typerocket_loaded' hook as well, but same scenerio.

Am I missing somehting?

Thanks.

**Comment by kevindees** [comment]
@mithublue 

Try omitting the ending and beginning forward slashes.

```php
tr_route()->get()->match('qqq')->do(function (){
    echo 'hello world !'; die();
});
```

**Comment by kevindees** [comment]
@mithublue 

I have updated the docs for this in v4. I missed updating a few examples from the v3 docs

https://typerocket.com/docs/v4/routes/
