### ISSUE TITLE
Item Field Type Cannot be Set

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#199]
Right now, the "Item" field doesn't let you use the `setType()` method to change the input type of the actual field within the repeater. Instead, it changes the input type of the hidden field that acts as the placeholder for the overall field name (which of course shouldn't be seen at all).

It was fairly simple to update the Item class to include a new property called `itemType` and a new method to set it, then alter the `getString()` method to use that type when instantiating the inputs for _existing_ entries. But unfortunately the template for adding new entries is entirely in JS, unlike the repeater field which uses a hidden template in the DOM that it copies.

Unfortunately, I'm up against a couple deadlines that make this a little beyond my capabilities at the moment. @kevindees, I'm also not sure what your preferred mechanism is to add this functionality (for instance, you may want to switch adding a new entry to copying a hidden DOM element like the repeater, or you may want to keep it entirely JS).

I'm kind of hoping this is something that could be added in the absolute mad amount of updates that have been flying out lately! We're hoping to use an Item field for a list of times, and would like to be able to use the HTML5 time input to make it simple for the user.

**Comment by kevindees** [comment]
@eric-michel 

This is now on the master branch. Feel free to use `dev-master` until next release.

**Comment by eric-michel** [comment]
@kevindees You're on fire!
