### ISSUE TITLE
No shortcode - code hint - provided inside repeater in dev mode

### ISSUE THREAD

**Issue by tylersloan** [TypeRocket/typerocket#2]
The repeater shows up in them options just fine, and provides the shortcode, but the repeated items inside it don't have any code to copy/paste into my template. Has something changed?

**Comment by kevindees** [comment]
**For Beta v1**:

Working with repeaters,

``` php
$form = tr_form();

$fields = array(
  array('text', array('First')),
  array('text', array('Last'))
);

$form->repeater('people', $fields, array(), 'People');
```

![screen shot 2015-05-12 at 8 38 07 am](https://cloud.githubusercontent.com/assets/348368/7587178/6526d54c-f882-11e4-8f5d-605d3029cb9c.png)

In the loop,

``` php
<?php
while(have_posts()) :
  the_post();
  var_dump( tr_post_field("[people]") );
endwhile;
?>
```

![screen shot 2015-05-12 at 8 40 41 am](https://cloud.githubusercontent.com/assets/348368/7587216/bc96d7d2-f882-11e4-9865-f1f01aba24c4.png)

From here you just need to loop through the items in the array to get your data.

``` php
<?php
while(have_posts()) :
  the_post();
  $people = tr_post_field("[people]");
  foreach($people as $fields) {
    echo $fields['first'];
    echo $fields['last'];
  }
endwhile;
?>
```

This will result in `KevinDees`.
