### ISSUE TITLE
Upgrade docs

### ISSUE THREAD

**Issue by twosg** [TypeRocket/typerocket#200]
I see some possibly breaking changes in the V4 releases info, but on https://typerocket.com/docs/v4/updating/ there is nearly no information about these.

Will there be more information about changes and on what to be aware of when upgrading from V3?

**Comment by kevindees** [comment]
Are you looking for this? https://typerocket.com/docs/v4/upgrade-guide/

**Comment by twosg** [comment]
Yes :) I assumed these informations should be on https://typerocket.com/docs/v4/updating/

Are you going to support v3 further?

**Comment by kevindees** [comment]
Hey @twosg 

Yes. I have no end of life planned for v3 at this time. I still submit critical patches to v3 when an issue comes up. I'm no longer adding new features though.

**Comment by twosg** [comment]
Thanks, great work!
