### ISSUE TITLE
Using a Repeater to Represent Records From a Related Model

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#201]
Hey @kevindees, sorry it took me longer than I hoped to get this ticket up.

So, right now I have a custom field I developed that I called the HasManyRepeater (kind of verbose, I know) - basically it extended your Repeater field to pull each row in the Repeater from an individual record in a related table.

So, for instance, this Repeater field:
![image](https://user-images.githubusercontent.com/45110062/57898301-78114980-7826-11e9-8d5e-ef95f2c07396.png)

corresponds to these records in the database in a table called `wp_event_dates`:
![image](https://user-images.githubusercontent.com/45110062/57898388-e35b1b80-7826-11e9-8fff-36b16d58e921.png)

When I upgrade to the latest version of TR core, it breaks this custom field, (which isn't a surprise). What I'd like to do is abandon that custom field, especially because I had to extend several other classes to get it to work, and use your new features to connect to the related table.

However, unless I'm missing something, it looks like I can't quite do what I want.

When I use the features you've documented in [this video](https://www.youtube.com/watch?v=-NqsKtOOu0w), I can set a new form within the main form of the Event post type and set its Group to be related to my related Model. So far so good.

However, your example is set as a one-to-one relationship, and I'm not sure how to get the one-to-many I'm looking for here. It looks like I should be able to get the _saving_ part to work just fine, as I would just iterate over each row in the Repeater when I extend the `update` method in the extended `PostController`. However, I can't figure out how to _retrieve_ the records that exist in the database and display them in the Repeater. Based on the source code (and I could easily be getting this wrong), it looks like it's still just looking for a serialized array in a one-to-one relationship in a field with the same name as the Repeater itself.

In addition, I'd also like to be able to filter the records it actually pulls into the Repeater when it retrieves the rows from the related table (in this case, I'd like it to only pull in dates that are in the future).

I may be overlooking something simple (and hope I am). What do you think?

Thanks in advance! Loving a ton of the new features!

**Comment by kevindees** [comment]
Hey @eric-michel 

One-to-many should work the exact same way. Nothing special to do there. What does your model code look like for both tables?

If you have a repeater field all you do not need to set the form group.

```php
tr_post_type('post')->setEditorForm(function() {
   $form = tr_form();
   echo $form->repeater('Meta')->setFields([
       $form->text('meta_key'),
       $form->text('meta_value'),
   ]);
});
```

> In addition, I'd also like to be able to filter the records it actually pulls into the Repeater when it retrieves the rows from the related table (in this case, I'd like it to only pull in dates that are in the future).

A: Just chain a where statement to the `hasMany` method (might work not sure).

**Comment by eric-michel** [comment]
Hey @kevindees, still a bit confused. Are you saying that the name for the Repeater field should be the relationship method? Is that how it knows what table to look in for the row values?

I ended up reverting my update to the current version of TR, but I'll definitely re-install it and try again. I'm just still not quite clear on how to tell the Repeater to look at the separate table for its rows.

**Comment by kevindees** [comment]
@eric-Michel 

Yes. The repeater fields name needs to be set to the relationship methods name. You can do that using setName on the field I think if you wanted a different name for the label.

Let me know if that works for you.

**Comment by kevindees** [comment]
Hey @eric-michel 

I'm closing this one out. I'm assuming the solution provided here worked out for you.

**Comment by eric-michel** [comment]
@kevindees Hey Kevin, just got this tested and working today. *So* incredibly easy compared to what I was doing. Still need to see if I can chain a `where` onto the `hasMany` method but I'll work on that next.

Thanks again for your help! This mechanism opens so many doors for different types of related data!
