### ISSUE TITLE
Migrations not working out of the box in v4

### ISSUE THREAD

**Issue by nebulousGirl** [TypeRocket/typerocket#202]
I needed to add the MakeMigration class to the commands config, but there's no mentions of this in the docs.

There was also an issue with the config in paths.php migrate.migrations is an array, but the MakeMigration class expects a string.

Is this because Migrations haven't been updated yet? Or should I make a pull request?

**Comment by kevindees** [comment]
Hey @nebulousGirl 

Is your core install of v4 up to date?

**Comment by kevindees** [comment]
@nebulousGirl 

You need to do this: https://typerocket.com/docs/v4/galaxy-cli/#section-wp-commands

To do this: https://typerocket.com/docs/v4/migrations/

**Comment by nebulousGirl** [comment]
I was on version 4.0.24 and have updated now.

Yup, I have seen the docs.

I still need to add this: 

`
    'commands' => [
        MakeMigration::class,
        Migrate::class
    ]`

To my galaxy config file to make the migration commands available, but don't see this in the documentation.

FYI, I installed Typerocket as a MU Plugin.

**Comment by nebulousGirl** [comment]
It turns out I misconfigured the galaxy config for Wordpress. I think it would be helpful to add an error when the config is not false and the wp-load file is not found in the console launcher class. At the moment, it can be quite confusing since the error is unrelated to the misconfiguration.

**Comment by kevindees** [comment]
@nebulousGirl 

Thanks! I've added better error messaging to the WP CLI commands based on your feedback. Updates will be in the next release.
