### ISSUE TITLE
How to use default WordPress taxonomies

### ISSUE THREAD

**Issue by mboisvertdupras** [TypeRocket/typerocket#203]
I apologize if this is documented somewhere but I haven't been able to find much information regarding the use of the built-in post_tag and category taxonomies on TypeRocket custom post types.

Ideally I would like to re-use the built-in WordPress ones and not have to re-register a category and a variation of tag. Is it possible?

**Comment by kevindees** [comment]
Hey @aft3rlife 

You can use `addPostType()` for taxonomies. 

https://typerocket.com/docs/v4/taxonomies/#section-apply-post-types

And, `addTaxonomy` for post types. I'm not seeing this in the Docs.

```php
tr_post_type('book')->addTaxonomy('category')->addTaxonomy('post_tag');
```

**Comment by kevindees** [comment]
@aft3rlife 

Updated the docs.

https://typerocket.com/docs/v4/post-types/#section-apply-taxonomy-and-meta-boxes-applying-to-existing-taxonomies

**Comment by mboisvertdupras** [comment]
Fantastic, thank you!
