### ISSUE TITLE
Item Field Type Only Set on Existing Rows

### ISSUE THREAD

**Issue by eric-michel** [TypeRocket/typerocket#204]
@kevindees I'm finally getting around to implementing the changes from [this issue](https://github.com/TypeRocket/typerocket/issues/199). It looks like the changes only covered the part where it pulls in existing rows. The JS is still setup so that it creates a text field, regardless of how the `setInputType` method is used.

In the example below, I've used `setInputType( 'time' )`. The top field is a newly added one, whereas the bottom field was already saved and has been loaded in.

![image](https://user-images.githubusercontent.com/45110062/58383124-a8808280-7fa0-11e9-8a16-422688a6e203.png)

The JS that causes this is on line 27 in tooling/items.js, seen here:
            `$ul.prepend($('<li class="item"><a class="move tr-control-icon tr-control-icon-move"></a><a href="#remove" class="remove tr-control-icon tr-control-icon-remove" title="Remove Item"></a><input type="text" name="' + name + '[]" /></li>')`

Since the creation of the new item field is hard set in the JS rather than coming from a hidden template (like the Repeater field), the JS would need to be updated to somehow detect what item type to use.

**Comment by kevindees** [comment]
Hey @eric-michel 

I have updated core with a fix but I have not created a release yet. You can use the latest version but setting your version to `dev-master`... I think.

**Comment by eric-michel** [comment]
Awesome, thanks @kevindees!

**Comment by eric-michel** [comment]
Hey @kevindees, just now getting a more recent release installed so I can have my item field work as expected. I see where you updated items.js, but it doesn't look like the minified version of core.js ever got recompiled to use the new code. When I look at the minified core.js that gets pulled into the admin, I see this:
```
e(document).on("click", ".items-list-button", function() {
            var t, r;
            (r = (t = e(this).parent().next()).attr("name")) && t.data("name", r),
            r = t.data("name"),
            t.prepend(e('<li class="item"><a class="move tr-control-icon tr-control-icon-move"></a><a href="#remove" class="remove tr-control-icon tr-control-icon-remove" title="Remove Item"></a><input type="text" name="' + r + '[]" /></li>').hide().delay(10).slideDown(150).scrollTop("100%"))
        }),
```
You'll notice the input type is still hard set as "text".

If it's easy to quickly compile that core.js file, that would be awesome. It looks like you might currently be using webpack to do that (?) but I'm not really familiar with that process.

Thanks again!

**Comment by kevindees** [comment]
Hey @eric-michel 

Updated the docs to help you with that. I'll update the core files here soon too.

https://typerocket.com/docs/v4/updating/#section-assets

**Comment by kevindees** [comment]
https://github.com/TypeRocket/typerocket/releases/tag/v4.0.9

**Comment by eric-michel** [comment]
@kevindees oh that's so incredibly easy! Awesome, I'll make a note to remember that from now on in case the same thing happens. Thanks for the quick response!
