### ISSUE TITLE
Is there a way to generate url from route?

### ISSUE THREAD

**Issue by deloz** [TypeRocket/typerocket#205]
Like [https://laravel.com/docs/5.8/urls#urls-for-named-routes](https://laravel.com/docs/5.8/urls#urls-for-named-routes)

eg:

has a route like:

```PHP
tr_route()
    ->get()
    ->noTrailingSlash()
    ->match('product/(.+?)', ['postName'])
    ->do('view@Product')
    ->name('product.view');
```

and in the view file, we can use the `tr_url` function to generate real url `/product/crontab`

`echo tr_url('product.view', ['postName' => $product->post_name]);`

**Comment by kevindees** [comment]
Hey @deloz 

We do not have named routes right now. I have looked at adding them before but named routes tend to lower performance when you have several routes in place.

I might look at it again though.
