### ISSUE TITLE
Routes not working

### ISSUE THREAD

**Issue by gabrielfojo** [TypeRocket/typerocket#206]
I have version 4 installed a few days back, its a composer install inside a generatepress theme. A simple route give me 404 :

tr_route()->get()->match('qqq')->do(function (){
    echo 'hello world !'; die();
});

Permalings are pretty and are flushed - any ideas? thanks

**Comment by gabrielfojo** [comment]
I have to add, this is a docker install - To be sure, i have installed a fresh WP in my server , installed the TypeRocket plugin, set the permalink structure, and still I'm having 404 - thanks

**Comment by kevindees** [comment]
@gabrielfojo 

Try using the `tr_load_routes` hook.

```php
add_action('tr_load_routes', function() {
  tr_route()->get()->match('qqq')->do(function (){
    echo 'hello world !'; die();
  });
});
```

If that does not work, try updating your install? There were a few updates that came through over the last few days.

**Comment by gabrielfojo** [comment]
Thanks for answering. I have not access now to my local docker, but I'm testing in my server now (Media Temple) - I have changed the code, but I'm in the same place - This WP install is a fresh one, a few minutes back , clean - The plugin has just been downloaded from your web site (latest.zip) - some clue to debug it? thanks

**Comment by kevindees** [comment]
Do you have `WP_DEBUG` set to `true`?

**Comment by gabrielfojo** [comment]
I have now -  https://trialvd.com.ar/wp1/qqq

**Comment by kevindees** [comment]
Hey @gabrielfojo 

Typerocket routes look at the full URL. You may need to add the wp folder to your route. I'll look at adding a feature that works better with that type of installation

```php
add_action('tr_load_routes', function() {
    // not sure if this works just mocking it up for you
   // expected: $prefx = 'wp1'
   $prefx = trim(str_replace('https://trialvd.com.ar/', '', home_url()), '/')

  tr_route()->get()->match( $prefx . '/qqq')->do(function (){
    echo 'hello world !'; die();
  });
});
```

```php
add_action('tr_load_routes', function() {
   // hard coded version
   $prefx = 'wp1'

  tr_route()->get()->match( $prefx . '/qqq')->do(function (){
    echo 'hello world !'; die();
  });
});
```

**Comment by gabrielfojo** [comment]
This is the response 
Parse error: syntax error, unexpected 'tr_route' (T_STRING) in /.../plugins/typerocket-framework/typerocket/routes.php on line 22
The site is experiencing technical difficulties.
---------------------------------
This is a test instalation, so no big deal, you say that the problem is becouse WP is not a root instalation?

**Comment by kevindees** [comment]
Can you post your code with lines numbers? Or highlight line 22?

**Comment by gabrielfojo** [comment]
routes.php its just what you have passed me : 


`<?php
/*
|--------------------------------------------------------------------------
| TypeRocket Routes
|--------------------------------------------------------------------------
|
| Manage your web routes here.
|
*/
/*
add_action('tr_load_routes', function() {
  tr_route()->get()->match('qqq')->do(function (){
    echo 'hello world !'; die();
  });
});
*/

add_action('tr_load_routes', function() {
   // hard coded version
   $prefx = 'wp1'

tr_route()->get()->match( $prefx . '/qqq')->do(function (){ // line 22
    echo 'hello world !'; die();
});
});`

**Comment by gabrielfojo** [comment]
the error was a missing ; in the code yo pass me, i still got the 404

**Comment by kevindees** [comment]
@gabrielfojo 

Looks like you are missing a `;`.

```php
$prefx = 'wp1' // bad
$prefx = 'wp1'; // good
```

Also, per the docs https://typerocket.com/docs/v4/#section-wp-plugin

If you are using the official plugin version of TypeRocket you should not edit the core files including the  `routes.php` file or `app` folder. Any updates that come through the automatic updates system will remove your edits.

To add custom routes and add a custom `app` and `config` folder to follow the configuration step of the install guide https://typerocket.com/docs/v4/installation/#section-wp-plugin-2-configuring 

The best way to add custom routes is to do so in a custom plugin. For example, create a WP plugin names `my-plugin.php` under your plugins folder.

In that file add:

```php
<?php
// Plugin Name: My Plugin
add_action('tr_load_routes', function() {
    $prefx = 'wp1';

    tr_route()->get()->match('qqq')->do(function (){
        echo 'hello world !'; die();
    });

    tr_route()->get()->match( $prefx . '/qqq')->do(function (){
        echo 'hello world !'; die();
    });
});
```

**Comment by gabrielfojo** [comment]
I have created the plugin and now its working fine - this was a test instalation here - 
In home i have a docker install with a theme instalation, i had the same problem there, i will test later if what you gave me here helps there too- Thanks for your help, awesome job!
