### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by gabrielfojo** [TypeRocket/typerocket#208]
I have added a middleware  : 
```
------ MIddleware
namespace App\Http\Middleware;

use \TypeRocket\Http\Middleware\Middleware;

class JwtAuth extends Middleware
{
    public function handle()
    {
        $request = $this->request;
        $response = $this->response;
        // Do stuff before controller is called
        exit('Check');
        $this->next->handle();
        // Do stuff after controller is called
    }
}
------ Kernel
use App\Http\Middleware\JwtAuth;
 public $middleware = [
        'hookGlobal' => [],
         .....
        'jwt' => 
            [ JwtAuth::class ]
            
    ];
```
In routes: 
```
tr_route()->get()->match($prefix.'test')->do('test@Test')->middleware(array('jwt'));
```
I have added it as i do in Laravel, but it seems the classs expects an Array - nothing happens - 
I'm missing something? Thanks

**Comment by kevindees** [comment]
@gabrielfojo 

In TypeRocket you pass a list of classes instead of a named group in the `middleware()` method. Also, TypeRocket uses the controller name, in your case test@**Test** as the named middleware group in lowercase.

```php
tr_route()->get()->match($prefix.'test')->do('test@Test')
```

**Comment by gabrielfojo** [comment]
Thanks for your answer so quick! I have created the group test in the kernel and the middleware works, now I have JWT!   - The middleware function as it is in laravel, added to the chain like this :

tr_route()->get()->match($prefix.'test')->do('test@Test')->middleware();

This won't work? I should add every controller in the kernel??
I'm sorry to bother you with these things, but there is no much info in the  middleware docs. 
Thanks again for your time

**Comment by kevindees** [comment]
Hey @gabrielfojo 

Added a feature to the middleware to help you out:

https://github.com/TypeRocket/core/releases/tag/v4.0.41
