### ISSUE TITLE
Field Dependancy

### ISSUE THREAD

**Issue by shahbaz-dev1** [TypeRocket/typerocket#21]
Really clean and awesome work, you have covered all areas like Laravel. One thing I can't see in the application is field dependency. If it exists in the app then how can I use it ( may be missing the docs ) or if its not in the app then do you have plan to add it. Really appreciate your response.

**Comment by kevindees** [comment]
Hey wowthemes,

I have not but a lot of thought into field  dependency. If by field dependency you mean in effect fields requiring other field to be used (conditional fields).

However, I have been using custom JS to handle these situation in my own project work.

It is an interesting idea though and I have considered it. I just have not considered the best way to interface with conditional fields for TypeRocket.

Is this what you are talking about? If so are there example system you think handle it well?

Thanks,
Kevin

**Comment by shahbaz-dev1** [comment]
@kevindees Exactly, I am talking about the conditionals. We can do it in a way like `$form->text('text')->dependency('otherfield', '=', 'somevalue');` and the output would be `<input type="text" name="text" data-dept="otherfield" data-condition="=" data-value="somevalue" />` and then we can handle it through jquery or javascript

Other examples are 

`$form->text('text')->dependency('otherfield', 'in', [1,2,3]);`

`$form->text('text')->dependency('otherfield', 'like', '%somevalue%');`

`$form->text('text')->dependency( ['otherfield', 'otherfield1', 'otherfield2'], '=', ['somevalue', 'somevalue1', 'somevalue2']);`

**Comment by kevindees** [comment]
Hey @wowthemes,

I see what you are talking about now. I can see TypeRocket doing something like this. I feel like it would need to be pure JS so you can:

1. Have multiple field dependencies not just one.
2. Have custom calculation for passing dependency checks if you wanted to get fancy.
3. Have dependency check work within repeatable and matrix fields.

However, we would make the JS library very simple and intuitive. So I could see something like this:

```js
var trForm = new TypeRocketForm({
   'el': '#myForm',
   'fields' : {
      'field_one': {
         'depends': {
            'repeater.new_field': {
               'repeater': 'any', // any, 1, sibling, child
               'condition': '=',
               'value': 'somevalue'
            }
         }
      }
   }
});
```

**Comment by shahbaz-dev1** [comment]
@kevindees Thanks, I'll check and let you if it works or not

**Comment by kevindees** [comment]
Hey wowthemes,

There is no implementation for the example I sent you. But, I can see adding it to version 3.1 which I am starting to roadmap.

Thanks,
Kevin

**Comment by shahbaz-dev1** [comment]
Hi @kevindees 

Any news about dependency, I used it in my premium projects and dependency is necessary for them. Really appreciate your efforts.

Thanks,

**Comment by kevindees** [comment]
Hey @wowthemes,

I have not been able to build this feature out yet. I would expect it to be done in the next 3-4 months. However, I have used basic JS to handle what you are talking about myself. I don't know if that is the solution you are looking for but right now but the feature you need is still under development.

Thanks,
Kevin

**Comment by shahbaz-dev1** [comment]
Hi @kevindees 

What I have in my mind. Add the following methods in `Typerocket\Elements\Fields\Field`

```php
/**
     * [setDepend description]
     *
     * @param [type] $field [description]
     * @param [type] $value [description]
     */
    public function setDepend( $field, $value ) {

        $this->dependency = array( $field, $value );

        return $this;
    }

    /**
     * [getDepend description]
     *
     * @return [type] [description]
     */
    public function getDepend() {
        return $this->dependency;
    }
```
Then in each field type print the dependency like `data-dependency="<?php echo json_encode( $field->getDepend() ); ?>"`

Then from JS code manipulate the `data-dependency` . 

If you agree then I can write some code in my Fork so you can review it.

Thanks

**Comment by kevindees** [comment]
Hey @wowthemes 

I'm still thinking through this request at the moment but I can see this potentially working.

Having a property called `data-dependency` is an interesting idea and can be parsed easily enough. I think the dependency binding needs to be robust enough to account for multiple bindable fields while also being extensible.

However, I feel like having a pure JS solution would be a good approach.

Also, I have been thinking about adding a macro system to certain classes like `Form` and `Fields` to allow anyone to add features like this using PHP magic methods to prove the concepts. this would allow everyone to make the feature they want without depending on a core update.

For example,

```php
trait Macroable
{
    public $macro = []

    public function __call($method, $parameters)
    {
        if (! $this->macro[$method]) {
            throw new BadMethodCallException("Method {$method} does not exist.");
        }
        if (static::$macros[$method] instanceof Closure) {
            return call_user_func_array($this->macro[$method]->bindTo($this), $parameters);
        }
    }
}
```

**Comment by shahbaz-dev1** [comment]
@kevindees Okay, If you do that then I'll revert my changes in the core and do it through hooks.

Thanks

**Comment by kevindees** [comment]
Hey @wowthemes 

I have added the macro system and hooks to the `Form`, `Field`, and `Tables` classes so you can take advantage of the system.

https://github.com/TypeRocket/core/releases/tag/v3.0.46

For example:

```php
add_action('tr_after_field_element_init', function($field) {
    $field->setMacro('setDepend', function($field, $value) {
        $this->dependency = array( $field, $value );

        return $this;
    });
});
```

**Comment by shahbaz-dev1** [comment]
@kevindees Thanks, Will give it a try.

**Comment by clemorphy** [comment]
Any news about a "conditional fields" / "field dependency" feature ?

**Comment by kevindees** [comment]
Hey @clemorphy 

I do not plan to implement this feature until Gutenberg comes out and brings React over with it. At that time I will have better tools to deal with field dependency in a modern way. I'll keep everyone updated on this thread with updates on this feature.

If you need this feature there are other tools that you can use to gain the effect you are wanting.

For example http://dstreet.github.io/dependsOn/

Thanks,
Kevin

**Comment by hvsombrilla** [comment]
Would be the same as (?)
```php
$form->text('text')->setAttribute('data-dependency', 'parent-field');
```
