### ISSUE TITLE
problems with tr_table

### ISSUE THREAD

**Issue by netdust** [TypeRocket/typerocket#210]
hi

I am trying out a few things and stumble into issues, i am not sure if I am doing something wrong.

I try to add a table to a page without using a controller, directly added with view_file. Tables don't seem to work like this,  a controller is needed. is this the case?

also when I add a model from a custom posttype to a table ( tr_table( 10, $some_posttype_model ) ) the table renders empty rows, but not the actual posttype items

does anybody encouter the same issues?

**Comment by kevindees** [comment]
@netdust 

Can you post your code here?

Thanks,
Kevin

**Comment by netdust** [comment]
I made a Model  'Vormingen' for the custom posttype 'ntdst_vormingen'
```
class Vormingen extends WPPost
{
    protected $postType = 'ntdst_vormingen';
}
```

Then in the page view, initiated by it's controller, I add this:
```
$table = tr_tables(10, new \App\Models\Vormingen);
$table->setColumns('post_title', [
    'post_title' => [
        'label' => 'Title',
        'sort' => true,
        'actions' => ['edit', 'delete', 'view'],
        'delete_ajax' => false, // disable AJAX delete
        'callback' => function( $text, $result ) {
            return $result ? '<strong>'.$text.'</strong>' : '';
        },
        'view_url' => function($show_url, $result) {
            $id = $result->id;
            return "/vad_opleidingen/{$id}/";
        }
    ],
    'ID' => [
        'label' => 'ID',
        'sort' => true
    ],
]);
$table->render();
```

it renders the table, but instead of seeing a posttype item, i see al the saved drafts...

![image](https://user-images.githubusercontent.com/344524/60615784-418c8f80-9dd0-11e9-8b3f-ae796e71f2e6.png)

**Comment by kevindees** [comment]
@netdust 

What is the result you are expected?

Also, maybe just get the published items.

```
(new \App\Models\Vormingen)->published()
```

**Comment by netdust** [comment]
🤣 that was what i needed!!
thx for the quick response
