### ISSUE TITLE
tr_pages and tr_meta_box to build dashboard

### ISSUE THREAD

**Issue by netdust** [TypeRocket/typerocket#211]
Hi,

I can't  seem to find a way to add metabox to a page or a custom resource. It would be nice to build a dashboard style index page using metaboxes...

Is this possible?

**Comment by kevindees** [comment]
Hey @netdust 

We do not have that feature right now. I played with the idea in the past but it felt too much like a hack. I may look at it again since it has been a few years.

**Comment by netdust** [comment]
Ok,  it would be a nice feature to have!
