### ISSUE TITLE
Urgent: import data in wp database

### ISSUE THREAD

**Issue by robcal** [TypeRocket/typerocket#212]
Hello, I was trying TypeRocket (a truly exceptional product) and I wanted to import data from another database.
In particular I created a dedicated taxonomy called Department which has a custom field called "color".
I created the relative model and the controller and I have no problem creating the department with its name, but how can I save the "color" custom field from the model?
How to save custom taxonomy / post_type fields from the model?
Thanks
Roberto

**Comment by robcal** [comment]
And another question: how to populate custom image fields?
thanks for help

**Comment by kevindees** [comment]
Hey @robcal 

Can you send your code over so I can look at your approach?

Thanks,
Kevin
