### ISSUE TITLE
Custom admin page as a subpage of a post type?

### ISSUE THREAD

**Issue by matteo-greco** [TypeRocket/typerocket#215]
I'm using `tr_page()` to create a custom admin page, and I'd like to add it to the menu as a subpage of a custom post type, like you'd do with `add_submenu_page( 'edit.php?post_type=stabilimenti', ... )`. However, it seems that the `setParent()` method of the `Page` class requires another `Page` object and won't accept a string like add_submenu_page. 

Can this be achieved in typerocket?

**Comment by kevindees** [comment]
Hey @matteo-greco 

I'll need to look into adding that feature into the core.
