### ISSUE TITLE
Search field on a frontend form

### ISSUE THREAD

**Issue by matteo-greco** [TypeRocket/typerocket#217]
Hello!
I have a search field that looks for posts in a certain post type:

`echo $form->search( 'id_stabilimento' )->setPostType( 'stabilimenti' )->setLabel( 'Stabilimento' );`

It's working great in a custom resource page in the backend. However, it doesn't allow me to pick anything when displayed in a frontend form (while all other fields work fine). What should I do to get it to work?

Thanks

**Comment by kevindees** [comment]
Hey @matteo-greco 

Do you have front-end assets enabled?

https://github.com/TypeRocket/typerocket/blob/master/config/typerocket.php#L12

Thanks,
Kevin
