### ISSUE TITLE
Pages listing shows the error

### ISSUE THREAD

**Issue by shahbaz-dev1** [TypeRocket/typerocket#22]
I have enabled builder plugin and when I visit the pages listing it shows the error `typerocket\vendor\typerocket\core\src\Core\Launcher.php on line 216` while the builder doesn't work too when add/edit page. Can you please have a look at this issue.

**Comment by kevindees** [comment]
What version of php and WordPress are you using? This will help me diagnose the issue.

Any other setup information will be helpful as well.

Thanks,
Kevin

**Comment by shahbaz-dev1** [comment]
PHP 7.1 and WordPress version is 4.8 , its the fresh installation with 2017 theme and no plugin activated. BTW I am using typrocket as a plugin and I think this is the thing causing issue.

**Comment by shahbaz-dev1** [comment]
Here is the error screenshot 
![screenshot 2017-06-11 01 28 19](https://user-images.githubusercontent.com/16266732/27006094-7e6ffd9c-4e45-11e7-883c-1184dec9fa7d.png) May be it helps in diagnosing the issue

**Comment by kevindees** [comment]
Hey wowthemes,

I believe I have found your error. You can run `composer update` from the TypeRocket folder and that will download the new core version with the patch v3.0.15.

Thanks,
Kevin
