### ISSUE TITLE
How to remove SEO metabox from custom post?

### ISSUE THREAD

**Issue by mbrughi** [TypeRocket/typerocket#226]
I try to remove SEO metabox only from specific custom post.
I use this code from codex to remove_meta_box, but don't work:

`
add_action( 'admin_menu', 'seo_remove_meta_box');
function seo_remove_meta_box(){
   remove_meta_box('seo_meta', 'slider', 'normal');
}     
`

**Comment by kevindees** [comment]
Hey @mbrughi 

What version of TypeRocket you are using?

Thanks,
Kevin

**Comment by mbrughi** [comment]
Hi @kevindees 
   the version is v4 'assets' => '4.0.8'

**Comment by kevindees** [comment]
You might need to call the remove function using the `typerocket_loaded` hook.

```php
add_action( 'typerocket_loaded', 'seo_remove_meta_box', 20);

function seo_remove_meta_box() { 
    remove_meta_box('seo_meta', 'slider', 'normal');
    remove_meta_box('tr_seo', 'slider', 'normal');
}
```
