### ISSUE TITLE
Removing the example pagebuilder makes it so fields do not save anymore.

### ISSUE THREAD

**Issue by fredy31** [TypeRocket/typerocket#227]
I just upgraded to v5, and ran into a weird issue. If I desactivate the example pagebuilder via a PHP line `define('TYPEROCKET_PAGE_BUILDER', false);`, as told in the TYPEROCKET_UI page, i cannot save any created fields.

So now I'm stuck with a choice. Have the builder box show up, or can't save any fields.

I dont know why it reacts like that, and its a weird reaction, but thats what I'm getting.

If you need anything else, or have ways to show more debug information, I can give you it. Just ask.

**Comment by kevindees** [comment]
Hey @fredy31 

Are you getting any specific PHP errors?

Thanks,
Kevin

**Comment by fredy31** [comment]
Sorry for the late reply. Got a crazy week.

So even with WP_Debug on, there was no apparent PHP Errors. Any other line I can put in so TR is also in debug mode?
