### ISSUE TITLE
Manually loading Pagebuilder items

### ISSUE THREAD

**Issue by fredy31** [TypeRocket/typerocket#229]
If I understand the docs well, you have not much choice in where your pagebuilder items have to be. It needs to be in the plugin folder, or you can modify where it is with a line in wp-config and transfering a bunch of the code from the plugin to the theme (or whereever you want it.)

In my agency we are looking to build a basic theme upon typerocket with the pagebuilder, but I would prefer to leave it in the theme, and where I actually need them to be. Typerocket is one of many moving pieces so I don't really want the bunch of files from TR in the main theme.

So is there a way to manually, from the functions.php file of the theme, add in the components I want instead of having to put them in the theme? Like what I would like to do is a folder that I can move from theme to theme, containing the component setup, the component thumbnail and images/sass/js that is with it. So something like a function that I give it the php of the field and the jpg/png of the thumb would be perfect, if that exists. (I'll add JS and SCSS by other means)

**Comment by kevindees** [comment]
Hey @fredy31 

I'm looking into options to allow for this.

Thanks,
Kevin

**Comment by kevindees** [comment]
Hey @fredy31 

I have added two new hooks to make this possible in v5. The update will roll out to the main plugin soon.

https://github.com/TypeRocket/core/releases/tag/v5.0.68

Thanks,
Kevin
