### ISSUE TITLE
How to add a field in wp-json?

### ISSUE THREAD

**Issue by joannesalfa** [TypeRocket/typerocket#230]
Hi, I've been reading your docs about v5 but I'm lost, I was trying to figure out how to add a field in wp-json from custom post type, take a look at this code:

```
// Setup
$team = tr_post_type('Person', 'Team');
$team->setIcon('dashicons-groups');
$team->setSupports(['title']);
$team->setTitlePlaceholder( 'Enter full name here' );
$team->setRest();
$team->setArchivePostsPerPage(-1);

// Custom Fields
$team->setTitleForm( function() {
    $form = tr_form();
    echo $form->image('Photo');
    //echo $form->editor('post_content')->setLabel('About Person');
});

tr_meta_box('Team Details')->apply($team)->setCallback(function() {
    $form = tr_form()->useRest();
    echo $form->text('Job Title');
});

$team->addColumn('Job Title');
```

I want to add "Job title" in wp-json but it won't appear in **yourdomain.com/wp-json/wp/v2/person** anymore
Thanks!

**Comment by kevindees** [comment]
@joannesalfa 

Great question. This is a WordPress thing. You need to use `register_meta` for WordPress to see custom fields. I am working on a clean way to do this in TypeRocket though.

https://developer.wordpress.org/reference/functions/register_meta/

Thanks,
Kevin

**Comment by joannesalfa** [comment]
I'm letting you know how I achieved it

After of applying the function with wp_register_meta like this:

```
add_action( 'rest_api_init', 'register_tr_meta_fields');
function register_tr_meta_fields(){

    register_meta( 'post', 'job_title', array(
        'type' => 'string',
        'single' => true,
        'show_in_rest' => true
    ));

    register_meta( 'post', 'photo', array(
        'type' => 'number',
        'single' => true,
        'show_in_rest' => true
    ));

}
```

It will not work UNTIL you add like this:

`$team->setSupports(['title', 'custom-fields']);`

custom-fields can solve this issue. Unfortunately it affects the global, not just custom type. Use `register_post_meta` instead of `register_meta` and replace "post" to "person" it will only show 2 meta keys in JSON object with "person" post type.

Kind regards.
