### ISSUE TITLE
[feature request] scaffolding for validators (validation rules)

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/typerocket#231]
It would be nice, if the `galaxy` CLI could scaffold a [custom validator](https://typerocket.com/docs/v5/validator/#section-custom-validation-rules).

Example:
```
galaxy make:validator DomainEmail
```

would create something like this:
```PHP
<?php
namespace App\Validators;

use TypeRocket\Utility\Str;
use TypeRocket\Utility\Validator;

class DomainEmailValidator extends ValidatorRule
{
    public function validate(): bool
    {
        /**
         * @var $option
         * @var $option2
         * @var $option3
         * @var $full_name
         * @var $field_name
         * @var $value
         * @var $type
         * @var Validator $validator
         */
        extract($this->args);

        return !$this->error;
    }
}
```

**Comment by kevindees** [comment]
Hey @jdoubleu 

There should be a command called `make:rule` that does this. I'll check the docs to see if it is in them.

Thanks,
Kevin

**Comment by jdoubleu** [comment]
Okay, I didn't know and certainly didn't read the description.

Nonetheless, the documentation, especially the section which "introduces" custom validation rules, does not provide that command.

It might also be confusing, that
1. The page itself is named "Validator",
2. the section describes it as "validation rule",
3. the base class is called "ValidatorRule"

**Comment by kevindees** [comment]
Added the command to that section of the docs :)
