### ISSUE TITLE
Featureless posts have "auto-draft" slugs (post_name)

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/typerocket#232]
When creating a custom `post_type` with no default fields (`PostType::featureless()`), but providing a `PostType::saveTitleAs` hook, all posts created will have the `auto-draft-NN` post slug.

Unfortunately, there is no `PostType::saveSlugAs` hook. I have to use the built-in WordPress hooks for when a post is saved, or maybe use the `typerocket_controller_after_update` hooks.

It would be nice to either be able to set the post slug, just like the title, through a simple hook with the post type builder (`PostType`). At that point I could also imagine opening up these "hook" interface to any field, not just `title`, `content, `excerpt`, `menuOrder`.

**Comment by kevindees** [comment]
@jdoubleu addressed https://github.com/TypeRocket/core/commit/388e1e6415caa50860502f15e36064191570ae5f

**Comment by jdoubleu** [comment]
Wow, that was fast! Thank you very much for addressing this so quickly.
Good job!
