### ISSUE TITLE
Flash messages are not shown on post edit page

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/typerocket#235]
No flash messages, neither warnings or errors, are shown on a single post's edit page in the backend. When I add some messages (`Response::flashNext`) inside the `WPPostController::update` function, it will not be displayed in the backend.

I assume this happens, due to the fact, that the `wp_update_post` hook actually triggers the controller in the end. So there is no real HTTP request going through the core.

Is there a way to circumvent this limitation?

**Comment by kevindees** [comment]
@jdoubleu addressed https://github.com/TypeRocket/core/commit/91f6233fae7b3aba41cb9f2e56ed9a7de01bd13c
