### ISSUE TITLE
[bug] multiple forms on one page pollutes fields

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/typerocket#238]
When there are multiple forms on the same page, some fields might be polluted by "old" values from fields from another form. Additionally, error and flash messages might be displayed on the wrong form.

## Example
On one page there is a contact form and a newsletter subscription form in the sidebar. Both forms include an `email` field. They are created using the `tr_form()` helper. Each form has a different action, causing **no** issue on the server-side.

### The problem
If a user submits the newsletter subscription form and their provided email does not pass verification, an error message is shown in the contact form as well as its `email` field might be filled with the newletter form's "old" `email` value. This is due to the contact form being rendered first, popping the "old" value from the transient cache.

## Workaround
Right now, the only way I could think of is to use a different prefix for each form:
```PHP
$form = tr_form();
$form->setPrefix('contact'); // or "newsletter"
```

This comes at a cost, since then my controller actions can no longer use [HTTP Fields](https://typerocket.com/docs/v5/http-fields/). The `Fields` constructor pulls all data from the current request using the default prefix (`tr`) (see https://github.com/TypeRocket/core/blob/main/src/Http/Fields.php#L37).

## Suggestion
I could imagine a mechanism, where the custom `Fields` class has a `prefix` property which it will use to get the data from the current request:
```PHP
class Fields {
    protected $form_prefix = 'tr';

    public function __construct( $fields = null ) {
        parent::__construct();

        if( empty($fields) ) {
            $fields = (new Request)->getFields(null, null, $this->form_prefix);
        }

        $this->exchangeArray( $fields ?? [] );
        // ...
    }

    // ...
}
```

I'm not sure how form validation and especially error and flash messages would work in this case.

**Comment by kevindees** [comment]
Hey @jdoubleu 

This is an interesting idea. I do have an unfinished feature that makes use of a hidden field `_tr_form_prefix` with what you are talking about in mind. At some point, I plan to add the prefix lookup for the request. However, I have not had time to look into all the edge cases and issue this might create.

```php
    /**
     * Prefix Field
     *
     * @param string $prefix prefix fields will be grouped under
     *
     * @return string
     */
    public static function prefixInput($prefix = 'tr')
    {
        return "<input type=\"hidden\" name=\"_tr_form_prefix\" value=\"{$prefix}\"  />";
    }
```

When I have these situations use the `tr_form()->extend('group_name')` right now.

**Comment by jdoubleu** [comment]
Okay, I'm going to try using the field groups for now.

I don't understand why exactly you want to introduce this new _hidden_ field. There are already form prefixes used by any form (i.e. `tr`). Why not use them? I could imagine, using same field names in different forms, might cause parameter pollution or at least confusion later on.

**Comment by jdoubleu** [comment]
Unfortunately, [form groups](https://typerocket.com/docs/v5/forms/#section-groups) do not properly set the error messages from the response.

What I did was to give each form on the same page a different group with `$form->setGroup('...')`. The HTTP Fields set their `$modelFieldsGroup = '...'` accordingly.

After a redirect, however, the fields do not render any error message. Upon further investigation, I noticed, that `tr_redirect_errors()` does return all the fields with their error messages **but** their names are not prefixed with the group. This has probably something to do with the Validator in the custom HTTP Field, not honoring the group or updating the error message array afterwards.

**Comment by jdoubleu** [comment]
I found a workaround which works for now, but maybe you can think of a better solution for this.

Depending on the requests, I add additional data to the response/redirect ([`->withData(['form' => 'second-form'])`](https://typerocket.com/docs/v5/redirects/#section-with-data). In the view, which renders both forms, I'm checking which form was submitted (i.e. redirected from when an error occurred) and only call `$form->useOld()->useErrors()` for the form that was submitted.
