### ISSUE TITLE
SubTabs in left

### ISSUE THREAD

**Issue by shahbaz-dev1** [TypeRocket/typerocket#24]
I was looking an option to have sub tabs in left as WordPress has admin menus in left. Its necessary in theme options for. Also it would be good if I can add tab icon as well. Appreciate your help

**Comment by kevindees** [comment]
Hey wowthemes,

I just added the ability to add icons to tabs in v3.0.16 of core. Also, I added the ability to have multiple select fields.

- https://typerocket.com/docs/v3/tabs/
- https://github.com/TypeRocket/core/releases/tag/v3.0.16

**Comment by shahbaz-dev1** [comment]
@kevindees Thanks a lot

**Comment by shahbaz-dev1** [comment]
@kevindees Please let me know if you have plan to add the feature of sub-tabs

**Comment by kevindees** [comment]
@wowthemes I think I know what you are talking about now. Yes, we plan to add that feature very soon.

**Comment by kevindees** [comment]
@wowthemes I just wanted to update you on some updates that are available for tabs now. You can put them in repeater fields. However, I'm still working on sub tabs.

[Core v3.0.23](https://github.com/TypeRocket/core/releases/tag/v3.0.23)

Also, requires an update to [NPM TypeRocket asset updates](https://typerocket.com/docs/v3/updating/#section-assets)

**Comment by kevindees** [comment]
Hey @wowthemes 

We can revisit this feature down the road if it comes up more frequently. I'm not going to add this feature for a while if I do.
