### ISSUE TITLE
[feature request] Form field placeholder accessors

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/typerocket#240]
Maybe add a placeholder property or its accessor methods to the Form's `Field` class.

Example:
```PHP
$form->text('email')
  ->setLabel("Email")
  ->setPlaceholder("john@example.com");
```

Right now, one has to use:
```PHP
$form->text('email')->setAttribute('placeholder', 'john@example.com');
```

Please note, that the `placeholder` attribute is only supported on certain input types (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attributes).

**Comment by kevindees** [comment]
Hey @jdoubleu 

This feature is coming in the next release.

Thanks,
Kevin
