### ISSUE TITLE
[feature-request] optional validation rules

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/typerocket#243]
It would be helpful to mark *all* validation rules as _optional_, meaning they should only be checked *when* the user provided a value for them. Similar to the [`required:weak`](https://typerocket.com/docs/v5/validator/#section-about-validation) rule but for all the other (built-in) rules, like `email`, `size`, etc.

I couldn't notice any difference between using:
```PHP
$rules = [ 'email' => 'required|email' ];
```
and
```PHP
$rules = [ 'email' => 'email' ];
```

Both fail, if the user didn't provide any value. While I would expect that behavior with the first rules, I don't with the second.

This is probably due to the fact, that the [`EmailValidator` uses `filter_var`](https://github.com/TypeRocket/core/blob/main/src/Utility/Validators/EmailValidator.php#L24) and thus fails when the `$value` is empty.

What I want to express is:
> A field may be empty, but if it's not it *must* pass the given rules.

## Workaround
Right now, I have to let those fields pass through the default HTTP Fields and add additional logic in the controller. This logic first checks, whether those fields are set in the request, and then manually uses another validator.

**Comment by kevindees** [comment]
Hey @jdoubleu 

This feature is coming in the next release:

```php
<?php
$fields['number'] = null;

$validator = new Validator([
    'number' => '?size:2'
], $fields, null, true);


$this->assertEquals(0, count($validator->getErrors()) );
$this->assertEquals(1, count($validator->getPasses()) );
```
