### ISSUE TITLE
Unable to find posts with given taxonomy

### ISSUE THREAD

**Issue by gogolander** [TypeRocket/typerocket#244]
Hi all!

Me and my mate are trying to do the following: register a CPT called "Contatto"; register a few taxonomies for "Contatto", let's say "Ufficio"; get all the "Contatto" posts with a given term of the Ufficio taxonomy. Both "Contatto" and "Ufficio" have both a model and a controller.
We hadn't any issue with the first two steps but getting the lists of Contatto for a given term is proving challenging for both the docs and the youtube videos seem not to enter in the details of this particular use-case.
Is it possibile to get this done using only typerocket or do we have to revert to the get_posts() function? If so, could You please give us some examples?

Thanks in advance

**Comment by kevindees** [comment]
Hey @gogolander 

What version of TypeRocket are you using? WordPress plugin or the composer install v4 or v5?

I have a patch that is about to be released that handles a taxonomy bug. It might fix the issue you are having.

https://github.com/TypeRocket/core/commit/0c63c9059985c705ec1026f1d18c39d9998c9a97

Thanks,
Kevin

**Comment by gogolander** [comment]
Hi Kevin!

We are using the open Typerocket v5 installed as mu-plugins.

Thanks

**Comment by kevindees** [comment]
@gogolander 

I just published an update with a few bug fixes.

Let me know if this works for you. Running `composer update` should do it unless you installed TypeRocket as a mu-plugin using the downloadable plugin.

https://github.com/TypeRocket/core/releases/tag/v5.0.94

Thanks,
Kevin

**Comment by gogolander** [comment]
Hi Kevin.

Ok, thanks! I'll keep You posted. Is the where() able to query using the terms too or should we use something else?

Thanks

**Comment by kevindees** [comment]
Hey @gogolander 

You can use the where clause but you might need to specify what table the where is applied to. For example,

```php
$model->where('wp_term_taxonomy.taxonomy', 'post_tag');
```

**Comment by robojuicedev** [comment]
Hey @gogolander 

Also, note I have added the following to some of the base classes for you app folder:

https://github.com/TypeRocket/typerocket/releases/tag/v5.0.18

Thanks,
Kevin

**Comment by gogolander** [comment]
Thanks, guys!

I’m really looking forward to try ti. I’ll keep You posted.

Cheers!

**Comment by gogolander** [comment]
Hey @kevindees!

We tested the new core and it works fine as described. So I'll close the issue.

Thank You so much!
