### ISSUE TITLE
Configuration in v5 Pro

### ISSUE THREAD

**Issue by lukwi** [TypeRocket/typerocket#245]
Hey Kevin,

i have problems to override the configuration in TypeRocket v5 Pro.
Documentation says i can use typerocket_env() function to override for example WP_DEBUG constant.
I call this in my function.php, but it doesn't works..
Also i want to override the extension array in config/app.php, so that the configurations doesn't loose, if i update the plugin.
In older version, i was able to copy config/app.php to to theme folder, but that doesn't work anymore.
Can you help me?

Greetings,

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

`typerocket_env()` is not designed to override PHP/WordPress constants. It is designed to provide a default value if the constant is not found.

Also, you can read more about the override system here for the config settings. 

https://typerocket.com/docs/v5/install-via-plugin/#section-create-override-folders

Thanks,
Kevin

**Comment by lukwi** [comment]
Thank you very much! I don't understand in which cases that is useful, but it doesn't matter. I've copied the whole config folder to my theme as you describe in the video and now it works :)

Greetings

Lucas
