### ISSUE TITLE
tr_form and 1-to-1 relationships in CPTs

### ISSUE THREAD

**Issue by gogolander** [TypeRocket/typerocket#247]
Hi,
in [this](https://www.youtube.com/watch?v=-NqsKtOOu0w) video, You explained how the tr_form loads data from a one-to-one relationship between a content-type and a custom resource. I'm trying to use this feature but to no avail. Is this feature still present in typerocket v5?
My models are similar to these:
```
class A extends WPPost
{
    protected $metaless = ['event'];
    public function rel()
    {
        return $this->hasOne(B::class, 'a_id');
    }
}

class B extends Model
{
    protected $resource = 'B';
    protected $fillable = [
       // all my fields...
    ];
    public function relA()
    {
        $this->hasOne(A::class, 'ID');
    }
}
```
and the code for the main form in `functions.php` file is:
```
$form = tr_form()->setGroup('rel');
        echo $form->date('opening_date')->setFormat('dd/mm/yy');
        echo $form->date('deadline_date')->setFormat('dd/mm/yy');
```
The resource entity is saved to the table and the relationship between the cpt A and B is correctly populated but the `$form` never shows the values of the entity B.
TIA

**Comment by kevindees** [comment]
Hey @gogolander 

Have you seen this video? https://www.youtube.com/watch?v=iFppxsZ09l8

Also, there is a blog post to go with it. https://typerocket.com/saving-post-type-fields-to-a-custom-database-table/

**Comment by gogolander** [comment]
Hi,
after re-watching it, I managed to track the issue down to the cast method.
Thanks
