### ISSUE TITLE
Editor unable to use search field in custom post type

### ISSUE THREAD

**Issue by lukwi** [TypeRocket/typerocket#248]
Hey Kevin,

an editor is not able to use a search field, which i have assigned to a custom post type:

echo $form->search('Thema')->setPostTypeOptions('thema');

Console says the following: 

Failed to load resource: the server responded with a status of 401 (Unauthorized)
/tr-api/search?post_type=thema&s=:1

Is there a way to enable search fields for editors?

Greetings

Lucas

**Comment by kevindees** [comment]
Hey @lukwi 

You need to update the Kernel middleware for the search field. You can use `AuthRead` which is pretty open but not public. Or, you can create your own middleware for security.

<img width="803" alt="Screen Shot 2022-02-14 at 3 26 56 PM" src="https://user-images.githubusercontent.com/348368/153941081-2caec0d6-a462-46a9-9bba-44c7d78a770c.png">

**Comment by lukwi** [comment]
Great! Thank you very much for the fast response!
