### ISSUE TITLE
Unable to set custom handler for post CPT

### ISSUE THREAD

**Issue by gogolander** [TypeRocket/typerocket#250]
Hi Kevin,

I've got a CPT called 'car' that has to interoperate with a external service. So I:

1. asked galaxy to create the model and the controller with `php galaxy make:model -c post Car`
2. decleared the CPT in my `functions.php`:
 
```php
$carCPT = tr_post_type('car', 'Cars')
    ->setHandler(\App\Controllers\CarController::class);
```

This is the `Car.php`:

```php
<?php
namespace App\Models;

use TypeRocket\Models\WPPost;

class Car extends WPPost
{
    public const POST_TYPE = 'car';
}
```

and this the `CarController.php`:

```php
<?php
namespace App\Controllers;

use App\Models\Car;
use TypeRocket\Controllers\WPPostController;

use TypeRocket\Http\Request;
use TypeRocket\Http\Response;
use TypeRocket\Models\AuthUser;

class CarController extends WPPostController
{
    protected $modelClass = Car::class;

    public function create(Request $request, Response $response, AuthUser $user) {
        // Just to let me know that this has been called
        die('called');
    }

    public function onActionSave($type, Car $car, Request $request) {
        // Just to let me know that this has been called
        die('action');
    }
}
```

All seems good and I think typerocket should do what I need here but the fact is that my methods are never actually called. Is this scenario supported by typerocket? Am I missing some steps?

Thanks

Edit: I'm running:
- WP 6.0
- PHP 8.1
- TypeRocket v5 installed in mu-plugins

**Comment by kevindees** [comment]
Hey @gogolander 

I'm not sure what is going on here. I have not done a lot of testing with PHP 8.1. However, all unit tests are passing when running them using PHP 8.1. Maybe a recent update fixed this issue for you?

**Comment by gogolander** [comment]
hi @kevindees,
I've encountered this issue suddenly and on a variety of environments: PHP v7.4, 8.0, 8.1; PHP standalone on my PC; on another PC; using the official WP container; using Lando; installing typerocket with composer, installing it unzipping it, ecc; cloning the repo or creating a brand new project, ecc..
I'm not sure if it's related to PHP given the various versions of the framework I tried but I'll retry: it couldn't hurt.
Could you please confirm that the snippet above is correct and should work as I imagine, i.e. I should see the error message? Just to rule out misconceptions about how controllers work in typerocket.
Is there any test I could run to get a better sense of what's going on and to provide You to some more infos?
Thanks

**Comment by kevindees** [comment]
@gogolander 

Can you share all of your CPT registration code? All I see is:

```php
    ->setHandler(\App\Controllers\CarController::class);
```

**Comment by kevindees** [comment]
Hey @gogolander 

I figured it out. We have a security check for running the controllers with TypeRocket that requires adding at least one custom field for the controller to run. You can bypass the check using the hook `typerocket_hook_verified`:

```php
add_filter('typerocket_hook_verified', function($verified, $context, $id) {
    if($context === 'posts' && get_post_type($id) === 'car') {
        return true;
    }

    return $verified;
}, 10, 3);
```

Also, when saving a post type the `create()` method is never called because WordPress always used the `update()` method on the post edit page.

Finally, if you do not want to add the `typerocket_hook_verified` filter you can add a hidden field and that should also get the `update()` method to get called.

```php
$carCPT = tr_post_type('car', 'Cars')
    ->setHandler(\App\Controllers\CarController::class)
    ->setMainForm(function() {
        $form = tr_form();
        $form->hidden('__triggerController');
    });
```

**Comment by gogolander** [comment]
Thank You, Kevin.
I'll try as soon as I'll be back at home.
Cheers

**Comment by gogolander** [comment]
Hi @kevindees! It works!
Thank you for the help :)

**Comment by gogolander** [comment]
Sorry to bother again, @kevindees but a thing isn't clear to me: do I have to add at least a field on **every** CPT I want to customize the controller logic or do I have to make sure that at least **one of all** my CPTs does?
Thanks

**Comment by kevindees** [comment]
@gogolander 

If you have multiple post types without custom fields I recommend using the hook instead of adding a hidden field. The system is in place for security purposes.

```php
add_filter('typerocket_hook_verified', function($verified, $context, $id) {
    $pt = get_post_type($id);
    if($context === 'posts' && in_array($pt, ['car','post','page'])) {
        return true;
    }

    return $verified;
}, 10, 3);
```
