### ISSUE TITLE
override folders to a plugin level

### ISSUE THREAD

**Issue by str** [TypeRocket/typerocket#251]
If I want to create a custom plugin, could I have "override folders"  not at a theme nor root level, but at a plugin level?

What if I have multiple plugins basedon typerocket in the same wp site?

**Comment by kevindees** [comment]
Hey @str 

This is possible by defining the overrides directory and config directory in your `wp-config.php` file. 

- https://github.com/TypeRocket/plugin/blob/main/typerocket-v5.php#L80-L89. 
- https://typerocket.com/docs/v5/install-via-plugin/#section-create-override-folders

```php
$plugin_path = '/your/plugin/path';
define('TYPEROCKET_OVERRIDE_PATH', $plugin_path);
define('TYPEROCKET_CORE_CONFIG_PATH', $plugin_path . '/config');
define('TYPEROCKET_APP_ROOT_PATH', $plugin_path);
define('TYPEROCKET_ALT_PATH', $plugin_path);
define('TYPEROCKET_AUTOLOAD_APP', [
    'prefix' => TYPEROCKET_APP_NAMESPACE . '\\',
    'folder' =>  $plugin_path . '/app/',
]);
```

However, if you are using TypeRocket Pro there is a command you can use to quickly create a TypeRocket enabled plugin.

https://typerocket.com/docs/v5/plugins-making/

Thanks,
Kevin
