### ISSUE TITLE
typerocket based plugin routes not working

### ISSUE THREAD

**Issue by str** [TypeRocket/typerocket#253]
OK, I created a new typerocket based plugin via make:plugin. I saw there was no $myPlugin/routes/public.phpso I copied the routes folder from the mu-plugins/typerocket folder.

- the route at  mu-plugins/typerocket/typerocket/routes/public.php does work great
- the route at plugins/$myPlugin/routes/public.phpdoes not work

I tested and confirm $myPlugin is active.  What am I doing wrong?

**Comment by kevindees** [comment]
@str 

https://typerocket.com/docs/v5/plugins-making/#section-core-plugin-class

Within the plugin install using `make:plugin` you can use the `routes()` method and your routes there.

**Comment by str** [comment]
I do see the plugin class with the right namespace and the routes method. I put a new route to it, but when trying to open the route in the browser, I get a 404

```php
<?php
namespace Maphpia\Om;

use TypeRocket\Core\System;
use TypeRocket\Utility\Helper;
use TypeRocketPro\Register\BasePlugin;
use Maphpia\Om\View;

class MaphpiaOmTypeRocketPlugin extends BasePlugin
{
    // ....
    
    public function init()
    {
        // if I put anything  here like a die('DEBUG') I see it
        // I did that to debug/confirm the plugin is working.
        // ...
    }
    
    public function routes()
    {
        // TODO: Add your TypeRocket route code here
        tr_route()->get()->on('hi/*', function ($arg) {
            // Will return... Hi, {url_segment}
            return 'Hi, ' . esc_html($arg);
        });
    }
    // ...
}
```

But still nothing... :(

**Comment by kevindees** [comment]
@str 

For the last line of your main plugin PHP file. the one named the same as the plugin folder. Try changing adding a priority of `9` to the `typerocket_loaded` hook.

```php
register_activation_hook( __FILE__, 'typerocket_plugin___key__');
add_action('delete_plugin', 'typerocket_plugin___key__');
add_action('typerocket_loaded', 'typerocket_plugin___key__', 9); // <-- here add 9
```

**Comment by str** [comment]
THAT DID IT!

**Comment by str** [comment]
IMHO, it would help to have the plugin internal structure as similar as  typerocket (or Laravel). If everything follows the same convention, it is easier for new devs. 

To keep the plugin routes in the plugin/routes/public.php  It would be just to replace the routes function with

```php

    public function routes()
    {
        require_once __DIR__ . '/../routes/public.php';
    }
```

**Comment by kevindees** [comment]
Hey @str 

I'll take this into account for version 6. I have several ideas for that version. The main idea is to enable embedding TypeRocket directly into a plugin and if multiple plugins have TypeRocket core embedded the latest core version will be the only one that loads. TBD
