### ISSUE TITLE
Render component from another component

### ISSUE THREAD

**Issue by milossh** [TypeRocket/typerocket#256]
I'm using Page Builder. I've created Component `Foo`, I've Builder field in it, which allows me to pick several other components, such as my also created component `Bar`. Now, is there any way to render `Bar` html in `Foo` render() method?

**Comment by kevindees** [comment]
You can use the matrix field component loop.

```php
use \TypeRocket\Elements\Fields\Matrix;

Matrix::componentsLoop($your_nested_builder_fields, [], 'builder');
```

**Comment by milossh** [comment]
Thanks!
