### ISSUE TITLE
How can i display a taxonomy term field

### ISSUE THREAD

**Issue by hymenoby** [TypeRocket/typerocket#260]
I have created a post type and a taxonomy like this: 

`
    $upperPlural = 'Projets';
    $upperSingular = 'Projet';
    $lowerSingular = 'projet';
    $pluralLower = 'projets';
    $withFront = false;

    $project = tr_post_type('Project', 'Projects');
    $project->setId('project');
    $project->setSlug('project', $withFront);
    $project->setRest('projects');
    $project->setPosition(25);
    $project->setIcon('dashicons-open-folder');
    $project->setLabels([
        'add_new'               => _x('Ajouter', 'post_type:project', 'moja'),
        'all_items'             => sprintf(_x('Tous les %s', 'post_type:project', 'moja'), $upperPlural),
        'archives'              => sprintf(_x('Archives %s', 'post_type:project', 'moja'), $upperSingular),
        'add_new_item'          => sprintf(_x('Ajouter un nouveau %s', 'post_type:project', 'moja'), $upperSingular),
        'attributes'            => sprintf(_x('Attributs %s', 'post_type:project', 'moja'), $upperSingular),
        'edit_item'             => sprintf(_x('Modifier %s', 'post_type:project', 'moja'), $upperSingular),
        'filter_items_list'     => sprintf(_x('Filtrer la liste %s %s', 'post_type:project', 'moja'), $pluralLower, $upperSingular),
        'insert_into_item'      => sprintf(_x('Insérer dans %s', 'post_type:project', 'moja'), $lowerSingular),
        'item_published'        => sprintf(_x('%s publié.', 'post_type:project', 'moja'), $upperSingular),
        'item_published_privately' => sprintf(_x('%s publié en privé.', 'moja'), $upperSingular),
        'item_updated'          => sprintf(_x('%s mis à jour.', 'post_type:project', 'moja'), $upperSingular),
        'item_reverted_to_draft' => sprintf(_x('%s rétabli en brouillon.', 'post_type:project', 'moja'), $upperSingular),
        'item_scheduled'        => sprintf(_x('%s planifié.', 'post_type:project', 'moja'), $upperSingular),
        'items_list'            => sprintf(_x('Liste %s', 'post_type:project', 'moja'), $upperPlural),
        'menu_name'             => sprintf(_x('%s',  'post_type:project:admin menu', 'moja'), $upperPlural),
        'name'                  => sprintf(_x('%s', 'post_type:project:post type general name', 'moja'), $upperPlural),
        'name_admin_bar'        => sprintf(_x('%s', 'post_type:project:ajouter nouveau depuis la barre d\'administration', 'moja'), $upperSingular),
        'items_list_navigation' => sprintf(_x('Navigation liste %s', 'post_type:project', 'moja'), $upperPlural),
        'new_item'              => sprintf(_x('Nouveau %s', 'post_type:project', 'moja'), $upperSingular),
        'not_found'             => sprintf(_x('Aucun %s trouvé', 'post_type:project', 'moja'), $pluralLower),
        'not_found_in_trash'    => sprintf(_x('Aucun %s trouvé dans la corbeille', 'post_type:project', 'moja'), $pluralLower),
        'parent_item_colon'     => sprintf(_x("Parent %s :", 'post_type:project', 'moja'), $upperPlural),
        'search_items'          => sprintf(_x('Rechercher %s', 'post_type:project', 'moja'), $upperPlural),
        'singular_name'         => sprintf(_x('%s',  'post_type:project:post type singular name', 'moja'), $upperSingular),
        'uploaded_to_this_item' => sprintf(_x('Téléchargé sur cet %s', 'post_type:project', 'moja'), $lowerSingular),
        'view_item'             => sprintf(_x('Voir %s', 'post_type:project', 'moja'), $upperSingular),
        'view_items'            => sprintf(_x('Voir %s', 'post_type:project', 'moja'), $upperPlural),
    ], 'Project');
    $project->register();

    $upperPlural = 'Catégories';
    $upperSingular = 'Catégorie';
    $lowerSingular = 'catégorie';
    $lowerPlural = 'catégories';

    $projectCategory = tr_taxonomy('Catégorie', 'Catégories');
    $projectCategory->setId('project_category');
    $projectCategory->setSlug('categorie', $withFront);
    $projectCategory->setRest('project_category');
    $projectCategory->setLabels([
        'add_new_item'               => sprintf(_x('Ajouter une nouvelle %s', 'taxonomy:project_category', 'moja'), $upperSingular),
        'add_or_remove_items'        => sprintf(_x('Ajouter ou supprimer des %s', 'taxonomy:project_category', 'moja'), $lowerPlural),
        'all_items'                  => sprintf(_x('Toutes les %s', 'taxonomy:project_category', 'moja'), $upperPlural),
        'back_to_items'              => sprintf(_x('← Retour à %s', 'taxonomy:project_category', 'moja'), $lowerPlural),
        'choose_from_most_used'      => sprintf(_x('Choisir parmi les %s les plus utilisées', 'taxonomy:project_category', 'moja'), $lowerPlural),
        'edit_item'                  => sprintf(_x('Modifier %s', 'taxonomy:project_category', 'moja'), $upperSingular),
        'name'                       => sprintf(_x('%s', 'taxonomy:project_category:taxonomy general name', 'moja'), $upperPlural),
        'menu_name'                  => sprintf(_x('%s', 'taxonomy:project_category:admin menu', 'moja'), $upperPlural),
        'new_item_name'              => sprintf(_x('Nouveau nom de %s', 'taxonomy:project_category', 'moja'), $upperSingular),
        'no_terms'                   => sprintf(_x('Aucune %s', 'taxonomy:project_category', 'moja'), $lowerPlural),
        'not_found'                  => sprintf(_x('Aucune %s trouvée.', 'taxonomy:project_category', 'moja'), $lowerPlural),
        'parent_item'                => sprintf(_x('Parent de %s', 'taxonomy:project_category', 'moja'), $upperSingular),
        'parent_item_colon'          => sprintf(_x('Parent de %s :', 'taxonomy:project_category', 'moja'), $upperSingular),
        'popular_items'              => sprintf(_x('%s populaires', 'taxonomy:project_category', 'moja'), $upperPlural),
        'search_items'               => sprintf(_x('Rechercher des %s', 'taxonomy:project_category', 'moja'), $upperPlural),
        'separate_items_with_commas' => sprintf(_x('Séparer les %s par des virgules', 'taxonomy:project_category', 'moja'), $lowerPlural),
        'singular_name'              => sprintf(_x('%s', 'taxonomy:project_category:taxonomy singular name', 'moja'), $upperSingular),
        'update_item'                => sprintf(_x('Mettre à jour %s', 'taxonomy:project_category', 'moja'), $upperSingular),
        'view_item'                  => sprintf(_x('Voir %s', 'taxonomy:project_category', 'moja'), $upperSingular),
    ], 'Catégorie');

    $projectCategory->setMainForm(function () {
        $form = tr_form();
        echo $form->image('Icon');
    });
    $projectCategory->apply($project);
    $projectCategory->register();
`

now i want to display the icon of the taxonomy in my front. 

this function `tr_term_field('Icon', 'project_category', $id)`

returns an error : 
`
Uncaught Error: Class "\App\Models\ProjectCategory" not found in 
`

**Comment by kevindees** [comment]
@hymenoby 

When adding fields to a taxonomy, you may need to have a model created for it.

https://typerocket.com/docs/v6/taxonomies/#section-forms-and-fields-example-1-publisher-with-custom-field
