### ISSUE TITLE
Deprecated dynamic property $beta

### ISSUE THREAD

**Issue by Ced-Sharp** [TypeRocket/typerocket#264]
First, I did not find where to post this issue, so I apologize if this is the wrong project for it.

In TypeRocket 6.1 (I use pro, but don't know if it matters), in the zip downloaded, the file typerocket/plugin/Updater.php is assigning a value to a new property $beta (line 43) which is not defined as a property of the class Updater. This causes a deprecation message to appear at the top of the website.

The fix is to simply define `private $beta = false;` after all the other properties in the Updater class.

**Comment by kevindees** [comment]
@Ced-Sharp, this is fixed in our upcoming patch. I'll be launching the update soon.
