### ISSUE TITLE
How to Create Rewrite Ajax in Framework?

### ISSUE THREAD

**Issue by mehrshaddarzi** [TypeRocket/typerocket#266]
Hi, thanks for your Framework.
I Have two question.

1) how to create Ajax Request similar Rewrite Ajax in this framework , not admin-ajax?
More Helper: https://www.youtube.com/watch?v=LWuLanCPoF0

2) I need full example create custom mysql table and Create Admin List table with custom Capability User in admin?

**Comment by kevindees** [comment]
Thanks for checking out TypeRocket. Unfortunately, we can not support giving full code examples for personal implementations.
