### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#27]
Hi,
is typerocket compatible with something like multilingualpress : https://multilingualpress.org/ ?
lastly i add a project where the client was exiging multilingual press, and i realize after chatting with the plugin support that i cannot use ACF or carbon fields, as they have a way to register the fields in the db that make it not compatible (they told me that there was the risk that the field in one language overwite the others etc..)
so i add to use cmb2 as it is cleaner and register the fields in the wordpress way, which is nice but lacking of features like flexible content which i was using a lot.

Is it also compatible with other multilanguage plugins like wpml and polylang ?
Thanks !

**Comment by kevindees** [comment]
Hey,

I have not used MultilingualPress before so I'm can not say if it is compatible. However, TypeRocket is design to work very well with WordPress plugins and I have not seen compatibility issues.

Also, as of version 3.0.5 (just released) I have added language support to the TypeRocket Plugins but I do not have any language translations yet. I'm open to working with someone to get translations mad. But, I can not push out the languages myself quickly.

Thanks,
Kevin
