### ISSUE TITLE
Contract repeater by default

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#30]
Is there a way to have repeater fields contracted by default
and also is there a way to have different width to the fields (in back office) or this is to do by css ?

**Comment by kevindees** [comment]
Repeaters do not have that option right now but that is a really good idea. I'll see what I can do to add it.

**Comment by kevindees** [comment]
Also, you can have fields added to row in repeaters https://typerocket.com/docs/v3/forms/#section-field-rows

```php
$form->row( $form->text('First Name'), $form->text('Last Name') );
```

**Comment by kevindees** [comment]
You can now have a repeater collapsed by default.

```php
$form->repeater('Stories')->contracted();
```

https://github.com/TypeRocket/core/releases/tag/v3.0.25
