### ISSUE TITLE
Relationship field

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#31]
Is there a way to make relationship fields like in ACF ?

**Comment by kevindees** [comment]
Hey @alexadark, 

What do you mean by relationship fields? I'm not familiar with them. What are you looking to do?

Thanks,
Kevin

**Comment by alexadark** [comment]
This is the relationship field https://www.advancedcustomfields.com/resources/relationship/
it exists also in carbon fields plugin  https://carbonfields.net/docs/fields-association/

basically with this field you can display other posts , or cpt , the user can pick them individually
it's really very usefull
i often use that instead of doing a new wp_Query , as it's more flexible for the user

**Comment by kevindees** [comment]
like this field? https://typerocket.com/docs/v3/field-types/#section-search

**Comment by alexadark** [comment]
Possibly, i have to test it :-)
