### ISSUE TITLE
Proper way to use register_activation_hook in TypeRocket

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#33]
Hi,
I've just started experimenting with TypeRocket for plugin development after I stumbled on it while search for wordpress plugin development framework and I was blown away by the cool features in the framework: MVC, routing, form, cpt, etc. 
But it seems to me that TypeRocket team promote it mainly for theme development and there are no much resources on the internet yet on getting started with TypeRocket other than the official website which has been helpful to me. At first I is used for theme dev only till i saw this [issue](https://github.com/TypeRocket/typerocket/issues/8).

In the plugin am working on I want to create some custom database tables on plugin activation, outside TypeRocket I know how to do that but what is the best approach to do it with TypeRocket?

Thanks in advance.

**Comment by kevindees** [comment]
Hey @chibexme,

Thanks for much for the kind words. We are a kinda unknown system so Google will not turn up a lot for us right now outside of our site. I'm working on content for plugin developers here soon actually so I'll let you know when that content gets released on how to use TypeRocket as in a plugin.

Right now we do not have a system for creating tables. We only have an ORM/Model system in place to work with existing tables. However, this is a feature we are working on for version 3.1. For now I you will need to use WP core to build up the initial tables.

https://codex.wordpress.org/Creating_Tables_with_Plugins

Thanks,
Kevin

**Comment by chibexme** [comment]
Hi @kevindees,

Thanks for your quick response. Have done it the wordpress way, will be looking forward for the new content you intend to make available for plugin development.

Thanks.

**Comment by kevindees** [comment]
We now have new installation documentation for those using TypeRocket in a plugin:

https://typerocket.com/docs/v3/installation/#section-plugin-installation
