### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#35]
are all updates important to be done (is there security ones for ex) ?
because if i use typerocket to build a commercial theme or plugin, i will do the updates, but if i use it for a client website that i sill not maintain after, then the updates will not be done....

**Comment by kevindees** [comment]
Hey Alex,

We do put in security updates but I have not added any in quite a while since we have not seen any lately. However, getting updates is an easy as using Composer running `composer update`.
