### ISSUE TITLE
Removing archive from cpt

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#36]
Hello,
i need to remove the archive from cpt,
so i have written that 
```
$story = tr_post_type( 'Story', 'Stories' );
$story->setId( 'stories' );
$story->setIcon( 'newspaper-o' );
$story->setArgument( 'supports', [ 'title', 'editor', 'thumbnail' ] );
$story->setArgument( 'has_archive', false );
```
but it doesn't work

**Comment by kevindees** [comment]
Hey,

Did you flush your WordPress permalinks?

Also, this might be helpful but it also disables the single pages for post types as well as the archive page: https://typerocket.com/docs/v3/post-types/#section-setting-admin-only

Thanks,
Kevin

**Comment by alexadark** [comment]
I have flushed the permalinks and the archive stills there
i can't use second solution as i need the single post type to be displayed

**Comment by alexadark** [comment]
I have noticed that the setSlig doesn't work neither
and this one : $story->setArchivePostsPerPage(-1); give me an error
https://cl.ly/lwi0

**Comment by kevindees** [comment]
Hey,

Did you flush your WordPress permalinks when changing the slug? Also, if you are using making a PT in your plugin try wrapping your code in the `typerocket_loaded` hook. That might be the problem. If not I'll need a code example what what you are doing.

https://typerocket.com/docs/v3/wordpress-hooks/#section-core-loaded

**Comment by kevindees** [comment]
I just found this. It looks like what you want to do can not be configured from a post type itself.

https://wordpress.stackexchange.com/questions/72209/custom-post-type-with-archive-page-but-no-detail-page

**Comment by alexadark** [comment]
Yes now with the hook it works
what i wanted is no archive not the oposite
so now it works like that 
```$story->setArgument( 'has_archive', false );``` but with the typerocket_loaded hook
