### ISSUE TITLE
Issues with Tab and Admin Menu Icon

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#38]
Hi,

I created admin page tr_page() function, added it to the admin and specified an icon but the icon did not show. Even TypeRocket Dev plugin icon is not showing as well.

Secondly, I created tabs with tr_tabs() function in my options page but it seem like the tab is not being format with CSS on rendering. When I use `$tabs->render( 'box' );` it displays well but I want to use tabs that appears at the top not the ones that appears by the side.

Please any help in correcting this is appreciated.

**Comment by kevindees** [comment]
Hi @chibexme,

How are you installing TypeRocket. If you are using it in a plugin you may need to change the asset paths to the CSS and fonts typerocket loads.

Similar question can be found here with solution:

https://github.com/TypeRocket/typerocket/issues/26#issuecomment-317233242

**Comment by chibexme** [comment]
@kevindees, I'm using it as plugin. The reference link you gave helped and its now working. Thank you.

**Comment by kevindees** [comment]
Just added: https://typerocket.com/docs/v3/installation/#section-plugin-installation
