### ISSUE TITLE
Displaying Table Inside Tab

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#39]
Hi,

I want to display table inside tab, please how can I achieve that?

**Comment by kevindees** [comment]
Hi @chibexme 

I have not tried to achieve this myself but maybe try using the callback method to add content to the tab and add the table in the callback:

https://typerocket.com/docs/v3/tabs/#section-tab-callback-v3-0-24

**Comment by chibexme** [comment]
@kevindees, it worked. 

This is how I used it:

`$table = tr_tables();
$stages = function() use ($table) {
    $table->render();
};

$tabs = tr_tabs();
$tabs->addTab('Stages', $stages, 'road');
$tabs->render();`

Thanks so much.
