### ISSUE TITLE
Displaying custom database table data using tr_tables() function

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#40]
Hi, 

I want to display my custom database table data using `tr_tables()` function but I can't get it working.

Database table name: wp_amln_stage

Here is my model:

> namespace App\Models;
use \TypeRocket\Models\Model;
class Stage extends Model
{
    protected $resource = 'amln_stage';
}

Used Like this:

> $table = tr_tables(25, \App\Models\Stage::class);
$table->setColumns('name', [
    'name' => [
        'sort' => true,
        'label' => 'Name',
        'actions' => ['edit', 'view', 'delete']
    ],
    'id' => [
       'sort' => true,
       'label' => 'ID'
    ]
]);
$table->render();

but the data is not displaying. Please what should I do? am using TypeRocket as plugin.

**Comment by kevindees** [comment]
What does your model class look like and table schema?

**Comment by kevindees** [comment]
Sorry, I see your model class. I just need the table schema.

**Comment by chibexme** [comment]
`$table = tr_tables(25, \App\Models\Stage::class); or $table = tr_tables();`
displays the database data from 'amln_stage' table on the below page:
> resources/pages/stages/index.php

but I want to display it on this page:
> resources/pages/options/index.php

using `$table = tr_tables(25, \App\Models\Stage::class);`

and it shows:

> Fatal error: Call to a member function findAll() on null in C:\xampp\htdocs\plugin-projects\aml-network\vendor\typerocket\core\src\Elements\Tables.php on line 167

**Comment by kevindees** [comment]
I think I have the docs wrong for this piece. Try this:

```php
$table = tr_tables(25, new \App\Models\Stage);
```

If you are changing pages you may need to use the `setPage()` method as well. Here is the method in the source code:

```php
/**
 * Set the page the table is connected to.
 *
 * @param \TypeRocket\Register\Page $page
 *
 * @return $this
 */
public function setPage( Page $page) {
    $this->page = $page;
    return $this;
}
```

**Comment by chibexme** [comment]
@kevindees, Thanks it works.
