### ISSUE TITLE
How to install TypeRocket with Docker?

### ISSUE THREAD

**Issue by jevgen** [TypeRocket/typerocket#41]
This is a question. I can figure out how to install wordpress and work on some theme or plugin development with Docker. But I can't figure out how can I install TypeRocket in Docker workflow. 
Should I use Composer image? But how will I link that to my wordpress working project directory in TypeRocket case?

**Comment by kevindees** [comment]
Hey,

I have not spent a lot of time working with docker containers and compose files specifically for WP and composer setups. If you are not an expert at composer, I would recommend simply installing composer on your local development machine OSX or PC and using it from there.

Composer is really just used as a way to download files so you do not need it installed on your docker setup unless you are using docker in a production environment where you need automated deploys working.

Thanks,
Kevin

**Comment by jevgen** [comment]
I am trying to use Docker to satisfy TypeRocket requirement for PDO in php, since MacOSX php does not seem to have it.

**Comment by kevindees** [comment]
Hey @jevgen 

If all you want is PDO it might be worth installing a newer version og PHP on your mac if it doesn't not break any of your other development. WordPress works on PHP 7.0 and PHP 5.6

https://php-osx.liip.ch/

However, you do not need PDO to use composer to install TypeRocket. You can use composer on your Mac to install TypeRocket. Then, Docker will take over after the install and enable PDO.

Thanks,
Kevin

**Comment by jevgen** [comment]
Yup, I came to this workflow yesterday. Thank you for Swiss PHP link, invaluable.
