### ISSUE TITLE
Questions on tr_tables() function and Tab

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#42]
Hi, I have some questions about tr_tables() function:
1) How can I include Bulk Action select option to tr_tables() like WP table?
2) How do I include Checkbox as the first column that will work with Bulk Action like WP table?
3) How do I display data from multiple database tables using model in the tr_tables()?
4) How do I make a tab selected by default as the page loads and not the first tab?

Thanks in advance.

**Comment by kevindees** [comment]
Hey,

1 - 2. For `tr_tables()` I have a few updates that have just been released https://github.com/TypeRocket/core/releases/tag/v3.0.26. You need to update core to get them. run `composer update`. This release allows for creating your own bulk actions. You need to code your table and use some custom JS to make it work be the elements are now available to make it possible.

3. I'm not sure about using multiple databases though we do allow for joins so I'm sure it is possible. It is just not documented or tested. 

4. We do not have this feature currently but I am update the tabs API for version TypeRocket 3.1.

**Comment by chibexme** [comment]
@kevindees, thanks for your response.

> I'm not sure about using multiple databases though we do allow for joins so I'm sure it is possible. It is just not documented or tested.

Can I get code sample for table join or should I create and use database View object?

> We do not have this feature currently but I am update the tabs API for version TypeRocket 3.1.

Ok. I will try doing that with javascript. When are we expecting TypeRocket 3.1?

Thanks once again.

**Comment by kevindees** [comment]
For the join options you can hook into the query builder by accessing the query builder used by the ORM.

```php
$model = new \App\Models\Post();
$query = $model->getQuery()
```

From there you can use the query docs to do what you need https://typerocket.com/docs/v3/query-builder/#section-joins

Version 3.1 is going to have a number of updates. I'm not sure on the date yet but should be in the next 4-6 months. Lots of interesting fields coming in 3.1 if I can pull them off.

Thanks,
Kevin
