### ISSUE TITLE
Can't make pagebuilder Work

### ISSUE THREAD

**Issue by chemocool** [TypeRocket/typerocket#44]
Hi, i can't seem to make the page builder work.

I can see the switch to switch between Builder & Standard Editor.

I also have the button for "Add new" with the dropdown of component (i can see new ones that i added, in the dropdown).

But when i click on the "content component" in the dropdown, it doesn't do anything.

Any idea ?

**Comment by kevindees** [comment]
Hi,

Can you send over the code you are using? This will be very helpful. Also, are you using friendly URLs?

Thanks,
Kevin.

**Comment by chemocool** [comment]
Hi Kevin, thanks for the fast answer.

Basically, i followed the instructions here:

https://typerocket.com/docs/v3/builder/

Made the modification to page.php and created standard.php, but of course that has to do with the rendering, not the admin part.

Is there another document on how to configure it to make it work ?

The wordpress instance is on a local server.

**Comment by kevindees** [comment]
where did you install typerocket? in your theme? Also, where did you place your components?

**Comment by chemocool** [comment]
I created a theme using underscore (https://underscores.me/), installed typerocket inside that theme

directory is as follow:
wp-content/themes/underscore/typerocket

**Comment by kevindees** [comment]
where did you place your components relative to wp-content?

**Comment by chemocool** [comment]
wp-content/themes/underscore/typerocket/wordpress/assets/components/builder/content.png

wp-content/themes/underscore/typerocket/resources/components/builder/content.php

wp-content/themes/underscore/typerocket/resources/visuals/builder/content.php

**Comment by chemocool** [comment]
Actually, i'm just trying to make it work with the default component, before creating new ones

**Comment by kevindees** [comment]
what is the code in the component for admin with the fields? You must be getting a 505 error somewhere. you should be able to check you browsers dev tools to see what the http error is when trying to load in the component.

**Comment by chemocool** [comment]
i have a 404 on "http://localhost/tr_builder_api/v1/builder/content/builder"

Initiated by "load-script.php"

**Comment by chemocool** [comment]
the component is the same that was created when i fetched typerocket using composer

**Comment by kevindees** [comment]
Its seem then that your permalinks are broken. what is the permalink setting you are using? You should use anything but the first option in the permalink list of options.

**Comment by kevindees** [comment]
http://www.wpbeginner.com/wp-tutorials/seo-friendly-url-structure-for-wordpress/

**Comment by chemocool** [comment]
I am using: http://localhost/wordpress/%category%/%postname%/

The custom one

**Comment by kevindees** [comment]
what happens if you go to this url? http://localhost/wordpress/tr_builder_api/v1/builder/content/builder

**Comment by chemocool** [comment]
I can see a form with a input[text] and a textarea named content component

**Comment by chemocool** [comment]
I guess i need to install wordpress in the root of the webserver, right ?

**Comment by kevindees** [comment]
ok, i think you need to remove the /wordpress from your permalink structure. This might be a bug in TypeRocket I need to work out if you add a prefix to your permalinks. is that a big deal for this site?

**Comment by chemocool** [comment]
nope, im just basically testing out typerocket, i was just sad that this specific feature didnt work for me

ill place my wordpress instance in the root

**Comment by chemocool** [comment]
It worked !

Glad I could help find a small bug ;)

Thanks for your help, really appreciated :)

**Comment by kevindees** [comment]
Bug will get fixed here soon so you can use your normal workflow

**Comment by chemocool** [comment]
Great, keep up the good work. That framework is really cool.

**Comment by kevindees** [comment]
https://github.com/TypeRocket/typerocket/releases/tag/v3.0.8

**Comment by ntnhan0605** [comment]
> It worked !
> 
> Glad I could help find a small bug ;)
> 
> Thanks for your help, really appreciated :)

How can you fix issue? Can you tell me.

**Comment by kevindees** [comment]
@ntnhan0605 

Is your version of TypeTocket up to date?  Also, have you flushed your permalinks?

- update https://typerocket.com/docs/v4/updating/
- flush https://typerocket.com/flushing-permalinks-in-wordpress/


Thanks,
Kevin

**Comment by ntnhan0605** [comment]
> @ntnhan0605
> 
> Is your version of TypeTocket up to date? Also, have you flushed your permalinks?
> 
> * update https://typerocket.com/docs/v4/updating/
> * flush https://typerocket.com/flushing-permalinks-in-wordpress/
> 
> Thanks,
> Kevin
I found the issue
\wp-content\themes\Medicare Theme\typerocket\wordpress\assets\typerocket\js\core.js
The link request tr_builder_api wrong. 
Thanks.
Can I install new version TYPEROCKET in old version WORDPRESS? Because my server isn't updated new version php. Current php version : 5.6.34

**Comment by kevindees** [comment]
@ntnhan0605, unfortunately, php 5.6 limits you to Typerocket v3.

Can you post the full URL that is not working in v3?

**Comment by kevindees** [comment]
@ntnhan0605 

Also, be sure you have v3 of TypeRocket up to date.

**Comment by ntnhan0605** [comment]
> @ntnhan0605, unfortunately, php 5.6 limits you to Typerocket v3.
> 
> Can you post the full URL that is not working in v3?
I decide to update my server & wordpress, so I'll use Typerocket v4.
And I test on my xampp php 7.3 first.
