### ISSUE TITLE
Theme Options

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#45]
I'm trying to set theme options and i'm a bit lost
i followed the instructions from the doc (but from inside a plugin), and this is what happens
first if i copy the admin file, i don't know how but even if i don't call the file the code is running.
then if i let it as it is i have a first error : https://cl.ly/m5EE
so i put a name instead of $this-> getName()
then new error that seems to be due to the open and close
https://cl.ly/m5EE
so if i remove them (but then the save doesn't work...i don't know if there is more doc on how to use the submit / save field, i'm a bit lost with that too)
Then they appear in the options, but very messed up : https://cl.ly/m5EE
....

Other questions:
-how can i have the options page in another place, for ex directly in the back office menu, or as i am using the genesis framework, inside the theme settings of genesis.

-How work the submit / save field ?

-Checkboxes, i tried to have default false but it doesn't work, the box stayed checked
`echo $form->checkbox('Company Open')->setText('Company open for business')->setLabel(false)->setSetting('default', false);`

**Comment by kevindees** [comment]
Hey @alexadark 

What is the full code you are using to for the theme options including the filters for `tr_theme_options_page` and `tr_theme_options_name `.

Also, you can add your own custom admin pages using the https://typerocket.com/docs/v3/admin-pages/ but you will need to know a little about using MVC and the best way to store data from a WP standpoint.

Thanks,
Kevin

**Comment by alexadark** [comment]
Hi,
this the code for the filter, they are in the root file of the plugin
```

add_filter('tr_theme_options_page', function() {
	return WST_DIR . '/inc/theme-options.php';
});

add_filter('tr_theme_options_name', function() {
	return 'my_theme_options';
});
```
for the rest of the code, i just copied the admin.php as you said in the doc
 I looked at this  https://typerocket.com/docs/v3/admin-pages/ but i'm lost

Can i just overwrite the admin.php directly where it is ?

This is the kind of things where we need video tutorials i think

**Comment by alexadark** [comment]
Ooooh, i just saw my mistake : i was already including the options files with an include_once
now it works.
But yes an advanced tutorial on admin pages with MVC would be great !
And also an explanation on how work the submit button etc...
perhaps i have missed something in the doc

**Comment by kevindees** [comment]
You can look into the admin pages and MVC stuff here:

https://typerocket.com/docs/v3/admin-pages/
https://typerocket.com/docs/v3/custom-resources/
