### ISSUE TITLE
Removing editor on pages from a custom field

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#46]
HI,
i need to remove the editor from pages which have a checkbox cf checked
```
add_action( 'wp', function(){
	if(tr_posts_field('builder_page')){
		remove_post_type_support( 'page', 'editor' );
	}
	
}, 99 );
```
Doesn't work
Typerocket is inside a plugin, and this is inside my child theme
if i write this in the plugin even without conditions it doesn't work

in the theme i have var_dump the cf, and it's null, the cf works, as it also add a body class to the page, and that works...
i think it's perhaps a question of hooks order, but i don't find the solution

**Comment by kevindees** [comment]
You might need to pass in the ID of the post type when calling `tr_posts_field('builder_page', $post_id)` since you are not in the loop.
