### ISSUE TITLE
Making tabs translatable

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#48]
How can i write the translation functions in tabs
for ex here 
```
tr_tabs()->addTab ('Content', $content)
         ->addTab( 'Settings', $settings )->render();
```
i need to make translatable content and settings, for fields i use setLabel for that, but here it doesn't work

Also i'm making a builder and i need to have the strings of the title translatable, but if i write it like that ```<h1><?php _e( 'Content Component', PLUGIN_NAME ); ?></h1>``` it messed up everything

**Comment by kevindees** [comment]
For translation when adding a tab just pass an array as the first argument.

```php
$defaults = [
        'title'    => false, // translate the title
        'id'       => false,
        'icon'       => false,
        'content'  => '',
        'callback' => false
];
tr_tabs()->addTab($defaults);
```

Also for repeaters and other fields see https://github.com/TypeRocket/typerocket/issues/43

**Comment by alexadark** [comment]
I don't understand very well ...
here i need to make translatable the words 'Content' and 'Settings'
```
tr_tabs()->setForm( $form )->bindCallbacks()
         ->addTab( 'Content', $content )
         ->addTab( 'Settings', $settings )
         ->uidTabs()// Make all tab IDs unique
         ->render();
```
and also the module name <h1>Content Component</h1>

For field names i have already found how to use label :-)

**Comment by kevindees** [comment]
```php
$settings = [
    'title'    => __('Content'), // translate the title
    'id'       => 'content', // ID of the tab
    'content'  => $content
];
tr_tabs()
    ->setForm( $form )
    ->bindCallbacks()
    ->addTab( $settings )
```

**Comment by alexadark** [comment]
Thanks, and have you a solution for the module name ?

**Comment by alexadark** [comment]
The solution for the tabs doesn't work for me, it messed up the builder
I have tried like that
```
tr_tabs()->setForm( $form )->bindCallbacks()
         ->addTab( array(
	         'title'    => __('Content'), // translate the title
	         'id'       => 'content', // ID of the tab
	         'content'  => $content
         ))
         ->addTab( 'Settings', $settings )
         ->uidTabs()// Make all tab IDs unique
         ->render();
```

and also having it in a var
