### ISSUE TITLE
Conditional fields

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#49]
Is it possible to make a field conditional ?
for if field 1 is checked, then display field 2

**Comment by kevindees** [comment]
We do not have this feature yet but are working on it. You will need to use standard JS to achieve what you are wanting to do.

**Comment by kevindees** [comment]
See https://github.com/TypeRocket/typerocket/issues/21

**Comment by alexadark** [comment]
Thanks
yes it would be a great feature

**Comment by alvarosaco** [comment]
What about this currently?
