### ISSUE TITLE
Notice & warning on metabox/ post type

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#5]
Hi, I use TypeRocket 2.0.9 along with WP 4.2.4 with WP_DEBUG set to true: https://gist.github.com/javasworks/2dd072b6512bec7dd084

I'm not sure, whether it is from my code or from Typerocket. (and I'm sorry for too much editing on this issue)

Thanks,
Bagus

**Comment by javasworks** [comment]
Oh im really sorry :(
I just read the https://typerocket.com/docs/ and forgot the https://typerocket.com/tutorials/

Thanks Kevin, for the tutorials section :)

**Comment by kevindees** [comment]
Hey, Thanks for letting me know about this bug. I believe this was happening because of an undefined `$post` variable in the dashboard support feature.

Let me know if this version fixes your problem: [2.0.10](https://github.com/TypeRocket/typerocket/releases/tag/v2.0.10)

Thanks again,
Kevin

**Comment by ghost** [comment]
Hi, 
The 2.0.10 fixes the problem :D :+1: 

Thanks a lot Kevin, for great response on issues, and for helping :)

**Comment by kevindees** [comment]
Not a problem :) If you find any more bugs I'd love to know about them. I really want to make theming WordPress fun for you.

Thanks for trying TypeRocket,
Kevin
