### ISSUE TITLE
Creating and Registering Shortcodes in TypeRocket

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#51]
Hi everyone,

How can I create and register shortcodes in Typerocket?

Am using TypeRocket as plugin.

**Comment by kevindees** [comment]
TypeRocket does not offer a shortcode API. You will need to use WordPress core to do that.

https://codex.wordpress.org/Shortcode_API

**Comment by chibexme** [comment]
@kevindees thanks for your reply. 

Based on you own recommendation, which is the best folder to place shortcode files in typerocket?

**Comment by kevindees** [comment]
It depends on the number of shortcodes you are adding.

I would just make a `shortcodes` folder inside the root of the plugin you created (not typerocket). And create unique files for each shortcode and then include those files from the main plugin file. This should be the same place you included typerocket into your plugin.

**Comment by chibexme** [comment]
Cool. Thanks
