### ISSUE TITLE
having fields from builder module in reusable variables

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#52]
I am doing a builder and i will reuse certain fields in most of modules
for example class.
so i wanted to have a file that i include in the component file where i assign these fields to a variable in order to reuse them .
But it seems that this variables take the same value, when of course each module will have a different class for ex.
how can i accomplish that ?

**Comment by kevindees** [comment]
Can you post some sample code of that you are trying to do?

**Comment by alexadark** [comment]
i have several components on my builder and there is lot of fields that will be used in all the components
for ex 
`
	echo $form->text( 'Class' )
	          ->setLabel( __( 'Class', PLUGIN_NAME ) );` to allow people to have a custom class in order to style the component
So instead of rewriting them in each component i want to have them in a file as vars
like that
`$class = $form->text( 'Class' )
	          ->setLabel( __( 'Class', PLUGIN_NAME ) );`

and then in the component file, i include this file
and write `echo $class`

But it doesn't work, my fields take the same values, so if i have 2 components in a page that share this field i cannot have different values

If it's not possible i will copy paste the fields, but it should be a way
also if i want to modify a field i have to modify it in every component which is annoying

**Comment by kevindees** [comment]
Whats does your full backend component code look like? In the mean time you might try:

```php
$class = clone $form->text( 'Class' ) ->setLabel( __( 'Class', PLUGIN_NAME ) );
```
