### ISSUE TITLE
Custom Wordpress Login with TypeRocket

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#55]
Hi, I want to know if TypeRocket has API for Wordpress Login or should I use default wordpress login API?

am using TypeRocket as plugin.

**Comment by kevindees** [comment]
Technically you can use the MVC pattern in TypeRocket to create your own login system but I recommend just using the WP login API.

**Comment by chibexme** [comment]
Ok. Using WP API now. Thanks.
