### ISSUE TITLE
Front-end Views not loading my theme

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#56]
Hi, am using `tr_form()` on the front end to create custom registration form, the form submits to custom route which maps to a Controller method. After validation I use the `tr_view()` to call custom view page to display success or error message, the page displays the message only without been wrapped in my theme.

In the admin dashboard things works fine, how can I load my theme inside custom view page from the front-end?

And secondly, how can I handle file upload in TypeRocket from the front end or it handled automatically?

Note: I load my form through custom shortcode.

**Comment by kevindees** [comment]
Hey @chibexme 

1. To get the rest of your theme on the front-end you need to template the view file in the same way you would for a theme template and use the standard boilerplate get_header() and get_footer() code to load up your design.

2. We do not have a uploads field at this point but you can create your own custom fields https://typerocket.com/docs/v3/custom-fields/ and then maybe use a drag and drop custom JS with it.

- Vanilla JS - https://www.youtube.com/watch?v=hqSlVvKvvjQ
- JS Plugin Dropzone - http://www.dropzonejs.com/

I do not recommend adding the uploaded files to the media library for custom uploaded images as they are typically not reused. But if you wanted to do that maybe try https://codex.wordpress.org/Function_Reference/media_sideload_image

Thanks,
Kevin

**Comment by chibexme** [comment]
Ok, thanks. Have sorted things out.
