### ISSUE TITLE
builder modules in different plugins

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#57]
Hi,
i'm building a plugin with typerocket inside, i want to have certains modules in another plugin in order to make additional sales
how can i do that ? and do i need to have typerocket inside the additional plugins

**Comment by kevindees** [comment]
Hey @alexadark 

You can do what you are asking but it would require know a little about PHP autoloading and exploring the deeper part of the framework through the source code. TypeRocket was not designed to do what you are asking specifically.

However, to answer your question you only need to have TypeRocket installed in one place/plugin.

To use TypeRocket in other plugins use the `typerocket_loaded` hook like before. 

Thanks,
Kevin

**Comment by alexadark** [comment]
Ok, as i am not very advanced in back end dev, will you post a topic in the doc on about to do that.
I need to do that before the end of the year i think
if not i will have to find help
