### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by bebaps** [TypeRocket/typerocket#58]
Just reading through the documentation and this section has a few typos https://typerocket.com/docs/v3/post-types/#section-forms-and-fields.

<img width="783" alt="screen shot 2017-08-30 at 1 54 59 pm" src="https://user-images.githubusercontent.com/5995907/29894753-5fc17094-8d8b-11e7-851a-a435103fd37f.png">

For example, providing a method of `$book->setTitleFrom();` when it should be `$book->setTitleForm();` (From vs Form).

If someone copies that from the documentation they will get an error.

**Comment by kevindees** [comment]
Thanks for the heads up. This is fix now :)
