### ISSUE TITLE
tr_tables() checkboxes with search form issue

### ISSUE THREAD

**Issue by chibexme** [TypeRocket/typerocket#59]
Hi,
Selected checkboxes in tr_tables() function added with $table->addCheckboxes() does not submit to server because search form tag does not enclose the rendered table.

Please can this be corrected ASAP?

Thanks.

**Comment by kevindees** [comment]
This feature is now in version 3.0.35 of core using the method on the table object `formWrapTable()`. You will need to run composer update.

**Comment by chibexme** [comment]
Thanks.
