### ISSUE TITLE
Allowing typerocket to be installed as a separate Wordpress plugin 

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#61]
Hello,

Instead of having to bundle typerocket with every Wordpress plugin I write, It would be great to be able to install it as a separate plugin.

As far as I understand it, a plugin A that I want to install and activate in a Wordpress instance doesn't need to bundle the typerocket library again if this Wordpress instance already contains another plugin B that already bundled the typerocket library (see issue #57). 

However, I can never be sure that plugin A and B will be installed at the same time in this Wordpress instance, therefore I end up bundling the typerocket library in both plugins. 

The advantages of this "typerocket as a plugin approach" are in my opinion: 

(1) Smaller size of plugins that rely on the typerocket library

(2) The separate typerocket plugin could profit from the auto update checker/installation functionality that Wordpress offers. It would therefore make the plugin developer work a little bit less. :-)

I had a first look at the source code of the typerocket and typerocket-core projects and it seems that making typerocket a plugin in it's own right is possible. It would be great if you could tell me if I'm on the right track here since I haven't put this idea into practice yet:

(1) Integrate the typerocket core js and css assets with the typerocket/typerocket-core project. Currently they are found in the  typerocket/typerocket project.

(2) Create a file typerocket-core.php in the typerocket/typerocket project with an appropriate file header (see: https://codex.wordpress.org/File_Header)

(3) Upload the plugin to the official Wordpress plugin directory. 

If I then want to develop a plugin which relies on this typerocket plugin I would have to provide the following: 

(1) Configuration files currently similar to the one currently residing in the config folder of the typerocket/typerocket project

(2) The same bootstrap code as in the init.php file of the typerocket/typerocket project with the correct paths to the typerocket-plugin

(3) Manually require the helpers.php file from the new typerocket-plugin.

With best regards, Matthias

**Comment by kevindees** [comment]
Hey @meinbrodt 

What you are talking about seems like it would be very possible. Normally, you can just make use of the `typerocket_loaded` [hook](https://typerocket.com/docs/v3/wordpress-hooks/#section-core-loaded) from the other plugins when including `typerocket/typerocket`.  However, you are talking about loading the `typerocket/typerocket-core` and I have not tried that myself.

It would be nice to know if your idea works.

You can really install TypeRocket just about anywhere you like with the proper configuration. As you pointed out just be sure the TypeRocket core assets are exposed to the public.

Thanks,
Kevin
