### ISSUE TITLE
Not able to set the default value of Textarea

### ISSUE THREAD

**Issue by shahbaz-dev1** [TypeRocket/typerocket#62]
I am stuck with settings up default value of a field type textarea. I have tried to dig up the code and documentation but didn't find any solution. Can you please guide me to do that. I tried to achieve it in a way `$form->textarea('My Textarea')->setSetting('default', 'my default value');` but not happened.

**Comment by kevindees** [comment]
Hey @wowthemes 

I'm not sure what is going on with this. Try using the `setDefault ` method. You might need to update your version of core using `composer update`.

```php
$form->textarea('My Textarea')->setDefault('my default value');
```
