### ISSUE TITLE
post type select

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#63]
Hi is there a way to have all the available post types ,(or taxonomies)
to allow the user to choose for a search field
or to make a component with a loop to choose the last items of the choosen post type

**Comment by kevindees** [comment]
Hey @alexadark 

For post types you should be able to use the key word `any` like so `$form->search('Search')->setPostType('any');`. However, for taxonomies I have not gotten that far. IF you are interested you can create your own custom fields to do what you are asking.

https://typerocket.com/docs/v3/custom-fields/

Maybe take the code from the built-in search field as it is and create your own version for now?

Thanks,
Kevin
