### ISSUE TITLE
Grouping Fields

### ISSUE THREAD

**Issue by cliftonc0613** [TypeRocket/typerocket#64]
@kevindees,

I am trying to create a Group of fields that have 2 editors side by side in the admin. I think that it is best to us the groups but I could be wrong about how to go about this. What are your suggestions Below is a video of what Im trying to accomplish with code and an image.

```
<h1>Content - Two Columns</h1>
<?php
$form = tr_form();
$formGroup = $form->getGroup();

$fieldFirst = new \TypeRocket\Elements\Fields\Text(
	'First',
	$form
);

$fieldLast = new \TypeRocket\Elements\Fields\Text(
	'Last',
	$form
);

$fieldLast->setGroup( $formGroup . '.name' );
$fieldLast->setGroup( $formGroup . '.name' );

$group = $field->getGroup();
?>
```

`Catchable fatal error: Argument 2 passed to TypeRocket\Elements\Fields\Field::__construct() must be of the type array, object given, called in /Users/cliftoncanady/Sites/typerocket-demo/wp-content/themes/ctwd-starter/typerocket/resources/components/builder/two-column.php on line 9 and defined in /Users/cliftoncanady/Sites/typerocket-demo/wp-content/themes/ctwd-starter/typerocket/vendor/typerocket/core/src/Elements/Fields/Field.php on line 32`

![two-column](https://user-images.githubusercontent.com/1175246/30997982-6a08b376-a499-11e7-80b4-9acebcdfd648.png)

**Comment by kevindees** [comment]
Hey @cliftonc0613 this is now fixed. It was a bug in the custom field setup that deferred from the docs. Rum `composer update` to get core version 3.0.44 with the fix.

Thanks,
Kevin

**Comment by cliftonc0613** [comment]
@kevindees thanks buddy!
