### ISSUE TITLE
Layout With Columns and Tabs

### ISSUE THREAD

**Issue by cliftonc0613** [TypeRocket/typerocket#66]
@kevindees,

I was wondering in your option what is the best way to create a layout in a custom  plugin option page that looks like the one below. This layout was done with Advanced Custom Fields and I wanna do it with Typerocket.

Thanks Clifton

![screen shot 2017-10-17 at 3 28 45 pm](https://user-images.githubusercontent.com/1175246/31685284-5dd539f6-b350-11e7-824a-c81ab637a016.png)

**Comment by kevindees** [comment]
Hey @cliftonc0613 

You can get the layout rows using the `row` method on the form class. Is this maybe what you are looking for?

https://typerocket.com/docs/v3/forms/#section-field-rows

```php
$form->row( $form->text('First Name'), $form->text('Last Name') );
```

**Comment by cliftonc0613** [comment]
@kevindees ok cool. Thanks Let me try this and see if it work like i want
