### ISSUE TITLE
Featured image on custom post types

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#67]
Hi,
there is no featured image field when I create a cpt with typerocket
How to have one, I don't see anything in the doc about that
Or is the only way to create an image cf

**Comment by chibexme** [comment]
@Alexadark, you can add featured image to custom post type with below sample:

```php
$book = tr_post_type('Book', 'My Books');
$book->setArgument('supports', ['thumbnail'] );
```

**Comment by alexadark** [comment]
I think that should be in the docs, i didn't find it

**Comment by chibexme** [comment]
Am guessing that including everything about typerocket and wordpress dev in the docs will make it bulky that maybe the reason they left somethings out.

My suggestion will be that the docs should focus more on typerocket and go in-dept then give references to related wordpress codex for more details on general wordpress development (theme or plugin).

You can find more wordpress CPT supports parameters at this [codex link](https://codex.wordpress.org/Function_Reference/post_type_supports).
