### ISSUE TITLE
Google maps iframes doesn't work in text editor

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#68]
I have tried to add the wpEditor and the problems remains the same

**Comment by kevindees** [comment]
Hey @alexadark 

What part of the iframe is not working? Front-end or admin... What role is the user adding it... I'll need more details to help debug your problem.

Thanks,
Kevin

**Comment by alexadark** [comment]
Now it works with the apply filters that you indicated me in the shortcodes issues, but as i add wp_kses_post i add this function also : https://gist.github.com/bjorn2404/8afe35383a29d2dd1135ae0a39dc018c
to allow iframes
