### ISSUE TITLE
Shortcodes 

### ISSUE THREAD

**Issue by alexadark** [TypeRocket/typerocket#69]
How can i activate shortcodes in the text editor ?
actually they doesn't work

**Comment by kevindees** [comment]
Hey @alexadark 

When you echo editor content to the front-end you need to be sure you use `the_content` filter.

https://wordpress.stackexchange.com/questions/173844/apply-filtersthe-content-content-vs-do-shortcodecontent

```php
echo apply_filters('the_content', $field_content);
```

Let me know if this helps for your iframe issue as well.

Thanks,
Kevin

**Comment by alexadark** [comment]
It works, and also for the maps iframes, but i still have a problem with the editor
If i make and empty div, for ex to have a spacer
`<div class="spacer"></div>`
it removes it, so i have to make something like that `<div class="spacer">.</div>` and add a css with text-indent, which is not vary practical
and also it changes the div tag by p tag, which is also annoying as it brings p margins etc...
How can i fix that

**Comment by kevindees** [comment]
Hey @alexadark 

I'm not sure how to fix the problem you are describing here. It sounds like you are facing a WordPress problem at this point. WordPress must be stripping and reformatting the code for you.

You may need to dig into how WordPress handles your specific design.

Thanks,
Kevin

**Comment by alexadark** [comment]
Actually i think it is a editor problem, as i never add this problem with the wordpress editor...
