### ISSUE TITLE
Can't get tr_users_field('fieldname') value

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#7]
Hi,

I just created custom field on user profile's setting. It shows on that setting page. But, when i want to use it on the theme, it returned nothing with this format `$value = tr_users_field('[fieldname]');`. The Typerocket version is 2.0.13

Thanks,
Bagus

**Comment by kevindees** [comment]
TypeRocket has three automations for user fields. First, it looks for the global `$user_id`. If that is not present it looks for the post authors ID. If that is not present it looks for the currently logged in users ID.

If none of these work try passing in the user ID.

``` php
// current user
$current_user_id = get_current_user_id();
tr_users_field("[job_title]", $current_user_id);

// specific id
tr_users_field("[job_title]", 1);
```

**Comment by ghost** [comment]
Thank you for instructions, Kevin. :D
Sorry I did not notice about current user ID, although it is in the documentation.

Again, thanks :+1:
