### ISSUE TITLE
Builder retrieve data from radio button

### ISSUE THREAD

**Issue by bradleydurham** [TypeRocket/typerocket#72]
I am in the process of setting up Builder with a custom post type. I want to have one of the elements be an image floated to either the left or right of some text. So I setup a radio button to let the user select Image Left or Image Right. I am having some issue getting the value to show up in the code. 

Code for the post creation section
```php
<h1>2 Column 50-50 Image-Content Layout</h1>
<?php
/** @var $form \TypeRocket\Elements\Form */
$options = [
	'Image Left'	=>	'l',
	'Image Right'	=>	'r'
];

echo $form->text('Headline');
echo $form->editor('Content');
echo $form->image('Image');
echo $form->text('Image alt text');
echo $form->radio('Image Position')->setOptions($options);
```

Code for the output
```php
<div class="builder-content-half">
    <h2><?php echo esc_html($data['headline']); ?></h2>
    <hr />
    <?php echo wpautop( $data['content'] ); ?>
</div>
<div class="builder-image-<?php echo esc_html($data['image-postion']);?>">
	<?php 
		$image_id = wp_get_attachment_image_src($data['image'], 'full'); 
		$image_alt = $data['image_alt_text'];
	?>
	<img src="<?php echo $image_id[0];?>" alt="<?php echo $image_alt;?>">
</div>
```

**Comment by kevindees** [comment]
Hey @bradleydurham 

This should be a simple fix. Change `image-postion` to `image_postion`. Field names with spaces use `_` instead of `-`.

Thanks,
Kevin

**Comment by bradleydurham** [comment]
Ahh... typos. Thanks for catching that. Works like a charm.
