### ISSUE TITLE
Rendering labels on frontend forms

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#73]
Hi All,

I have reviewed the documentation and I can't seem to find anything on this, so apologies if I'm missing something obvious.

Out of the box, when rendering frontend forms, the system seems to output spans of class label as the input labels.

Is there any builtin way to render actual labels that reference the names of the inputs, like the following:

`<label for="example_field">Example Field Title</label>`

I know I can render the raw field and build the associated html myself, but I'd prefer to avoid that if possible!

Thanks for all the work, very impressed with typerocket so far!

**Comment by kevindees** [comment]
Hey @alans-webdesign 

There is a way to override the templating if you want to but it requires creating your own `Form` class and registering it in the `config/app.php` file. It takes knowing a little PHP OOP to do so.

https://github.com/TypeRocket/typerocket/blob/master/config/app.php#L66

First, you will need to make a new class under your `app` folder `app/Form.php` and extend the `TypeRocket\Elements\From` class.

```php
<?php

namespace App;

class Form extends \TypeRocket\Elements\Form
{
}
```

Update the config file to use that new class `\App\Form::class` and then override the `getLabel` method with whatever you like.

```php
<?php

namespace App;

class Form extends \TypeRocket\Elements\Form
{
    /**
     * Get the Form Field Label
     *
     * @return string
     */
    protected function getLabel()
    {
        $open_html  = "<div class=\"control-label\"><span class=\"label\">";
        $close_html = '</span></div>';
        $debug      = $this->getDebug();
        $html       = '';
        $label      = $this->currentField->getLabelOption();
        $required   = $this->currentField->getRequired() ? '<span class="tr-required">*</span>' : '';
        if ($label) {
            $label = $this->currentField->getSetting( 'label' );
            $html  = "{$open_html}{$label} {$required} {$debug}{$close_html}";
        } elseif ($debug !== '') {
            $html = "{$open_html}{$debug}{$close_html}";
        }
        return $html;
    }

}
```

I'm not sure if you editing the field will break any aa spin and see what you can do with it. Also, note that `tr_form()` will now use your new `\App\Form` class. And, you can add any number of methods you want to it.

Thanks,
Kevin

**Comment by ghost** [comment]
Brilliant, thanks for this. Working very well now. 

On a related issue, I now see that the inputs don't have id's rendered by default.

I know that I can do a `$form->text( 'Post Title', array( 'id'=>'tr[post_title]' ) );` to get the id to render, but I don't think this is very sustainable in the long run.

Is it possible to override the `\TypeRocket\Elements\Fields\Field` setup() method to include something like:

`$this->setAttribute('id', $this->getNameAttributeString() );`

I have an App\Field class that defines the setup() method, but I cannot figure out how to get my App\Form to use my new Field class.

Thanks again.

**Comment by kevindees** [comment]
Hey @alans-webdesign 

Yes. There is a WP hook that runs at the end of the field setup process.

```php
add_action('tr_after_field_element_init', function($field) {
    $this->setAttribute('id', $this->getNameAttributeString() );
});
```

Let me know if this helps.

Thanks,
Kevin

**Comment by ghost** [comment]
Working Perfectly. 

Thanks again!
