### ISSUE TITLE
Date field in repeater

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#74]
Hi again,

I am encountering an issue when adding a date field to a repeater in the backend.

I have tried adding a repeater with a date field to both a metabox and to the setTitleForm with no joy.

To elaborate: the repeater displays correctly, and I can add & remove repeater items. The date field renders correctly & the calendar appears on click, but when I try to select a date I get the following:

`Uncaught TypeError: Cannot set property 'currentDay' of undefined
    at c._selectDay (datepicker.min.js?ver=1.11.4:11)
    at HTMLTableCellElement.selectDay (datepicker.min.js?ver=1.11.4:11)
    at HTMLTableCellElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLTableCellElement.r.handle (jquery.js?ver=1.12.4:3)`

I had thought that this issue could be related to my previous modification to the Field class, but I have reverted these changes and the issue persists.

Any thoughts?

**Comment by kevindees** [comment]
It might be that you are using the same ID on multiple fields. I have tried to recreate your bug and have had little luck. Do you have any duplicate IDs?

https://stackoverflow.com/questions/17781425/datepicker-returning-uncaught-typeerror-undefined-currentday

**Comment by ghost** [comment]
It is to do with IDs! When I do the `$field->setAttribute('id', $field->getName() );` in the `tr_after_field_element_init` action, the datepickers stop working in repeaters.

There are no duplicate IDs, and regardless of what I set the IDs to (e.g. guids) the datepickers don't work. Everything works well if I leave the IDs empty.

When debugging the JS, I can see that the datepicker element evaluates like this when IDs are populated:

`<input type="text" data-name="tr[work_history][{{ work_history }}][start_date]" value="" id="db1b997c-e990-4054-a69d-5f21c9448979" class="date-picker">`

And like this when IDs are not populated

`<input type="text" value="" class="date-picker hasDatepicker" name="tr[work_history][1510349801153][start_date]" id="dp1510349798736">`

There is definitely an issue occurring when I set the ID that causes the {{work_history}} not to render correctly but determining what that is is beyond me!

**Comment by kevindees** [comment]
@alans-webdesign 

I think this is because the datepicker JS adds an ID to the field on the fly and chokes when you already have one for some reason. Might be worth trying to use a different datepicker or simply coding the data fields to ignore your label ID code using `instanceof` on the current field. http://php.net/manual/en/internals2.opcodes.instanceof.php

**Comment by ghost** [comment]
Hi @kevindees,

I have successfully disabled the id/label customisation on datepicker fields using the instanceof method you describe above. 

This is fine as a temporary workaround, unfortunately a lot of the sites I create must conform to the WCAG AA accessibility guidelines (which states that each label must reference the related control using the _for_ attribute).

I believe I have tracked down the core issue though:

When a repeater is rendered on the form, it renders the _tr-repeater-group-template_ as hidden. 

In my custom _tr_after_field_element_init_ action, I am setting the id of the field to the value of _$field->getNameAttributeString()_, this renders the id on the field in the hidden _tr-repeater-group-template_ as _tr[field_name]_ (note that this does not include the {{repeater_name}} placeholder that would be replaced via js).

When the repeater group template gets duplicated, the id is also duplicated, which causes the datepicker JS to choke.

I believe that a modification to the repeater functionality in core.js (to replace all instances of {{repeater_name}}) and a modification to how I am currently generating the field ids would do the trick.

Are there any future plans to make the forms generated by typerocket adhere to accessibility standards? 

**Or** 

Is there any way to grab a copy of the unminified sources for typerocket/wordpress/assets/typerocket/js/core.js so I could make the required changes myself?

Many thanks,

**Comment by kevindees** [comment]
Hey @alans-webdesign 

I do plan to update TypeRocket son to allow for using labels and also applying IDs inside repeater fields. To your point of accessibility. I want to make sure everyone can use TypeRocket as best possible and labels would be very helpful in that.

As for update the JS files TypeRocket uses NPM. The best way to edit the core compiled JS is to pull in the NPM code and recompile it after editing the JS.

https://typerocket.com/docs/v3/updating/#section-assets

Let me know if this helps.

Thanks,
Kevin

**Comment by ghost** [comment]
Hi Kevin,

That's great - very helpful.

Thanks,
Alan.
