### ISSUE TITLE
Question about repeater field count

### ISSUE THREAD

**Issue by nabileisa** [TypeRocket/typerocket#75]
Hi , first thank you for the great work you are doing here. 
I have been playing around with the different field types Type Rocket have to offer and i have a quick question : 
Can we set minimum and maximum number of instances of the `repeater` field ?

Also on a side note : could you make the `'Clear'` button for the image field translatable for consistency
thanks.

**Comment by kevindees** [comment]
Hey @nabileisa 

There is currently not option to set a limit for repeater fields but I have had the requested before so I will likely add that feature. If you need it now you can always add a little JS "counter" of your own.

For the clear button I must have missed it. It is now in the latest update. https://github.com/TypeRocket/core/releases/tag/v3.0.47

Thanks,
Kevin

**Comment by nabileisa** [comment]
Hey @kevindees  , thanks for the quick reply , and the quick fix for the clear button.
As for the repeat field ,  sure thing a simple counter can be implemented in JS but it would be great if this is a core feature as well as the ability to create predetermined number of instances of the field on page load and i hope to see it in the future .
