### ISSUE TITLE
TR with WordPress Widgets 

### ISSUE THREAD

**Issue by cliftonc0613** [TypeRocket/typerocket#76]
@kevindees,
So I am wanting to create a widget where I can use a repeater and add four images with links and look like the image below. I searched the docs and couldn't find anything talking about how to attach fields to widgets.
![screen shot 2017-11-12 at 1 35 01 pm](https://user-images.githubusercontent.com/1175246/32702036-94f77bc0-c7ae-11e7-8983-aee7c11bc74b.png)

**Comment by kevindees** [comment]
Hey @cliftonc0613 

I was able to add the ability to use TypeRocket custom fields within widgets. You may need to apply some custom CSS to make the widgets look better at this point. However, I will be updating the design for widget in the near future.

You will need to run `composer update` to get the latest version of TypeRocket https://github.com/TypeRocket/core/releases/tag/v3.0.48.

Here is the fastest way to make a custom widget using TypeRocket (update to your liking):

```php
class Tr_Widget extends \TypeRocket\Register\BaseWidget {

    /**
     * Sets up the widgets name etc
     */
    public function __construct() {
        parent::__construct( 'tr_widget', 'Tr Widget', [
            'classname' => 'Tr_Widget',
            'description' => 'Tr Widget is awesome'
        ] );
    }

    public function backend($fields)
    {
        echo $this->form->text('Title');
        echo $this->form->date('Date');
    }

    public function frontend($args, $fields)
    {
        // make frontend code
    }

    public function save($new_fields, $old_fields)
    {
        // You will want to sanitize your $new_fields data 
        return $new_fields;
    }
}
```

Then register it in WordPress.

```php
add_action( 'widgets_init', function(){
    register_widget( 'Tr_Widget' );
});
```
