### ISSUE TITLE
frontend form not working in plugin

### ISSUE THREAD

**Issue by developerpaddy** [TypeRocket/typerocket#77]
I was so wondered to work with a great framework. This is my first time I started to develop my own plugin just inspired from typerocket. Thanking you for such a great efforts.

My issue is:
I have installed typerocket in plugin which works great.
I registered custom post type and developed form for it, works great in admin area. But I want that form at front end side so that people can submit their details.

**I am working on LOCALHOST**

I have routes for it into routes.php file:
`tr_route()->any('/businesses/add_edit', 'busiform@Businesses');`

_I tried get,put, any routes_

created controller with GALAXY CLI command provided at website guide:
`class BusinessesController extends Controller
{

	public function busiform(){
		return tr_view('businesses.form');
	}

}`

and in resources/businesses/form.php:

`<?php echo "This is front end"; ?>`

but when I visit siteurl/businesses/add_edit
it shows 404 error.

What I did wrong?

Is there any best practices or tutorial for frontend form in typerocket working in plugin?

**Comment by kevindees** [comment]
Hey @developerpaddy 

Your issue might be around your Kernel configuration and middleware. I had someone else with a similar question here: https://github.com/TypeRocket/typerocket/issues/70

You may need to comment out the `AuthRead::class` from your Kernel as well and set a blank middleware group that matches the name of your resource.

```php
class Kernel extends \TypeRocket\Http\Kernel
{
protected $middleware = [
'hookGlobal' => [],
'resourceGlobal' => [
   AuthRead::class, // maybe comment out the auth read here
   Middleware\VerifyNonce::class
],
'noResource' => [AuthAdmin::class ],
'user' => [IsUserOrCanEditUsers::class ],
'post' => [OwnsPostOrCanEditPosts::class ],
'page' => [OwnsPostOrCanEditPosts::class ],
'comment' => [OwnsCommentOrCanEditComments::class ],
'option' => [CanManageOptions::class ],
'category' => [CanManageCategories::class ],
'tag' => [CanManageCategories::class ],
'businesses' => [], // maybe bank middleware group... might be 'business' too, not sure
];
}
```
