### ISSUE TITLE
Empty image field in custom taxonomy

### ISSUE THREAD

**Issue by nicolasleon** [TypeRocket/typerocket#78]
When saving an item from a custom taxonomy, the image field attached to it stays empty.
 
The custom taxonomy is created like this

```php
// Create a taxonomy for record post type
$category = tr_taxonomy(__('Categorie (structures)'), __('Categories (structures)'));
$category->setId('guide_category');

// Champ Illustration pour les taxonomie record, event
$category->setMainForm(function() {
    $form = tr_form();
    echo $form->image('illustration')->setLabel('Illustration de rubrique')->setHelp('Ajouter ici l\'image d\'illustrtaion de la rurique principale (Dimension : 800x300)');
});

```

Taxonomy controller an model are created with this Galaxy command:

```
php galaxy make:model -c term GuideCategory
```

**Comment by kevindees** [comment]
Hey @nicolasleon 

What does your Model class look like for that taxonomy?

Thanks,
Kevin

**Comment by nicolasleon** [comment]
Hi Kevin,
the model looks like this:

```php
<?php
namespace App\Models;

use \TypeRocket\Models\WPTerm;

class GuideCategory extends WPTerm
{
    protected $taxonomy = 'guide_category';
}
```

**Comment by kevindees** [comment]
@nicolasleon 

Does this error happen when making a new term, or updating a term, or both?

Thanks,
Kevin

**Comment by nicolasleon** [comment]
It happens when creating and updating a term.

When in dev mode and adding a new entry for the custom term, the dev hint shows

`tr_taxonomies_field('illustration', 'category', $id);`

Shouldn't it be:

`tr_taxonomies_field('illustration', 'guide_category', $id);`

Thanks,
Nicolas

**Comment by kevindees** [comment]
The latest version should fix your issue. All you need to do is run `composer update` and get v3.0.50 https://github.com/TypeRocket/core/releases/tag/v3.0.50

**Comment by SaeedSoltoon** [comment]
Hi @kevindees ,
same problem,
this issue still remains after running `composer update` and  the image field attached to it stays empty.
Dear @nicolasleon , is your problem solved?

**Comment by twosg** [comment]
Hi @SaeedSoltoon @nicolasleon @kevindees,

Unfortunately I encounter the same problem, with latest 3.x. I also have just simple code like @nicolasleon.

Were you able to solve it?
