### ISSUE TITLE
Use Typerocket as plugin

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#8]
Hi Kevin,
I have not tried it. Can we use Typerocket as a plugin? I didn't find it on documentation/tutorial.

Thanks,
Bagus

**Comment by kevindees** [comment]
Hey,

I have yet to add it to the docs like you said. But, you can do it. Here is the plugin code I use right now. You will need to know how to create a plugin though.

![screen shot 2015-10-30 at 8 22 50 am](https://cloud.githubusercontent.com/assets/348368/10845590/77117aee-7edf-11e5-8528-17376feeed6f.png)

File name: `typerocket/typerocket.php`

``` php
<?php
/*
Plugin Name: TypeRocket
Plugin URI: http://typerocket.com/
Description: For all your custom TypeRocket needs.
Version: 20000
Author: TypeRocket
Author URI: http://typerocket.com/
License: GPLv2 or later
*/

include('typerocket/init.php');
```

Create a typerocket `config.php` file within the typerocket folder: `typerocket/typerocket/config.php`

``` php
<?php
/*
|--------------------------------------------------------------------------
| TypeRocket Folder
|--------------------------------------------------------------------------
|
| The name of the folder containing TypeRocket.
|
*/
define('TR_FOLDER', 'typerocket');
define('TR_DEBUG', true);
define('TR_PLUGINS', 'docs');
define('TR_MATRIX_FOLDER_PATH', __DIR__ . '/matrix');
define('TR_APP_FOLDER_PATH', __DIR__ . '/app');
define('TR_PLUGINS_FOLDER_PATH', plugin_dir_path(__FILE__) . '/plugins');
define('TR_PLUGINS_URL', plugin_dir_url(__FILE__) . '/plugins');
define('TR_ASSETS_URL', plugin_dir_url(__FILE__) . '/assets');
define('TR_SEED', 'new_seed_there');
```

This will get you going at very basic level but you may need to configure things differently based on your needs.

Thanks,
Kevin
