### ISSUE TITLE
Updating user data from meta box doesn't work

### ISSUE THREAD

**Issue by ipaulin** [TypeRocket/typerocket#80]
Hello,

I've created a meta box on dashboard screen where I want to have a form for updating user fields.
Problem is that when I submit the form, the data is not changing/updating in the database. 

I've installed Typerocket inside the plugin, and I'm using this code in theme's functions.php file:

`add_action('typerocket_loaded', function() {
  
  $box = tr_meta_box('Author Details');
  $box->addScreen('dashboard');
  
  $box->setCallback(function() {
    $user = tr_form('user', 'update', 1);
    $user->useAjax()->useJson();
    echo $user->open();
    echo $user->text('user_url');
    echo $user->close('Update');
  });

});`

This is the errors I get in debug file:

`PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /srv/www/myw/public_html/wp-content/plugins/my-plugin/includes/typerocket/vendor/typerocket/core/src/Http/Request.php on line 113`

`PHP Notice:  Trying to get property of non-object in /srv/www/myw/public_html/wp-content/plugins/my-plugin/includes/typerocket/vendor/typerocket/core/src/Http/Middleware/IsUserOrCanEditUsers.php on line 21`

I've tried to install Typerocket inside the theme and as a root installation, but this error always appears and updating of users data is not working.

Thanks,
Ivan

**Comment by kevindees** [comment]
Hey @ipaulin 

I'm not seeing anything strange with the code you have written. Have you checked your database to ensure there is a user with the ID of `1`?

I'll also go in and see if this is a bug.  I have not see this issue before.

Thanks,
Kevin
