### ISSUE TITLE
Plugin structure with typerocket

### ISSUE THREAD

**Issue by arunaseva** [TypeRocket/typerocket#81]
Hi,

I have difficulties how to structure plugin.  There is a lot of plugin skeleton for WP, but I need a typerocket conform one. What is the best practice?  In the documentation I can not see finished example plugin to investigate.

Can you link or send some plugin that is created with typerocket 3 ?

Thanks, Adam

**Comment by kevindees** [comment]
Hey @arunaseva 

I do not have a completed plugin example. I can look into getting something made to help in the documentation at some point.

However, we do have some documentation on how to install TypeRocket into a plugin here: https://typerocket.com/docs/v3/#section-plugin-installation

Thanks,
Kevin
