### ISSUE TITLE
Wordpress Editor in Repeat

### ISSUE THREAD

**Issue by vanhuy12toan2** [TypeRocket/typerocket#82]
Hi again,
I am encountering an issue when adding a wpEditor field to a repeater in the backend. The wordpress Editor not working in repeat field. I can't not type any word.

**Comment by vanhuy12toan2** [comment]
In class WordPressEditor, I edited $editor_id from method wp_editor. And It worked.
I hope you fix this
![image](https://user-images.githubusercontent.com/19154697/34650423-ba4c1c48-f3f3-11e7-9ea7-aa78edc777e9.png)

**Comment by kevindees** [comment]
Hey @vanhuy12toan2 

I'll get a fix added in for this.

Thanks for the help on this one,
Kevin

**Comment by zoephilipps** [comment]
@kevindees Any update on this?

**Comment by kevindees** [comment]
Hey @zackphilipps 

I added the suggested code just now. However, I'm not sure it will completely make the WP Editor compatible repeaters. I recommend using the standard `editor()` field over the WP Editor. The WP Editor was never really designed to be that dynamic.

To make the WP Editor increment use the `increment()` method with the editor. 

```php
$form->wpEditor('Content')->increment();
```

Note: You may need to run `composer update`.

Thanks,
Kevin

**Comment by zackphilipps** [comment]
@kevindees This should work in theory, but it is not working for multiple WYSIWYGs within a Page Builder field. 🙁 

I understand where you're coming from, but [Advanced Custom Fields](https://www.advancedcustomfields.com/) manages to pull this off. In our case, we also have some tinymce customization on the WP Editor that would be improbable to duplicate with the Redactor editors. Migrating from ACF to TR we are losing the functionality of having multiple custom WYSIWYGs on a page.

**Comment by zoephilipps** [comment]
@kevindees just FYI to get this to work properly when adding components to a builder field, the following JS is required: 

```js
TypeRocket.repeaterCallbacks.push(function($template) {
  var $tinymce = $template.find('.wp-editor-area')
  $tinymce.each(function() {
    tinyMCE.execCommand('mceAddEditor', false, $(this).attr('id'))
  })
})
```

In addition, I had to change `(WordPressEditor::$count++)` to `uniqid()` since it would not increment asynchronously. I'll open a PR for that.
