### ISSUE TITLE
Issue with ajax post update

### ISSUE THREAD

**Issue by futuredesigngroup** [TypeRocket/typerocket#84]
I am trying to send a post update since one of my values is too long for a get request but I keep getting a invalid CSRF token. I have made sure the route is there (even though it returns a 404 when accessed directly). If I change it to a get route it works fine but again, I cannot use it that way.

Any suggestions?

**Comment by kevindees** [comment]
What does your code look like?

**Comment by futuredesigngroup** [comment]
No worries. This issue has been resolved. I added the function inside of the route call instead of the controller and it worked just fine.
