### ISSUE TITLE
Send Email After Adding CPT Post

### ISSUE THREAD

**Issue by futuredesigngroup** [TypeRocket/typerocket#85]
Is there a way to send an email once a post has been added to a custom post type that we created? I want the user to be able to add a post (our custom post type) through the admin, then once they either publish the post or update it, it will send an email to the email of their choice. Is this possible with TypeRocket or is it more of a WordPress function thing?

**Comment by kevindees** [comment]
This will be more of a WordPress thing. You can hook into the here I think:

https://codex.wordpress.org/Plugin_API/Action_Reference/publish_post
