### ISSUE TITLE
tr_route not working?

### ISSUE THREAD

**Issue by jwarnox** [TypeRocket/typerocket#86]
I am loving this framework, brilliant work and have been following through the guides all day, but cannot get **tr_route** to work?

I have in my functions.php:
```
tr_frontend();
```
I have this form in my template:

```
<div class="typerocket-container">
        <?php 
          $id = get_the_ID();
          $form = tr_form();
          $form
            ->useURL( 'PUT', '/foo/'.$id.'/' )
            ->useAjax();

          echo $form->open();
          echo $form->text('Title');
          echo $form->close('Update Book');
        ?>
      </div>
```

and to test tr_route have this in routes.php:

```
tr_route()->put('/foo/{id}/', function( $path, \TypeRocket\Http\Request $request, $wilds ) {
   echo $path;
   return var_dump($wilds);
});
```

But I just keep getting a 404 error, I have tried creating a Controller and using tr_view in a show method etc... but nothing is working - can you please help? this will be a deal breaker in using this in my next project.

regards,
Jamie

**Comment by kevindees** [comment]
Hey @jwarnox 

Thanks for the kind words. I believe, you need to tell the from object what to expect in terms of input.

https://typerocket.com/docs/v3/forms/#section-use-url

```
$id = get_the_ID();
$form = tr_form('post', 'update', $id);
$form->useURL( 'PUT', '/foo/'.$id.'/' )->useAjax();
```

Thanks,
Kevin

**Comment by jwarnox** [comment]
Hi kevin,

Tried that and still getting 404, changed ->useAjax to ->useJson and got a flash message of Post Updated. but no return from my tr_route?

For testing I changed my custom route to a GET request...

```
tr_route()->get('/foo/{id}/', function( $path, \TypeRocket\Http\Request $request, $wilds ) {
   echo $path;
   return var_dump($wilds);
});
```

...and requested this route on my dev site - http://79.170.40.235/wptyperocket.co/foo/7/

and still got a 404, ran out of ideas of what I am doing wrong here? click the link above but i should be getting returned the var_dump in my custom route? Hmmm.

**Comment by kevindees** [comment]
Hey @jwarnox 

Looks like you found a bug. It is now fixed in the core version 3.0.52. You should just need to run `composer update` on the tyeprocket folder.

Thanks,
Kevin

**Comment by jwarnox** [comment]
Great thanks Kevin,

I will update tonight and feedback to you my results!

Thanks,
Jamie

**Comment by jwarnox** [comment]
Hi Kevin,

Working now, great thanks, but I think I am not understanding how the response Class should work as the docs are missing for the developers REST API - https://typerocket.com/docs/v3/rest-api/

I presently have in my Controller Class handler:

```
public function update ( $id ) {
    $fields = $this->request->getFields();
    //var_dump($fields);

    $this->response->setData([
      'id' => $id,
      'fields' => $fields
    ]);
  }
```

you can see I am retrieving the requested fields and trying to return them with the submitted ID for testing purposes in the response data array, but in my TypeRocket.httpCallbacks in the frontend the data array is empty?

```
{
  blockFlash: false,
  data: [],
  errors: [],
  flash: true,
  message: "No Message Set",
  messageType: "success",
  redirect: false,
  status: 200
}
```

I have also tried to return with json_encode but not working?

```
return json_encode( [
    'id' => $id,
    'fields' => $fields
 ] );
```

Do I need to return the response instance? Can you please advise where I am going wrong please?

regards,
Jamie

**Comment by kevindees** [comment]
Hey @jwarnox 

I plan to put together a good youtube tutorial on how to use the routes, models, and controllers here soon. I'll keep you updated when it is finished. I feel like this will help answer a lot of questions you might have now and down the line.

Thanks,
Kevin

**Comment by jwarnox** [comment]
Thank you Kevin look forward to the video tutorial!
