### ISSUE TITLE
Route Model Binding like Laravel

### ISSUE THREAD

**Issue by jwarnox** [TypeRocket/typerocket#87]
Hi Kevin,

Is Route Model Binding supported like Laravel? this is not working:

routes.php
```
tr_route()->get('/book/{book}', 'view@Book');
```

BookController
```
use \App\Models\Book;

...

public function view ( Book $book ) {
  var_dump($book);
}
```

**Comment by kevindees** [comment]
Hey @jwarnox

We do how route model binding. I'll cover this in the youtube video as well.

As a note the method on the model is:

```php
public function getRouterInjectionColumn()
{
    return strtolower($this->idColumn);
}
```

You can see how the model gets injected here: https://github.com/TypeRocket/core/blob/0aba2700719b2de2c8fc377f96eb1083a57f6605/src/Http/Router.php#L79

Note that the name of the var in the route must math the name of the table Id column:

```php
// correct
tr_route()->get('/book/{id}', 'view@Book');
tr_route()->get('/book/{ID}', 'view@Book'); // I dot not remember if it is case sensitive

// not correct
tr_route()->get('/book/{book}', 'view@Book');
```

Thanks,
Kevin

**Comment by jwarnox** [comment]
Thanks Kevin looking forward to the video!
