### ISSUE TITLE
Data Structure : Custom Post vs Custom Table

### ISSUE THREAD

**Issue by rodmar35** [TypeRocket/typerocket#88]
Hello,

Wow thank you very much for your script. Great Job ! This is not a rocket but rather a bomb ;-) For a long time I was looking for a script like this one.

I develop on Mac with ValetPlus https://github.com/weprovide/valet-plus and I start with Laravel.

I managed to install TypeRocket as root and redo the examples in these videos https://www.youtube.com/channel/UCWABH6tVaqW92nXFMDceeFQ

I would like to develop a plugin for soccer league management like https://wordpress.org/plugins/sportspress/ but I have many questions about the best way to proceed.

My project will have a lot of data and relationship and I prefer not to use Wordpress meta.

Some examples of data: season, competition, clubs, player, games, event (goal, substitutions, red card, ...), ranking, ...

I'm not sure how to start my data structure. 3 possibilities :

- Create a CustomPostType and I store the data in a table in the meta.

- Create a CustomPostType and I try to store the data in a specific custom table with relation.

- Create models and use TypeRocket Base Controller for all my data.

In backoffice:
- I would need a data adminstration system. Via Wordpress or a specific CRUD Laravel?
- I would like to keep and use Wordpress Media Add and Management
- be able to query my data via the wordpress API for example a mobile application

In front:
- there will be several specific pages: match calendar, match sheet, player sheet, statistics, ...
- be able to use shortcodes in an article for example.

As you can see, my project is "quite complex" (for me ;-) ) and I would like not fool me in my choice of structure.

Thank you in advance for your advice
RodMar

**Comment by kevindees** [comment]
Hey @rodmar35 

Thanks for the kind words. I'm glad you like TypeRocket.

When possible I would always reach for Post Types. This will make what you create compatible with tons of plugins. As soon as you go outside of Post Types you start to lose out of the box integration capabilities with other WP plugins. 

I like to use the custom database table setup anytime I have a number of custom fields I need to do complex SQL queries with and I know the scope of the project is not going to need any integrations in the near future.

I hope this helps.

Thanks,
Kevin
