### ISSUE TITLE
Dependency Example Not Found

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#89]
Hello TypeRocket team,
I really appreciate your work, but I have face a problem that I have not found dependency example. 
There have any fields dependency example?
@kevindees

**Comment by kevindees** [comment]
Hey @hannanishfq007 

We do not currently have field dependency built into TypeRocket but it will be in a future release.

Thanks,
Kevin

**Comment by kevindees** [comment]
@hannanishfq007 

You can always use other JS libraries like http://emranahmed.github.io/Form-Field-Dependency/ for what you need as well.

Thanks,
Kevin

**Comment by ghost** [comment]
Thanks,
@kevindees
