### ISSUE TITLE
Theme option's textarea strips the html content

### ISSUE THREAD

**Issue by ghost** [TypeRocket/typerocket#9]
Hi,
I use textarea on theme option page to embed googlemap code (iframe code). When I save it, then reload, the data is lost.

This only happens when the content is HTML, not text.
Is it possible to skip the filter?

Thanks,
Bagus

**Comment by kevindees** [comment]
Hey,

Using the sanitize setting will do the trick.

``` php
$form = tr_form();
echo $form->textarea('Content')->setSetting('sanitize', 'editor');
```

Options are:
- textarea
- raw
- attribute
- url
- sql
- plaintext
- editor
- hex
- underscore
- dash

**Comment by apsolut** [comment]
do we still have this for v6 ?

**Comment by kevindees** [comment]
@apsolut 

This should still be in place. We have not removed it.

**Comment by apsolut** [comment]
> @apsolut
> 
> This should still be in place. We have not removed it.

Thank you (that was fast), my issue was `wpautop()` removing it embedded code works without issues.
