### ISSUE TITLE
TR allows you to change repeater button labels... almost

### ISSUE THREAD

**Issue by zoephilipps** [TypeRocket/typerocket#91]
Hi @kevindees 👋 

First of all, thanks so much for your work on this. Excellent, excellent stuff.

I have a feature request. TR allows you to change the repeater button labels. I want to change "Contract" to "Collapse" and "Flip" to "Reverse Order" to make it more clear what these buttons do. I am able to do this when I initialize the field:

```php
$form->repeater(
  $name, [], [
    'controls' => [
      'contract' => 'Collapse',
      'flip' => 'Reverse Order'
    ]
  ]
);
```

However, the JS is written in a way that prevents the Expand/Collapse button from working once I've made this change (sorry for the beautified minified code):

```js
e(document).on("click", ".tr-repeater .controls .tr_action_collapse", function(t) {
  var r,
    a;
  a = e(this).parent().parent().next().next(),
  "Contract" === e(this).val()
    ? (e(this).val("Expand"), a.find("> .tr-repeater-group").animate({
      height: "90px"
    }, 200))
    : (e(this).val("Contract"), a.find("> .tr-repeater-group").attr("style", "")),
  r = e(this).parent().parent().next().next(),
  r.hasClass("tr-repeater-collapse")
    ? (r.toggleClass("tr-repeater-collapse"), r.find("> .tr-repeater-group").removeClass("tr-repeater-group-collapsed").attr("style", ""))
    : (r.toggleClass("tr-repeater-collapse"), r.find("> .tr-repeater-group").removeClass("tr-repeater-group-expanded")),
  t.preventDefault()
})
```

Please implement variables here so that the text can actually be changed.

Thanks again for your awesome work!

**Comment by kevindees** [comment]
Hey @zackphilipps 

Thanks for submitting this request. There are a lot of JS improvement we want to make and this is a great one to add to the list.

I imagine we may move a lot of our JS into whatever framework (React JS) Gutenburg uses when/if it is launched.

Also, we are working on version 4.0 which will come with a lot of improvements to TypeRocket overall so keep an eye out for that in the coming months.

Thanks,
Kevin

**Comment by zoephilipps** [comment]
@kevindees awesome, thanks for the update!

**Comment by kevindees** [comment]
@zackphilipps 

I just submitted the patch for this to version 4.0. It will go live with the new version.

Thanks,
Kevin
