### ISSUE TITLE
In my custom plugin doesn't work.

### ISSUE THREAD

**Issue by altemberg** [TypeRocket/typerocket#92]
I followed the steps in the guide but I can not make typerocket work in my plugin, I managed to make it work inside the theme, but not in the plugin, which is what I really want.

I changed the paths.php to the correct path of the plugin, you can see the code below:
````
'urls' => [
  'assets' => plugin_dir_url(__DIR__) . 'typerocket/wordpress/assets',
  'components' => plugin_dir_url(__DIR__) . 'typerocket/wordpress/assets/components',
],
````
And the code I used for testing was this:
````
add_action( 'typerocket_loaded', function() {
  tr_post_type('Book');
});
````

And when I tested on the theme appeared the menu "Dev", already with the plugin does not appear.

**Comment by altemberg** [comment]
I solved the problem :)

**Comment by manuman94** [comment]
Hi! Can you please tell us how did you solve it? 

I'm facing the same issue. The custom post type is not appearing in the left sidebar but "Dev" it does. I'm using it in a plugin too.

Greetings.
