### ISSUE TITLE
Set false value on checkbox in theme options

### ISSUE THREAD

**Issue by altemberg** [TypeRocket/typerocket#94]
@kevindees, hi!

I'm trying to set the value of the checkbox as false in my theme options but it only stays true.

I did a test on a CPT and it worked, only in theme options it's not going.

There's something wrong?
````
echo $form->checkbox('sobrescrever')->setSetting('default', false)->setText('Sobrescrever opções padrão')->setLabel(false);
````

Thanks,
Altemberg

**Comment by kevindees** [comment]
Hey @altemberg 

I have made a number of updates in version 4.0 of TypeRocket. If you end up with that version let me know if it fixed your specific issue.

Thanks,
Kevin
