### ISSUE TITLE
instructions not clear on how to install as root

### ISSUE THREAD

**Issue by appsdevpk** [TypeRocket/typerocket#95]
i am trying very hard to understand how to use type rocket as root, as there is no index.php file in the root of typerocket folder and there are no instructions in documentation on how to bootstrap the app.

found the solution myself

**Comment by zoephilipps** [comment]
@appsdevpk what was it?

**Comment by zoephilipps** [comment]
Figured it out. You have to move the contents of the `wordpress/` directory to the root.
