### ISSUE TITLE
Builder within Repeater

### ISSUE THREAD

**Issue by GPurdue** [TypeRocket/typerocket#96]
Hi @kevindees , love the work you've done on TypeRocket.

I'm trying to rebuild a page builder I've built using ACF as it's getting sluggish and clunky. I'm trying to nest the builder within a repeater within another repeater on a page to create rows and columns. The fields all show correctly, but when I click on a builder component to add it to the column it doesn't add it to the box, it creates a secret repeater that only appears when I update the page?!

`$boxPages = tr_meta_box('Page Builder Ultra');
$boxPages->addScreen('page');
$boxPages->setCallback(function(){

	$form = tr_form();

	$col_settings = [
		$build = tr_form(),
		$build->text('Column class'),
		$build->builder('Builder')
	];

	$repeater = $form->repeater('Row')->setFields([
		$form->text('Row class'),
		$form->repeater('Columns')->setFields($col_settings)
	]);
	echo $repeater;
});`

I've probably done something wrong but any help would be brilliant.
Cheers

**Comment by kevindees** [comment]
Hey @GPurdue 

Maybe Try this? You should only need one instance of `tr_form()`.

```php
$boxPages = tr_meta_box('Page Builder Ultra');
$boxPages->addScreen('page');
$boxPages->setCallback(function(){

$form = tr_form();

$col_settings = [
	$form->text('Column class'),
	$form->builder('Builder')
];

$repeater = $form->repeater('Row')->setFields([
	$form->text('Row class'),
	$form->repeater('Columns')->setFields($col_settings)
]);

echo $repeater;
});
```

**Comment by GPurdue** [comment]
Hi @kevindees 

Thanks for replying, this doesn't seem to make any difference though.

Cheers

**Comment by GPurdue** [comment]
Hi @kevindees do you have any ideas on how to get this working at all, or any further code I can try?

Cheers
Gary

**Comment by kevindees** [comment]
Hey @GPurdue 

Instead of a repeater I bet using a matrix field will do the trick. You can use it like a repeater field / builder field.

The matrix field has the same look as the repeater field but the functionality of a builder field. You could use a matrix field with just one component and that may do it for you.

https://typerocket.com/docs/v3/field-types/#section-matrix-and-builder

Thanks,
Kevin

**Comment by GPurdue** [comment]
Hi @kevindees 

Thank you for the reply, did you mean like this?

```
$boxPages = tr_meta_box('Page Builder Ultra');
$boxPages->addScreen('page');
$boxPages->setCallback(function(){

$form = tr_form();

$col_settings = [
	$form->text('Column class'),
	$form->matrix('Ultra Builder')
];

$repeater = $form->repeater('Row')->setFields([
	$form->text('Row class'),
	$form->repeater('Columns')->setFields($col_settings)
]);

echo $repeater;
});
```

This gives the same issues as the other way. The 'Add New' button briefly says 'Adding' then turns back to 'Add New' and nothing happens. Are you able to try this code and see if you can replicate the error or if it works for you and I've done something wrong?

Cheers again
Gary

**Comment by kevindees** [comment]
Hey @GPurdue 

I was thinking like this:

```php
$boxPages = tr_meta_box('Page Builder Ultra');
$boxPages->addScreen('page');
$boxPages->setCallback(function(){
   $form = tr_form();
   echo $form->matrix('Row');
})
```

Then in the single matrix component file:

```php
// matrix component file
$col_settings = [
	$form->text('Column class'),
	$form->builder('Ultra Builder')
];

echo $form->text('Row class'),
echo $form->repeater('Columns')->setFields($col_settings)
```

**Comment by GPurdue** [comment]
Hi @kevindees,

Thanks for the help on this, I've now got a 'Row' matrix with a 'Column' matrix inside with a 'Content' builder inside again (screenshot attached).

![edit page type rocket](https://user-images.githubusercontent.com/17878752/39831774-5ce73d92-53bd-11e8-9e69-41fcece8f853.png)

I'm getting the 'Row' details to show via the visuals folder but I can't get the 'Column' details to show and also then can't get the 'Content' to show from the builder either.

It's suggesting I add the 'Column' using

`<?php tr_components_field('row.1525877061.row.column'); ?>`

I know this might be a long shot, but do you have any ideas if I've gone wrong or taking it further than it was meant to be?

Cheers
Gary

**Comment by kevindees** [comment]
Hey @GPurdue 

The best way to work with nested repeater/matrix fields is to only use the first level function `<?php tr_components_field('row'); ?>`. From there you will need to do a var_dump on the `$data` from that that components visual and create your own look to deal with the nesting. You should be able to use a modified version of the  `tr_components_field` function to get what you want.

I have not tested this but here is an example:

```php
function tr_components_data($name, $builder_data)
{
    if (is_array($builder_data)) {
        foreach ($builder_data as $data) {
            $key       = key($data);
            $component = strtolower(key($data));
            $paths = \TypeRocket\Core\Config::getPaths();
            $file  = $paths['visuals'] . '/' . $name . '/' . $component . '.php';
            if( file_exists($file) ) {
                $fn = function( $file, $data, $name) {
                    /** @noinspection PhpIncludeInspection */
                    include( $file );
                };
                $fn($file, $data[$key], $name);
            } else {
                echo "<div class=\"tr-dev-alert-helper\"><i class=\"icon tr-icon-bug\"></i> Add builder visual here by creating: <code>{$file}</code></div>";
            }
        }
    }

    return $builder_data;
}
```
