### ISSUE TITLE
Add dist download to releases?

### ISSUE THREAD

**Issue by Camzilla** [TypeRocket/typerocket#97]
Non-regular wordpress dev here who doesn't have composer installed. Would prefer not having to install a one-time pm just to be able to download typerocket.
So suggestion: Add a dist version when there's a new releases ❤️

**Comment by kevindees** [comment]
Would this work for you? [typerocket-3.0.9.zip](https://github.com/TypeRocket/typerocket/files/1891786/typerocket-3.0.9.zip)

**Comment by Camzilla** [comment]
Yes it does! Thank you. I also have to confess that I ended up downloading php and composer anyways, Typerocket just seemed too good to pass on.. Totally worth it! Solved all my problems in under a minute 🙂 thank you very much, good job and keep it up!

If that^ doesn't encourage people to install it anyways, please do consider to post a dist version like that with future releases!

**Comment by kevindees** [comment]
@Camzilla 

Thanks for the kind words :) I'll keep in mind posting dist versions with future releases.

Thanks,
Kevin
