### ISSUE TITLE
Is it possible to restrict components to certain pages?

### ISSUE THREAD

**Issue by alesub** [TypeRocket/typerocket#99]
Hi,

Is it possible to restrict components to pages with a given page template or custom field set? For example, a home page has certain components that won't be present in any other page, then some inner pages use information from a parent page to display certain data, so a component should be available only for that type of page.

Is it possible to apply this kind of restriction? It's the only feature I see missing, otherwise typerocket seems to have it all.

Thanks!

**Comment by kevindees** [comment]
Hey @alesub 

You will need to work a little WordPress magic yourself using the builtin WordPress hooks core offers but I would think that you can. By default, the matrix and builder fields pull the components base on the files it finds but you can set your own list using the `setOptions()` method. You would need to use this method and the WordPress hooks. However, I have tried this in the past and it never really does what you would want.

I think the best option would be to use jQuery to listen of an on change event of the template select input and modify the build/matrix select list and added components using regular javascript. There are just too many gotchas using PHP to get what you are wanting.

I hope this helps,
Kevin
